import { defineConfig } from "tsdown";

export default defineConfig({
  entry: {
    index: "src/index.ts",
    cli: "src/cli.ts",
    "ai-sdk/index": "src/ai-sdk/index.ts",
    "catalog/index": "src/catalog/index.ts",
    // The literal-preserving registry, on its own specifier for the reason
    // docs/decisions.md §3 gives for `unmodel/chat/factory`: its bundled
    // declaration is ~5 MB against a few KiB for `catalog/index`, and the
    // cheap path has to be the only path. Both are pinned in
    // test/bundle-budget.test.ts.
    "catalog/typed.gen": "src/catalog/typed.gen.ts",
    "chat/index": "src/chat/index.ts",
    "chat/factory": "src/chat/factory.ts",
    // The six unified media surfaces. Each is the kernel plus a factory — the
    // provider adapters are named by the caller, so these entries stay small
    // (pinned in test/bundle-budget.test.ts) no matter how many adapters ship.
    "unified/image": "src/unified/image.ts",
    "unified/image-edit": "src/unified/image-edit.ts",
    "unified/video": "src/unified/video.ts",
    "unified/speech": "src/unified/speech.ts",
    "unified/transcribe": "src/unified/transcribe.ts",
    "unified/music": "src/unified/music.ts",
    "providers/alibaba/index": "src/providers/alibaba/index.ts",
    "providers/amazon-bedrock/index": "src/providers/amazon-bedrock/index.ts",
    "providers/anthropic/index": "src/providers/anthropic/index.ts",
    "providers/assemblyai/index": "src/providers/assemblyai/index.ts",
    "providers/assemblyai/unified": "src/providers/assemblyai/unified.ts",
    "providers/azure/index": "src/providers/azure/index.ts",
    "providers/baseten/index": "src/providers/baseten/index.ts",
    "providers/black-forest-labs/index": "src/providers/black-forest-labs/index.ts",
    "providers/black-forest-labs/unified": "src/providers/black-forest-labs/unified.ts",
    "providers/bria/index": "src/providers/bria/index.ts",
    "providers/bria/unified": "src/providers/bria/unified.ts",
    "providers/bytedance/index": "src/providers/bytedance/index.ts",
    "providers/bytedance/unified": "src/providers/bytedance/unified.ts",
    "providers/cartesia/index": "src/providers/cartesia/index.ts",
    "providers/cartesia/unified": "src/providers/cartesia/unified.ts",
    "providers/cerebras/index": "src/providers/cerebras/index.ts",
    "providers/cloudflare-workers-ai/index": "src/providers/cloudflare-workers-ai/index.ts",
    "providers/cohere/index": "src/providers/cohere/index.ts",
    "providers/deepgram/index": "src/providers/deepgram/index.ts",
    "providers/deepgram/unified": "src/providers/deepgram/unified.ts",
    "providers/deepinfra/index": "src/providers/deepinfra/index.ts",
    "providers/deepseek/index": "src/providers/deepseek/index.ts",
    "providers/elevenlabs/index": "src/providers/elevenlabs/index.ts",
    "providers/elevenlabs/unified": "src/providers/elevenlabs/unified.ts",
    "providers/fireworks-ai/index": "src/providers/fireworks-ai/index.ts",
    "providers/fish-audio/index": "src/providers/fish-audio/index.ts",
    "providers/fish-audio/unified": "src/providers/fish-audio/unified.ts",
    "providers/friendli/index": "src/providers/friendli/index.ts",
    "providers/gladia/index": "src/providers/gladia/index.ts",
    "providers/gladia/unified": "src/providers/gladia/unified.ts",
    "providers/google/index": "src/providers/google/index.ts",
    "providers/google/unified": "src/providers/google/unified.ts",
    "providers/google-vertex/index": "src/providers/google-vertex/index.ts",
    "providers/groq/index": "src/providers/groq/index.ts",
    "providers/huggingface/index": "src/providers/huggingface/index.ts",
    "providers/hume/index": "src/providers/hume/index.ts",
    "providers/hume/unified": "src/providers/hume/unified.ts",
    "providers/ideogram/index": "src/providers/ideogram/index.ts",
    "providers/ideogram/unified": "src/providers/ideogram/unified.ts",
    "providers/inception/index": "src/providers/inception/index.ts",
    "providers/inworld/index": "src/providers/inworld/index.ts",
    "providers/inworld/unified": "src/providers/inworld/unified.ts",
    "providers/kling/index": "src/providers/kling/index.ts",
    "providers/kling/unified": "src/providers/kling/unified.ts",
    "providers/krea/index": "src/providers/krea/index.ts",
    "providers/krea/unified": "src/providers/krea/unified.ts",
    "providers/leonardo/index": "src/providers/leonardo/index.ts",
    "providers/leonardo/unified": "src/providers/leonardo/unified.ts",
    "providers/lightricks/index": "src/providers/lightricks/index.ts",
    "providers/lightricks/unified": "src/providers/lightricks/unified.ts",
    "providers/lmnt/index": "src/providers/lmnt/index.ts",
    "providers/lmnt/unified": "src/providers/lmnt/unified.ts",
    "providers/longcat/index": "src/providers/longcat/index.ts",
    "providers/luma/index": "src/providers/luma/index.ts",
    "providers/luma/unified": "src/providers/luma/unified.ts",
    "providers/meta/index": "src/providers/meta/index.ts",
    "providers/minimax/index": "src/providers/minimax/index.ts",
    "providers/minimax/unified": "src/providers/minimax/unified.ts",
    "providers/mistral/index": "src/providers/mistral/index.ts",
    "providers/mistral/unified": "src/providers/mistral/unified.ts",
    "providers/moonshotai/index": "src/providers/moonshotai/index.ts",
    "providers/murf/index": "src/providers/murf/index.ts",
    "providers/murf/unified": "src/providers/murf/unified.ts",
    "providers/nebius/index": "src/providers/nebius/index.ts",
    "providers/novita-ai/index": "src/providers/novita-ai/index.ts",
    "providers/nvidia/index": "src/providers/nvidia/index.ts",
    "providers/openai/index": "src/providers/openai/index.ts",
    "providers/openai/unified": "src/providers/openai/unified.ts",
    "providers/openai-compatible/index": "src/providers/openai-compatible/index.ts",
    "providers/openrouter/index": "src/providers/openrouter/index.ts",
    "providers/perplexity/index": "src/providers/perplexity/index.ts",
    "providers/pixverse/index": "src/providers/pixverse/index.ts",
    "providers/pixverse/unified": "src/providers/pixverse/unified.ts",
    "providers/recraft/index": "src/providers/recraft/index.ts",
    "providers/recraft/unified": "src/providers/recraft/unified.ts",
    "providers/resemble/index": "src/providers/resemble/index.ts",
    "providers/resemble/unified": "src/providers/resemble/unified.ts",
    "providers/revai/index": "src/providers/revai/index.ts",
    "providers/revai/unified": "src/providers/revai/unified.ts",
    "providers/reve/index": "src/providers/reve/index.ts",
    "providers/reve/unified": "src/providers/reve/unified.ts",
    "providers/rime/index": "src/providers/rime/index.ts",
    "providers/rime/unified": "src/providers/rime/unified.ts",
    "providers/runway/index": "src/providers/runway/index.ts",
    "providers/runway/unified": "src/providers/runway/unified.ts",
    "providers/sarvam/index": "src/providers/sarvam/index.ts",
    "providers/scaleway/index": "src/providers/scaleway/index.ts",
    "providers/siliconflow/index": "src/providers/siliconflow/index.ts",
    "providers/smallest-ai/index": "src/providers/smallest-ai/index.ts",
    "providers/smallest-ai/unified": "src/providers/smallest-ai/unified.ts",
    "providers/soniox/index": "src/providers/soniox/index.ts",
    "providers/soniox/unified": "src/providers/soniox/unified.ts",
    "providers/speechify/index": "src/providers/speechify/index.ts",
    "providers/speechify/unified": "src/providers/speechify/unified.ts",
    "providers/speechmatics/index": "src/providers/speechmatics/index.ts",
    "providers/speechmatics/unified": "src/providers/speechmatics/unified.ts",
    "providers/stability/index": "src/providers/stability/index.ts",
    "providers/stability/unified": "src/providers/stability/unified.ts",
    "providers/stepfun/index": "src/providers/stepfun/index.ts",
    "providers/togetherai/index": "src/providers/togetherai/index.ts",
    "providers/upstage/index": "src/providers/upstage/index.ts",
    "providers/vercel/index": "src/providers/vercel/index.ts",
    "providers/vidu/index": "src/providers/vidu/index.ts",
    "providers/vidu/unified": "src/providers/vidu/unified.ts",
    "providers/xai/index": "src/providers/xai/index.ts",
    "providers/zhipuai/index": "src/providers/zhipuai/index.ts",
  },
  format: "esm",
  // Keep the output free of Node-specific resolution so it runs on
  // Cloudflare Workers and Bun as well as Node. The CLI's lazy
  // `import("node:fs/promises")` is legitimately Node-only (bin entry) —
  // mark node: builtins external so the build stays warning-free.
  platform: "neutral",
  deps: { neverBundle: [/^node:/] },
  dts: true,
  clean: true,
});
