import { defineConfig } from "tsdown";

export default defineConfig({
  entry: {
    index: "src/index.ts",
    cli: "src/cli.ts",
    "ai-sdk/index": "src/ai-sdk/index.ts",
    "catalog/index": "src/catalog/index.ts",
    "chat/index": "src/chat/index.ts",
    "providers/alibaba/index": "src/providers/alibaba/index.ts",
    "providers/amazon-bedrock/index": "src/providers/amazon-bedrock/index.ts",
    "providers/anthropic/index": "src/providers/anthropic/index.ts",
    "providers/assemblyai/index": "src/providers/assemblyai/index.ts",
    "providers/azure/index": "src/providers/azure/index.ts",
    "providers/baseten/index": "src/providers/baseten/index.ts",
    "providers/black-forest-labs/index": "src/providers/black-forest-labs/index.ts",
    "providers/bria/index": "src/providers/bria/index.ts",
    "providers/bytedance/index": "src/providers/bytedance/index.ts",
    "providers/cartesia/index": "src/providers/cartesia/index.ts",
    "providers/cerebras/index": "src/providers/cerebras/index.ts",
    "providers/cloudflare-workers-ai/index": "src/providers/cloudflare-workers-ai/index.ts",
    "providers/cohere/index": "src/providers/cohere/index.ts",
    "providers/deepgram/index": "src/providers/deepgram/index.ts",
    "providers/deepinfra/index": "src/providers/deepinfra/index.ts",
    "providers/deepseek/index": "src/providers/deepseek/index.ts",
    "providers/elevenlabs/index": "src/providers/elevenlabs/index.ts",
    "providers/fireworks-ai/index": "src/providers/fireworks-ai/index.ts",
    "providers/fish-audio/index": "src/providers/fish-audio/index.ts",
    "providers/friendli/index": "src/providers/friendli/index.ts",
    "providers/gladia/index": "src/providers/gladia/index.ts",
    "providers/google/index": "src/providers/google/index.ts",
    "providers/google-vertex/index": "src/providers/google-vertex/index.ts",
    "providers/groq/index": "src/providers/groq/index.ts",
    "providers/huggingface/index": "src/providers/huggingface/index.ts",
    "providers/hume/index": "src/providers/hume/index.ts",
    "providers/ideogram/index": "src/providers/ideogram/index.ts",
    "providers/inception/index": "src/providers/inception/index.ts",
    "providers/inworld/index": "src/providers/inworld/index.ts",
    "providers/kling/index": "src/providers/kling/index.ts",
    "providers/krea/index": "src/providers/krea/index.ts",
    "providers/leonardo/index": "src/providers/leonardo/index.ts",
    "providers/lightricks/index": "src/providers/lightricks/index.ts",
    "providers/lmnt/index": "src/providers/lmnt/index.ts",
    "providers/longcat/index": "src/providers/longcat/index.ts",
    "providers/luma/index": "src/providers/luma/index.ts",
    "providers/meta/index": "src/providers/meta/index.ts",
    "providers/minimax/index": "src/providers/minimax/index.ts",
    "providers/mistral/index": "src/providers/mistral/index.ts",
    "providers/moonshotai/index": "src/providers/moonshotai/index.ts",
    "providers/murf/index": "src/providers/murf/index.ts",
    "providers/nebius/index": "src/providers/nebius/index.ts",
    "providers/novita-ai/index": "src/providers/novita-ai/index.ts",
    "providers/nvidia/index": "src/providers/nvidia/index.ts",
    "providers/openai/index": "src/providers/openai/index.ts",
    "providers/openai-compatible/index": "src/providers/openai-compatible/index.ts",
    "providers/openrouter/index": "src/providers/openrouter/index.ts",
    "providers/perplexity/index": "src/providers/perplexity/index.ts",
    "providers/pixverse/index": "src/providers/pixverse/index.ts",
    "providers/recraft/index": "src/providers/recraft/index.ts",
    "providers/resemble/index": "src/providers/resemble/index.ts",
    "providers/revai/index": "src/providers/revai/index.ts",
    "providers/reve/index": "src/providers/reve/index.ts",
    "providers/rime/index": "src/providers/rime/index.ts",
    "providers/runway/index": "src/providers/runway/index.ts",
    "providers/sarvam/index": "src/providers/sarvam/index.ts",
    "providers/scaleway/index": "src/providers/scaleway/index.ts",
    "providers/siliconflow/index": "src/providers/siliconflow/index.ts",
    "providers/smallest-ai/index": "src/providers/smallest-ai/index.ts",
    "providers/soniox/index": "src/providers/soniox/index.ts",
    "providers/speechify/index": "src/providers/speechify/index.ts",
    "providers/speechmatics/index": "src/providers/speechmatics/index.ts",
    "providers/stability/index": "src/providers/stability/index.ts",
    "providers/stepfun/index": "src/providers/stepfun/index.ts",
    "providers/togetherai/index": "src/providers/togetherai/index.ts",
    "providers/upstage/index": "src/providers/upstage/index.ts",
    "providers/vercel/index": "src/providers/vercel/index.ts",
    "providers/vidu/index": "src/providers/vidu/index.ts",
    "providers/xai/index": "src/providers/xai/index.ts",
    "providers/zhipuai/index": "src/providers/zhipuai/index.ts",
  },
  format: "esm",
  // Keep the output free of Node-specific resolution so it runs on
  // Cloudflare Workers and Bun as well as Node. The CLI's lazy
  // `import("node:fs/promises")` is legitimately Node-only (bin entry) —
  // mark node: builtins external so the build stays warning-free.
  platform: "neutral",
  deps: { neverBundle: [/^node:/] },
  dts: true,
  clean: true,
});
