// Generated by scripts/codegen.ts — DO NOT EDIT.
// Derived from data/models-dev.json (https://models.dev/api.json) by the conjunction
// heuristic in scripts/availability.ts, filtered by data/availability-overrides.json.
// Regenerate with `bun run codegen` (or `bun run codegen:refresh` to update the snapshot).

import type { AvailabilityMap } from "../../core/translate/availability-types";

/**
 * Which providers serve baseten's chat models, and what each one calls
 * them. Source model id → target provider id → the target's own id.
 *
 * baseten itself is always among the targets: a provider serves its own
 * models by definition, so the identity retarget `.toApi("baseten")` is
 * valid (and lossless) for every row here, including rows nobody else serves.
 *
 * A bare string means the target's default endpoint; the object form carries
 * a non-default `endpoint` and/or `narrows` metadata (a smaller context
 * window, or input modalities the target does not accept) so `.toApi` can
 * warn without loading the target provider's catalog.
 */
export const availability = {
  "MiniMaxAI/MiniMax-M2.5": {
    "amazon-bedrock": { id: "minimax.minimax-m2.5", narrows: { context: 196608 } },
    "baseten": "MiniMaxAI/MiniMax-M2.5",
    "deepinfra": { id: "MiniMaxAI/MiniMax-M2.5", narrows: { context: 196608 } },
    "friendli": { id: "MiniMaxAI/MiniMax-M2.5", narrows: { context: 196608 } },
    "huggingface": "MiniMaxAI/MiniMax-M2.5",
    "minimax": "MiniMax-M2.5",
    "nebius": { id: "MiniMaxAI/MiniMax-M2.5", narrows: { context: 196608 } },
    "novita-ai": "minimax/minimax-m2.5",
    "openrouter": "minimax/minimax-m2.5",
    "togetherai": "MiniMaxAI/MiniMax-M2.5",
    "vercel": "minimax/minimax-m2.5",
  },
  "deepseek-ai/DeepSeek-V3.1": {
    "baseten": "deepseek-ai/DeepSeek-V3.1",
    "deepinfra": { id: "deepseek-ai/DeepSeek-V3.1", narrows: { context: 163840 } },
    "google-vertex": { id: "deepseek-ai/deepseek-v3.1-maas", endpoint: "google-vertex.chatMaas", narrows: { context: 163840 } },
    "huggingface": { id: "deepseek-ai/DeepSeek-V3.1", narrows: { context: 131072 } },
    "novita-ai": { id: "deepseek/deepseek-v3.1", narrows: { context: 131072 } },
    "togetherai": { id: "deepseek-ai/DeepSeek-V3-1", narrows: { context: 131072 } },
    "vercel": { id: "deepseek/deepseek-v3.1", narrows: { context: 163840 } },
  },
  "deepseek-ai/DeepSeek-V4-Flash-0731": {
    "alibaba": { id: "deepseek-v4-flash-0731", narrows: { context: 1000000 } },
    "baseten": "deepseek-ai/DeepSeek-V4-Flash-0731",
    "deepinfra": "deepseek-ai/DeepSeek-V4-Flash-0731",
    "fireworks-ai": { id: "accounts/fireworks/models/deepseek-v4-flash-0731", narrows: { context: 1000000 } },
    "huggingface": "deepseek-ai/DeepSeek-V4-Flash-0731",
    "openrouter": "deepseek/deepseek-v4-flash-0731",
    "togetherai": { id: "deepseek-ai/DeepSeek-V4-Flash-0731", narrows: { context: 1000000 } },
    "vercel": { id: "deepseek/deepseek-v4-flash-0731", narrows: { context: 1000000 } },
  },
  "deepseek-ai/DeepSeek-V4-Pro": {
    "azure": "deepseek-v4-pro",
    "baseten": "deepseek-ai/DeepSeek-V4-Pro",
    "deepinfra": "deepseek-ai/DeepSeek-V4-Pro",
    "deepseek": "deepseek-v4-pro",
    "fireworks-ai": "accounts/fireworks/models/deepseek-v4-pro",
    "huggingface": "deepseek-ai/DeepSeek-V4-Pro",
    "nebius": "deepseek-ai/DeepSeek-V4-Pro",
    "novita-ai": "deepseek/deepseek-v4-pro",
    "nvidia": "deepseek-ai/deepseek-v4-pro",
    "openrouter": "deepseek/deepseek-v4-pro",
    "siliconflow": "deepseek-ai/DeepSeek-V4-Pro",
    "togetherai": "deepseek-ai/DeepSeek-V4-Pro",
    "vercel": "deepseek/deepseek-v4-pro",
  },
  "moonshotai/Kimi-K2.5": {
    "azure": "kimi-k2.5",
    "baseten": "moonshotai/Kimi-K2.5",
    "deepinfra": "moonshotai/Kimi-K2.5",
    "huggingface": "moonshotai/Kimi-K2.5",
    "moonshotai": "kimi-k2.5",
    "nebius": { id: "moonshotai/Kimi-K2.5", narrows: { context: 256000 } },
    "novita-ai": "moonshotai/kimi-k2.5",
    "openrouter": "moonshotai/kimi-k2.5",
    "togetherai": "moonshotai/Kimi-K2.5",
    "vercel": "moonshotai/kimi-k2.5",
  },
  "moonshotai/Kimi-K2.6": {
    "azure": "kimi-k2.6",
    "baseten": "moonshotai/Kimi-K2.6",
    "cloudflare-workers-ai": "@cf/moonshotai/kimi-k2.6",
    "deepinfra": "moonshotai/Kimi-K2.6",
    "huggingface": "moonshotai/Kimi-K2.6",
    "moonshotai": "kimi-k2.6",
    "novita-ai": "moonshotai/kimi-k2.6",
    "nvidia": "moonshotai/kimi-k2.6",
    "openrouter": "moonshotai/kimi-k2.6",
    "togetherai": "moonshotai/Kimi-K2.6",
    "vercel": "moonshotai/kimi-k2.6",
  },
  "moonshotai/Kimi-K2.7-Code": {
    "azure": "kimi-k2.7-code",
    "baseten": "moonshotai/Kimi-K2.7-Code",
    "cloudflare-workers-ai": "@cf/moonshotai/kimi-k2.7-code",
    "deepinfra": "moonshotai/Kimi-K2.7-Code",
    "huggingface": "moonshotai/Kimi-K2.7-Code",
    "moonshotai": "kimi-k2.7-code",
    "nebius": { id: "moonshotai/Kimi-K2.7-Code", narrows: { drops: ["image"] } },
    "novita-ai": "moonshotai/kimi-k2.7-code",
    "openrouter": "moonshotai/kimi-k2.7-code",
    "togetherai": { id: "moonshotai/Kimi-K2.7-Code", narrows: { drops: ["image"] } },
    "vercel": { id: "moonshotai/kimi-k2.7-code", narrows: { context: 256000 } },
  },
  "moonshotai/Kimi-K3": {
    "baseten": "moonshotai/Kimi-K3",
    "deepinfra": "moonshotai/Kimi-K3",
    "fireworks-ai": "accounts/fireworks/models/kimi-k3",
    "huggingface": { id: "moonshotai/Kimi-K3", narrows: { context: 1000000 } },
    "moonshotai": "kimi-k3",
    "nebius": { id: "moonshotai/Kimi-K3", narrows: { drops: ["image"] } },
    "novita-ai": "moonshotai/kimi-k3",
    "openrouter": "moonshotai/kimi-k3",
    "togetherai": "moonshotai/Kimi-K3",
    "vercel": { id: "moonshotai/kimi-k3", narrows: { context: 1000000 } },
  },
  "nvidia/NVIDIA-Nemotron-3-Ultra-550B-A55B": {
    "baseten": "nvidia/NVIDIA-Nemotron-3-Ultra-550B-A55B",
  },
  "nvidia/Nemotron-120B-A12B": {
    "baseten": "nvidia/Nemotron-120B-A12B",
  },
  "openai/gpt-oss-120b": {
    "baseten": "openai/gpt-oss-120b",
  },
  "thinkingmachines/inkling": {
    "baseten": "thinkingmachines/inkling",
    "deepinfra": { id: "thinkingmachines/Inkling", narrows: { context: 524288 } },
    "huggingface": "thinkingmachines/Inkling",
    "nvidia": "thinkingmachines/inkling",
    "openrouter": "thinkingmachines/inkling",
    "togetherai": { id: "thinkingmachines/Inkling", narrows: { context: 524288 } },
    "vercel": { id: "thinkingmachines/inkling", narrows: { context: 256000 } },
  },
  "thinkingmachines/inkling-small": {
    "baseten": "thinkingmachines/inkling-small",
    "deepinfra": { id: "thinkingmachines/Inkling-Small", narrows: { context: 524288 } },
    "huggingface": { id: "thinkingmachines/Inkling-Small", narrows: { context: 524288 } },
    "openrouter": { id: "thinkingmachines/inkling-small", narrows: { context: 524288 } },
    "vercel": { id: "thinkingmachines/inkling-small", narrows: { context: 1000000 } },
  },
  "zai-org/GLM-4.7": {
    "amazon-bedrock": "zai.glm-4.7",
    "baseten": "zai-org/GLM-4.7",
    "deepinfra": "zai-org/GLM-4.7",
    "google-vertex": { id: "zai-org/glm-4.7-maas", endpoint: "google-vertex.chatMaas" },
    "huggingface": "zai-org/GLM-4.7",
    "novita-ai": "zai-org/glm-4.7",
    "openrouter": "z-ai/glm-4.7",
    "vercel": "zai/glm-4.7",
    "zhipuai": "glm-4.7",
  },
  "zai-org/GLM-5": {
    "amazon-bedrock": { id: "zai.glm-5", narrows: { context: 202752 } },
    "baseten": "zai-org/GLM-5",
    "deepinfra": { id: "zai-org/GLM-5", narrows: { context: 202752 } },
    "google-vertex": { id: "zai-org/glm-5-maas", endpoint: "google-vertex.chatMaas", narrows: { context: 202752 } },
    "huggingface": { id: "zai-org/GLM-5", narrows: { context: 202752 } },
    "nebius": { id: "zai-org/GLM-5", narrows: { context: 200000 } },
    "novita-ai": "zai-org/glm-5",
    "openrouter": "z-ai/glm-5",
    "togetherai": { id: "zai-org/GLM-5", narrows: { context: 202752 } },
    "vercel": "zai/glm-5",
    "zhipuai": "glm-5",
  },
  "zai-org/GLM-5.1": {
    "baseten": "zai-org/GLM-5.1",
    "deepinfra": { id: "zai-org/GLM-5.1", narrows: { context: 202752 } },
    "friendli": { id: "zai-org/GLM-5.1", narrows: { context: 202752 } },
    "huggingface": { id: "zai-org/GLM-5.1", narrows: { context: 202752 } },
    "novita-ai": "zai-org/glm-5.1",
    "openrouter": "z-ai/glm-5.1",
    "togetherai": { id: "zai-org/GLM-5.1", narrows: { context: 202752 } },
    "vercel": "zai/glm-5.1",
    "zhipuai": { id: "glm-5.1", narrows: { context: 200000 } },
  },
  "zai-org/GLM-5.2": {
    "alibaba": { id: "glm-5.2", narrows: { context: 1000000 } },
    "baseten": "zai-org/GLM-5.2",
    "cloudflare-workers-ai": { id: "@cf/zai-org/glm-5.2", narrows: { context: 262144 } },
    "deepinfra": "zai-org/GLM-5.2",
    "friendli": { id: "zai-org/GLM-5.2", narrows: { context: 1000000 } },
    "huggingface": { id: "zai-org/GLM-5.2", narrows: { context: 262144 } },
    "nebius": { id: "zai-org/GLM-5.2", narrows: { context: 432000 } },
    "novita-ai": "zai-org/glm-5.2",
    "nvidia": { id: "z-ai/glm-5.2", narrows: { context: 1000000 } },
    "openrouter": "z-ai/glm-5.2",
    "scaleway": { id: "glm-5.2", narrows: { context: 256000 } },
    "siliconflow": "zai-org/GLM-5.2",
    "togetherai": { id: "zai-org/GLM-5.2", narrows: { context: 512000 } },
    "vercel": { id: "zai/glm-5.2", narrows: { context: 1000000 } },
    "zhipuai": { id: "glm-5.2", narrows: { context: 1000000 } },
  },
  "zai-org/GLM-5.2-Fast": {
    "baseten": "zai-org/GLM-5.2-Fast",
    "vercel": { id: "zai/glm-5.2-fast", narrows: { context: 1000000 } },
  },
} as const satisfies AvailabilityMap;

export type BasetenAvailability = typeof availability;
