// Generated by scripts/codegen.ts — DO NOT EDIT.
// Derived from data/models-dev.json (https://models.dev/api.json) by the conjunction
// heuristic in scripts/availability.ts, filtered by data/availability-overrides.json.
// Regenerate with `bun run codegen` (or `bun run codegen:refresh` to update the snapshot).

import type { AvailabilityMap } from "../../core/translate/availability-types";

/**
 * Which other providers serve cerebras's chat models, and what each one
 * calls them. Source model id → target provider id → the target's own id.
 *
 * A bare string means the target's default endpoint; the object form carries
 * a non-default `endpoint` and/or `narrows` metadata (a smaller context
 * window, or input modalities the target does not accept) so `.toApi` can
 * warn without loading the target provider's catalog.
 */
export const availability = {
  "gpt-oss-120b": {
    "amazon-bedrock": { id: "openai.gpt-oss-120b", narrows: { context: 128000 } },
    "cloudflare-workers-ai": { id: "@cf/openai/gpt-oss-120b", narrows: { context: 128000 } },
    "deepinfra": "openai/gpt-oss-120b",
    "fireworks-ai": "accounts/fireworks/models/gpt-oss-120b",
    "google-vertex": { id: "openai/gpt-oss-120b-maas", endpoint: "google-vertex.chat" },
    "groq": "openai/gpt-oss-120b",
    "huggingface": "openai/gpt-oss-120b",
    "nebius": { id: "openai/gpt-oss-120b", narrows: { context: 128000 } },
    "nvidia": { id: "openai/gpt-oss-120b", narrows: { context: 128000 } },
    "openrouter": "openai/gpt-oss-120b",
    "scaleway": { id: "gpt-oss-120b", narrows: { context: 128000 } },
    "togetherai": "openai/gpt-oss-120b",
    "vercel": "openai/gpt-oss-120b",
  },
} as const satisfies AvailabilityMap;

export type CerebrasAvailability = typeof availability;
