// Generated by scripts/codegen.ts — DO NOT EDIT.
// Derived from data/models-dev.json (https://models.dev/api.json) by the conjunction
// heuristic in scripts/availability.ts, filtered by data/availability-overrides.json.
// Regenerate with `bun run codegen` (or `bun run codegen:refresh` to update the snapshot).

import type { AvailabilityMap } from "../../core/translate/availability-types";

/**
 * Which other providers serve cloudflare-workers-ai's chat models, and what each one
 * calls them. Source model id → target provider id → the target's own id.
 *
 * A bare string means the target's default endpoint; the object form carries
 * a non-default `endpoint` and/or `narrows` metadata (a smaller context
 * window, or input modalities the target does not accept) so `.toApi` can
 * warn without loading the target provider's catalog.
 */
export const availability = {
  "@cf/deepseek-ai/deepseek-r1-distill-qwen-32b": {
    "novita-ai": { id: "deepseek/deepseek-r1-distill-qwen-32b", narrows: { context: 64000 } },
  },
  "@cf/google/gemma-4-26b-a4b-it": {
    "deepinfra": "google/gemma-4-26B-A4B-it",
    "google": "gemma-4-26b-a4b-it",
    "huggingface": "google/gemma-4-26B-A4B-it",
    "openrouter": "google/gemma-4-26b-a4b-it",
    "scaleway": "gemma-4-26b-a4b-it",
    "siliconflow": { id: "google/gemma-4-26B-A4B-it", narrows: { drops: ["image"] } },
    "vercel": "google/gemma-4-26b-a4b-it",
  },
  "@cf/meta/llama-3.2-11b-vision-instruct": {
    "nvidia": "meta/llama-3.2-11b-vision-instruct",
  },
  "@cf/meta/llama-3.2-1b-instruct": {
    "nvidia": "meta/llama-3.2-1b-instruct",
    "openrouter": "meta-llama/llama-3.2-1b-instruct",
  },
  "@cf/meta/llama-3.2-3b-instruct": {
    "novita-ai": { id: "meta-llama/llama-3.2-3b-instruct", narrows: { context: 32768 } },
    "nvidia": { id: "meta/llama-3.2-3b-instruct", narrows: { context: 32768 } },
    "openrouter": "meta-llama/llama-3.2-3b-instruct",
  },
  "@cf/meta/llama-4-scout-17b-16e-instruct": {
    "azure": { id: "llama-4-scout-17b-16e-instruct", narrows: { context: 128000 } },
  },
  "@cf/moonshotai/kimi-k2.6": {
    "azure": "kimi-k2.6",
    "baseten": { id: "moonshotai/Kimi-K2.6", narrows: { context: 262000 } },
    "deepinfra": "moonshotai/Kimi-K2.6",
    "huggingface": "moonshotai/Kimi-K2.6",
    "moonshotai": "kimi-k2.6",
    "novita-ai": "moonshotai/kimi-k2.6",
    "nvidia": "moonshotai/kimi-k2.6",
    "openrouter": "moonshotai/kimi-k2.6",
    "togetherai": "moonshotai/Kimi-K2.6",
    "vercel": { id: "moonshotai/kimi-k2.6", narrows: { context: 262000 } },
  },
  "@cf/moonshotai/kimi-k2.7-code": {
    "azure": "kimi-k2.7-code",
    "baseten": { id: "moonshotai/Kimi-K2.7-Code", narrows: { context: 262000 } },
    "deepinfra": "moonshotai/Kimi-K2.7-Code",
    "huggingface": "moonshotai/Kimi-K2.7-Code",
    "moonshotai": "kimi-k2.7-code",
    "nebius": { id: "moonshotai/Kimi-K2.7-Code", narrows: { drops: ["image"] } },
    "novita-ai": "moonshotai/kimi-k2.7-code",
    "openrouter": "moonshotai/kimi-k2.7-code",
    "togetherai": { id: "moonshotai/Kimi-K2.7-Code", narrows: { drops: ["image"] } },
    "vercel": { id: "moonshotai/kimi-k2.7-code", narrows: { context: 256000 } },
  },
  "@cf/openai/gpt-oss-120b": {
    "amazon-bedrock": "openai.gpt-oss-120b",
    "cerebras": "gpt-oss-120b",
    "deepinfra": "openai/gpt-oss-120b",
    "fireworks-ai": "accounts/fireworks/models/gpt-oss-120b",
    "google-vertex": { id: "openai/gpt-oss-120b-maas", endpoint: "google-vertex.chat" },
    "groq": "openai/gpt-oss-120b",
    "huggingface": "openai/gpt-oss-120b",
    "nebius": "openai/gpt-oss-120b",
    "nvidia": "openai/gpt-oss-120b",
    "openrouter": "openai/gpt-oss-120b",
    "scaleway": "gpt-oss-120b",
    "togetherai": "openai/gpt-oss-120b",
    "vercel": "openai/gpt-oss-120b",
  },
  "@cf/openai/gpt-oss-20b": {
    "amazon-bedrock": "openai.gpt-oss-20b",
    "deepinfra": "openai/gpt-oss-20b",
    "fireworks-ai": "accounts/fireworks/models/gpt-oss-20b",
    "google-vertex": { id: "openai/gpt-oss-20b-maas", endpoint: "google-vertex.chat" },
    "groq": "openai/gpt-oss-20b",
    "huggingface": "openai/gpt-oss-20b",
    "novita-ai": "openai/gpt-oss-20b",
    "nvidia": "openai/gpt-oss-20b",
    "openrouter": "openai/gpt-oss-20b",
    "togetherai": "openai/gpt-oss-20b",
    "vercel": "openai/gpt-oss-20b",
  },
  "@cf/qwen/qwen2.5-coder-32b-instruct": {
    "nvidia": "qwen/qwen2.5-coder-32b-instruct",
  },
  "@cf/zai-org/glm-4.7-flash": {
    "amazon-bedrock": "zai.glm-4.7-flash",
    "deepinfra": "zai-org/GLM-4.7-Flash",
    "huggingface": "zai-org/GLM-4.7-Flash",
    "novita-ai": "zai-org/glm-4.7-flash",
    "openrouter": "z-ai/glm-4.7-flash",
    "vercel": "zai/glm-4.7-flash",
    "zhipuai": "glm-4.7-flash",
  },
  "@cf/zai-org/glm-5.2": {
    "alibaba": "glm-5.2",
    "baseten": "zai-org/GLM-5.2",
    "deepinfra": "zai-org/GLM-5.2",
    "friendli": "zai-org/GLM-5.2",
    "huggingface": "zai-org/GLM-5.2",
    "nebius": "zai-org/GLM-5.2",
    "novita-ai": "zai-org/glm-5.2",
    "nvidia": "z-ai/glm-5.2",
    "openrouter": "z-ai/glm-5.2",
    "scaleway": { id: "glm-5.2", narrows: { context: 256000 } },
    "siliconflow": "zai-org/GLM-5.2",
    "togetherai": "zai-org/GLM-5.2",
    "vercel": "zai/glm-5.2",
    "zhipuai": "glm-5.2",
  },
} as const satisfies AvailabilityMap;

export type CloudflareWorkersAiAvailability = typeof availability;
