// Generated by scripts/codegen.ts — DO NOT EDIT.
// Derived from data/models-dev.json (https://models.dev/api.json) by the conjunction
// heuristic in scripts/availability.ts, filtered by data/availability-overrides.json.
// Regenerate with `bun run codegen` (or `bun run codegen:refresh` to update the snapshot).

import type { AvailabilityMap } from "../../core/translate/availability-types";

/**
 * Which providers serve deepseek's chat models, and what each one calls
 * them. Source model id → target provider id → the target's own id.
 *
 * deepseek itself is always among the targets: a provider serves its own
 * models by definition, so the identity retarget `.toApi("deepseek")` is
 * valid (and lossless) for every row here, including rows nobody else serves.
 *
 * A bare string means the target's default endpoint; the object form carries
 * a non-default `endpoint` and/or `narrows` metadata (a smaller context
 * window, or input modalities the target does not accept) so `.toApi` can
 * warn without loading the target provider's catalog.
 */
export const availability = {
  "deepseek-v4-flash": {
    "azure": "deepseek-v4-flash",
    "deepinfra": "deepseek-ai/DeepSeek-V4-Flash",
    "deepseek": "deepseek-v4-flash",
    "huggingface": "deepseek-ai/DeepSeek-V4-Flash",
    "nebius": { id: "deepseek-ai/DeepSeek-V4-Flash", narrows: { context: 131072 } },
    "novita-ai": "deepseek/deepseek-v4-flash",
    "nvidia": "deepseek-ai/deepseek-v4-flash",
    "openrouter": "deepseek/deepseek-v4-flash",
    "siliconflow": "deepseek-ai/DeepSeek-V4-Flash",
    "vercel": "deepseek/deepseek-v4-flash",
  },
  "deepseek-v4-flash-vision-exp": {
    "deepseek": "deepseek-v4-flash-vision-exp",
    "openrouter": "deepseek/deepseek-v4-flash-vision-exp",
    "vercel": "deepseek/deepseek-v4-flash-vision-exp",
  },
  "deepseek-v4-pro": {
    "azure": "deepseek-v4-pro",
    "baseten": "deepseek-ai/DeepSeek-V4-Pro",
    "deepinfra": "deepseek-ai/DeepSeek-V4-Pro",
    "deepseek": "deepseek-v4-pro",
    "huggingface": "deepseek-ai/DeepSeek-V4-Pro",
    "nebius": "deepseek-ai/DeepSeek-V4-Pro",
    "novita-ai": "deepseek/deepseek-v4-pro",
    "nvidia": "deepseek-ai/deepseek-v4-pro",
    "openrouter": "deepseek/deepseek-v4-pro",
    "siliconflow": "deepseek-ai/DeepSeek-V4-Pro",
    "togetherai": { id: "deepseek-ai/DeepSeek-V4-Pro", narrows: { context: 512000 } },
    "vercel": "deepseek/deepseek-v4-pro",
  },
} as const satisfies AvailabilityMap;

export type DeepseekAvailability = typeof availability;
