// Generated by scripts/codegen.ts — DO NOT EDIT.
// Derived from data/models-dev.json (https://models.dev/api.json) by the conjunction
// heuristic in scripts/availability.ts, filtered by data/availability-overrides.json.
// Regenerate with `bun run codegen` (or `bun run codegen:refresh` to update the snapshot).

import type { AvailabilityMap } from "../../core/translate/availability-types";

/**
 * Which providers serve fireworks-ai's chat models, and what each one calls
 * them. Source model id → target provider id → the target's own id.
 *
 * fireworks-ai itself is always among the targets: a provider serves its own
 * models by definition, so the identity retarget `.toApi("fireworks-ai")` is
 * valid (and lossless) for every row here, including rows nobody else serves.
 *
 * A bare string means the target's default endpoint; the object form carries
 * a non-default `endpoint` and/or `narrows` metadata (a smaller context
 * window, or input modalities the target does not accept) so `.toApi` can
 * warn without loading the target provider's catalog.
 */
export const availability = {
  "accounts/fireworks/models/deepseek-v4p1-flash": {
    "fireworks-ai": "accounts/fireworks/models/deepseek-v4p1-flash",
  },
  "accounts/fireworks/models/ember-1": {
    "fireworks-ai": "accounts/fireworks/models/ember-1",
    "openrouter": "fireworks/ember-1",
    "vercel": "fireworks/ember-1",
  },
  "accounts/fireworks/models/glm-5p3": {
    "fireworks-ai": "accounts/fireworks/models/glm-5p3",
  },
  "accounts/fireworks/models/glm-5p3-flash": {
    "fireworks-ai": "accounts/fireworks/models/glm-5p3-flash",
  },
  "accounts/fireworks/models/gpt-oss-120b": {
    "amazon-bedrock": "openai.gpt-oss-120b",
    "cerebras": "gpt-oss-120b",
    "cloudflare-workers-ai": { id: "@cf/openai/gpt-oss-120b", narrows: { context: 128000 } },
    "deepinfra": "openai/gpt-oss-120b",
    "fireworks-ai": "accounts/fireworks/models/gpt-oss-120b",
    "google-vertex": { id: "openai/gpt-oss-120b-maas", endpoint: "google-vertex.chatMaas" },
    "groq": "openai/gpt-oss-120b",
    "huggingface": "openai/gpt-oss-120b",
    "nebius": "openai/gpt-oss-120b",
    "openrouter": "openai/gpt-oss-120b",
    "scaleway": { id: "gpt-oss-120b", narrows: { context: 128000 } },
    "togetherai": "openai/gpt-oss-120b",
    "vercel": "openai/gpt-oss-120b",
  },
  "accounts/fireworks/models/inkling": {
    "baseten": "thinkingmachines/inkling",
    "deepinfra": { id: "thinkingmachines/Inkling", narrows: { context: 524288 } },
    "fireworks-ai": "accounts/fireworks/models/inkling",
    "huggingface": "thinkingmachines/Inkling",
    "nvidia": "thinkingmachines/inkling",
    "openrouter": { id: "thinkingmachines/inkling", narrows: { context: 524288 } },
    "togetherai": { id: "thinkingmachines/Inkling", narrows: { context: 524288 } },
    "vercel": { id: "thinkingmachines/inkling", narrows: { context: 256000 } },
  },
  "accounts/fireworks/models/kimi-k3": {
    "alibaba": "kimi-k3",
    "baseten": "moonshotai/Kimi-K3",
    "deepinfra": "moonshotai/Kimi-K3",
    "fireworks-ai": "accounts/fireworks/models/kimi-k3",
    "huggingface": { id: "moonshotai/Kimi-K3", narrows: { context: 1000000 } },
    "moonshotai": "kimi-k3",
    "nebius": { id: "moonshotai/Kimi-K3", narrows: { drops: ["image"] } },
    "novita-ai": "moonshotai/kimi-k3",
    "nvidia": "moonshotai/kimi-k3",
    "openrouter": "moonshotai/kimi-k3",
    "siliconflow": "moonshotai/Kimi-K3",
    "togetherai": "moonshotai/Kimi-K3",
    "vercel": { id: "moonshotai/kimi-k3", narrows: { context: 1000000 } },
  },
  "accounts/fireworks/models/minimax-m3": {
    "deepinfra": "MiniMaxAI/MiniMax-M3",
    "fireworks-ai": "accounts/fireworks/models/minimax-m3",
    "huggingface": "MiniMaxAI/MiniMax-M3",
    "minimax": "MiniMax-M3",
    "nebius": "MiniMaxAI/MiniMax-M3",
    "nvidia": "minimaxai/minimax-m3",
    "openrouter": "minimax/minimax-m3",
    "siliconflow": "MiniMaxAI/MiniMax-M3",
    "togetherai": "MiniMaxAI/MiniMax-M3",
    "vercel": "minimax/minimax-m3",
  },
  "accounts/fireworks/models/nemotron-3-ultra-nvfp4": {
    "fireworks-ai": "accounts/fireworks/models/nemotron-3-ultra-nvfp4",
  },
  "accounts/fireworks/models/nemotron-lightning-3p5-30b-a3b": {
    "fireworks-ai": "accounts/fireworks/models/nemotron-lightning-3p5-30b-a3b",
  },
  "accounts/fireworks/models/qwen3p8-2p4t-a95b": {
    "fireworks-ai": "accounts/fireworks/models/qwen3p8-2p4t-a95b",
  },
  "accounts/fireworks/models/qwen3p8-max": {
    "fireworks-ai": "accounts/fireworks/models/qwen3p8-max",
  },
  "accounts/fireworks/routers/deepseek-flash-latest": {
    "fireworks-ai": "accounts/fireworks/routers/deepseek-flash-latest",
    "openrouter": "~deepseek/deepseek-flash-latest",
  },
  "accounts/fireworks/routers/glm-5p3-fast": {
    "fireworks-ai": "accounts/fireworks/routers/glm-5p3-fast",
  },
  "accounts/fireworks/routers/glm-fast-latest": {
    "fireworks-ai": "accounts/fireworks/routers/glm-fast-latest",
  },
  "accounts/fireworks/routers/glm-flash-latest": {
    "fireworks-ai": "accounts/fireworks/routers/glm-flash-latest",
    "openrouter": "~z-ai/glm-flash-latest",
  },
  "accounts/fireworks/routers/glm-latest": {
    "fireworks-ai": "accounts/fireworks/routers/glm-latest",
    "openrouter": "~z-ai/glm-latest",
  },
  "accounts/fireworks/routers/kimi-fast-latest": {
    "fireworks-ai": "accounts/fireworks/routers/kimi-fast-latest",
  },
  "accounts/fireworks/routers/kimi-k3-fast": {
    "fireworks-ai": "accounts/fireworks/routers/kimi-k3-fast",
    "vercel": { id: "moonshotai/kimi-k3-fast", narrows: { context: 1000000 } },
  },
  "accounts/fireworks/routers/kimi-latest": {
    "fireworks-ai": "accounts/fireworks/routers/kimi-latest",
    "openrouter": "~moonshotai/kimi-latest",
  },
  "accounts/fireworks/routers/minimax-latest": {
    "fireworks-ai": "accounts/fireworks/routers/minimax-latest",
  },
  "accounts/fireworks/routers/qwen-max-latest": {
    "fireworks-ai": "accounts/fireworks/routers/qwen-max-latest",
  },
} as const satisfies AvailabilityMap;

export type FireworksAiAvailability = typeof availability;
