// Generated by scripts/codegen.ts — DO NOT EDIT.
// Derived from data/models-dev.json (https://models.dev/api.json) by the conjunction
// heuristic in scripts/availability.ts, filtered by data/availability-overrides.json.
// Regenerate with `bun run codegen` (or `bun run codegen:refresh` to update the snapshot).

import type { AvailabilityMap } from "../../core/translate/availability-types";

/**
 * Which providers serve fireworks-ai's chat models, and what each one calls
 * them. Source model id → target provider id → the target's own id.
 *
 * fireworks-ai itself is always among the targets: a provider serves its own
 * models by definition, so the identity retarget `.toApi("fireworks-ai")` is
 * valid (and lossless) for every row here, including rows nobody else serves.
 *
 * A bare string means the target's default endpoint; the object form carries
 * a non-default `endpoint` and/or `narrows` metadata (a smaller context
 * window, or input modalities the target does not accept) so `.toApi` can
 * warn without loading the target provider's catalog.
 */
export const availability = {
  "accounts/fireworks/models/deepseek-v4-flash-0731": {
    "alibaba": "deepseek-v4-flash-0731",
    "baseten": "deepseek-ai/DeepSeek-V4-Flash-0731",
    "cloudflare-workers-ai": "@cf/deepseek-ai/deepseek-v4-flash-0731",
    "deepinfra": "deepseek-ai/DeepSeek-V4-Flash-0731",
    "fireworks-ai": "accounts/fireworks/models/deepseek-v4-flash-0731",
    "huggingface": "deepseek-ai/DeepSeek-V4-Flash-0731",
    "nvidia": "deepseek-ai/deepseek-v4-flash-0731",
    "openrouter": "deepseek/deepseek-v4-flash-0731",
    "scaleway": { id: "deepseek-v4-flash-0731", narrows: { context: 256000 } },
    "togetherai": "deepseek-ai/DeepSeek-V4-Flash-0731",
    "vercel": "deepseek/deepseek-v4-flash-0731",
  },
  "accounts/fireworks/models/deepseek-v4-pro-0813": {
    "baseten": "deepseek-ai/DeepSeek-V4-Pro-0813",
    "cloudflare-workers-ai": "@cf/deepseek-ai/deepseek-v4-pro-0813",
    "deepinfra": "deepseek-ai/DeepSeek-V4-Pro-0813",
    "fireworks-ai": "accounts/fireworks/models/deepseek-v4-pro-0813",
    "huggingface": "deepseek-ai/DeepSeek-V4-Pro-0813",
    "nvidia": "deepseek-ai/deepseek-v4-pro-0813",
    "openrouter": "deepseek/deepseek-v4-pro-0813",
    "togetherai": "deepseek-ai/DeepSeek-V4-Pro-0813",
    "vercel": "deepseek/deepseek-v4-pro-0813",
  },
  "accounts/fireworks/models/glm-5p2": {
    "fireworks-ai": "accounts/fireworks/models/glm-5p2",
  },
  "accounts/fireworks/models/glm-5p3": {
    "fireworks-ai": "accounts/fireworks/models/glm-5p3",
  },
  "accounts/fireworks/models/glm-5p3-flash": {
    "fireworks-ai": "accounts/fireworks/models/glm-5p3-flash",
  },
  "accounts/fireworks/models/gpt-oss-120b": {
    "amazon-bedrock": { id: "openai.gpt-oss-120b", narrows: { context: 128000 } },
    "cerebras": "gpt-oss-120b",
    "cloudflare-workers-ai": { id: "@cf/openai/gpt-oss-120b", narrows: { context: 128000 } },
    "deepinfra": "openai/gpt-oss-120b",
    "fireworks-ai": "accounts/fireworks/models/gpt-oss-120b",
    "google-vertex": { id: "openai/gpt-oss-120b-maas", endpoint: "google-vertex.chatMaas" },
    "groq": "openai/gpt-oss-120b",
    "huggingface": "openai/gpt-oss-120b",
    "nebius": { id: "openai/gpt-oss-120b", narrows: { context: 128000 } },
    "nvidia": { id: "openai/gpt-oss-120b", narrows: { context: 128000 } },
    "openrouter": "openai/gpt-oss-120b",
    "scaleway": { id: "gpt-oss-120b", narrows: { context: 128000 } },
    "togetherai": "openai/gpt-oss-120b",
    "vercel": "openai/gpt-oss-120b",
  },
  "accounts/fireworks/models/inkling": {
    "baseten": { id: "thinkingmachines/inkling", narrows: { drops: ["audio"] } },
    "deepinfra": { id: "thinkingmachines/Inkling", narrows: { context: 524288 } },
    "fireworks-ai": "accounts/fireworks/models/inkling",
    "huggingface": { id: "thinkingmachines/Inkling", narrows: { drops: ["audio"] } },
    "nvidia": "thinkingmachines/inkling",
    "openrouter": "thinkingmachines/inkling",
    "togetherai": { id: "thinkingmachines/Inkling", narrows: { context: 524288 } },
    "vercel": { id: "thinkingmachines/inkling", narrows: { context: 256000, drops: ["audio"] } },
  },
  "accounts/fireworks/models/kimi-k2p6": {
    "fireworks-ai": "accounts/fireworks/models/kimi-k2p6",
  },
  "accounts/fireworks/models/kimi-k2p7-code": {
    "fireworks-ai": "accounts/fireworks/models/kimi-k2p7-code",
  },
  "accounts/fireworks/models/kimi-k3": {
    "baseten": "moonshotai/Kimi-K3",
    "deepinfra": "moonshotai/Kimi-K3",
    "fireworks-ai": "accounts/fireworks/models/kimi-k3",
    "huggingface": { id: "moonshotai/Kimi-K3", narrows: { context: 1000000 } },
    "moonshotai": "kimi-k3",
    "nebius": { id: "moonshotai/Kimi-K3", narrows: { drops: ["image"] } },
    "novita-ai": "moonshotai/kimi-k3",
    "nvidia": "moonshotai/kimi-k3",
    "openrouter": "moonshotai/kimi-k3",
    "togetherai": "moonshotai/Kimi-K3",
    "vercel": { id: "moonshotai/kimi-k3", narrows: { context: 1000000 } },
  },
  "accounts/fireworks/models/minimax-m3": {
    "deepinfra": "MiniMaxAI/MiniMax-M3",
    "fireworks-ai": "accounts/fireworks/models/minimax-m3",
    "huggingface": { id: "MiniMaxAI/MiniMax-M3", narrows: { drops: ["video"] } },
    "minimax": "MiniMax-M3",
    "nebius": { id: "MiniMaxAI/MiniMax-M3", narrows: { drops: ["image", "video"] } },
    "nvidia": "minimaxai/minimax-m3",
    "openrouter": "minimax/minimax-m3",
    "togetherai": { id: "MiniMaxAI/MiniMax-M3", narrows: { drops: ["video"] } },
    "vercel": { id: "minimax/minimax-m3", narrows: { drops: ["video"] } },
  },
  "accounts/fireworks/models/muse-glimmer-30b": {
    "fireworks-ai": "accounts/fireworks/models/muse-glimmer-30b",
    "nvidia": "meta/muse-glimmer-30b",
    "openrouter": "meta/muse-glimmer-30b",
    "vercel": "meta/muse-glimmer-30b",
  },
  "accounts/fireworks/models/nemotron-3-ultra-nvfp4": {
    "fireworks-ai": "accounts/fireworks/models/nemotron-3-ultra-nvfp4",
  },
  "accounts/fireworks/models/nemotron-lightning-3p5-30b-a3b": {
    "fireworks-ai": "accounts/fireworks/models/nemotron-lightning-3p5-30b-a3b",
  },
  "accounts/fireworks/models/qwen3p7-plus": {
    "fireworks-ai": "accounts/fireworks/models/qwen3p7-plus",
  },
  "accounts/fireworks/models/qwen3p8-max": {
    "fireworks-ai": "accounts/fireworks/models/qwen3p8-max",
  },
  "accounts/fireworks/routers/glm-5p2-fast": {
    "fireworks-ai": "accounts/fireworks/routers/glm-5p2-fast",
  },
  "accounts/fireworks/routers/kimi-k3-fast": {
    "fireworks-ai": "accounts/fireworks/routers/kimi-k3-fast",
    "vercel": { id: "moonshotai/kimi-k3-fast", narrows: { context: 1000000 } },
  },
} as const satisfies AvailabilityMap;

export type FireworksAiAvailability = typeof availability;
