// Generated by scripts/codegen.ts — DO NOT EDIT.
// Derived from data/models-dev.json (https://models.dev/api.json) by the conjunction
// heuristic in scripts/availability.ts, filtered by data/availability-overrides.json.
// Regenerate with `bun run codegen` (or `bun run codegen:refresh` to update the snapshot).

import type { AvailabilityMap } from "../../core/translate/availability-types";

/**
 * Which other providers serve friendli's chat models, and what each one
 * calls them. Source model id → target provider id → the target's own id.
 *
 * A bare string means the target's default endpoint; the object form carries
 * a non-default `endpoint` and/or `narrows` metadata (a smaller context
 * window, or input modalities the target does not accept) so `.toApi` can
 * warn without loading the target provider's catalog.
 */
export const availability = {
  "MiniMaxAI/MiniMax-M2.5": {
    "amazon-bedrock": "minimax.minimax-m2.5",
    "baseten": "MiniMaxAI/MiniMax-M2.5",
    "deepinfra": "MiniMaxAI/MiniMax-M2.5",
    "huggingface": "MiniMaxAI/MiniMax-M2.5",
    "minimax": "MiniMax-M2.5",
    "nebius": "MiniMaxAI/MiniMax-M2.5",
    "novita-ai": "minimax/minimax-m2.5",
    "openrouter": "minimax/minimax-m2.5",
    "togetherai": "MiniMaxAI/MiniMax-M2.5",
    "vercel": "minimax/minimax-m2.5",
  },
  "deepseek-ai/DeepSeek-V3.2": {
    "azure": { id: "deepseek-v3.2", narrows: { context: 128000 } },
    "deepinfra": "deepseek-ai/DeepSeek-V3.2",
    "google-vertex": { id: "deepseek-ai/deepseek-v3.2-maas", endpoint: "google-vertex.chat" },
    "huggingface": "deepseek-ai/DeepSeek-V3.2",
    "nebius": { id: "deepseek-ai/DeepSeek-V3.2", narrows: { context: 163000 } },
    "novita-ai": "deepseek/deepseek-v3.2",
    "openrouter": "deepseek/deepseek-v3.2",
    "vercel": { id: "deepseek/deepseek-v3.2", narrows: { context: 128000 } },
  },
  "google/gemma-4-31B-it": {
    "deepinfra": "google/gemma-4-31B-it",
    "google": "gemma-4-31b-it",
    "huggingface": "google/gemma-4-31B-it",
    "nvidia": { id: "google/gemma-4-31b-it", narrows: { context: 256000 } },
    "openrouter": "google/gemma-4-31b-it",
    "siliconflow": { id: "google/gemma-4-31B-it", narrows: { drops: ["image"] } },
    "vercel": { id: "google/gemma-4-31b-it", narrows: { context: 256000 } },
  },
  "zai-org/GLM-5.1": {
    "baseten": "zai-org/GLM-5.1",
    "deepinfra": "zai-org/GLM-5.1",
    "huggingface": "zai-org/GLM-5.1",
    "novita-ai": "zai-org/glm-5.1",
    "openrouter": "z-ai/glm-5.1",
    "togetherai": "zai-org/GLM-5.1",
    "vercel": "zai/glm-5.1",
    "zhipuai": { id: "glm-5.1", narrows: { context: 200000 } },
  },
  "zai-org/GLM-5.2": {
    "alibaba": "glm-5.2",
    "baseten": "zai-org/GLM-5.2",
    "cloudflare-workers-ai": { id: "@cf/zai-org/glm-5.2", narrows: { context: 262144 } },
    "deepinfra": "zai-org/GLM-5.2",
    "huggingface": { id: "zai-org/GLM-5.2", narrows: { context: 262144 } },
    "nebius": { id: "zai-org/GLM-5.2", narrows: { context: 432000 } },
    "novita-ai": "zai-org/glm-5.2",
    "nvidia": "z-ai/glm-5.2",
    "openrouter": "z-ai/glm-5.2",
    "scaleway": { id: "glm-5.2", narrows: { context: 256000 } },
    "siliconflow": "zai-org/GLM-5.2",
    "togetherai": { id: "zai-org/GLM-5.2", narrows: { context: 512000 } },
    "vercel": "zai/glm-5.2",
    "zhipuai": "glm-5.2",
  },
} as const satisfies AvailabilityMap;

export type FriendliAvailability = typeof availability;
