// Generated by scripts/codegen.ts — DO NOT EDIT.
// Derived from data/models-dev.json (https://models.dev/api.json) by the conjunction
// heuristic in scripts/availability.ts, filtered by data/availability-overrides.json.
// Regenerate with `bun run codegen` (or `bun run codegen:refresh` to update the snapshot).

import type { AvailabilityMap } from "../../core/translate/availability-types";

/**
 * Which providers serve google-vertex's chat models, and what each one calls
 * them. Source model id → target provider id → the target's own id.
 *
 * google-vertex itself is always among the targets: a provider serves its own
 * models by definition, so the identity retarget `.toApi("google-vertex")` is
 * valid (and lossless) for every row here, including rows nobody else serves.
 *
 * A bare string means the target's default endpoint; the object form carries
 * a non-default `endpoint` and/or `narrows` metadata (a smaller context
 * window, or input modalities the target does not accept) so `.toApi` can
 * warn without loading the target provider's catalog.
 */
export const availability = {
  "codestral-2": {
    "google-vertex": "codestral-2",
  },
  "deepseek-ai/deepseek-v3.1-maas": {
    "baseten": "deepseek-ai/DeepSeek-V3.1",
    "deepinfra": "deepseek-ai/DeepSeek-V3.1",
    "google-vertex": { id: "deepseek-ai/deepseek-v3.1-maas", endpoint: "google-vertex.chatMaas" },
    "huggingface": { id: "deepseek-ai/DeepSeek-V3.1", narrows: { context: 131072 } },
    "togetherai": { id: "deepseek-ai/DeepSeek-V3-1", narrows: { context: 131072 } },
    "vercel": "deepseek/deepseek-v3.1",
  },
  "deepseek-ai/deepseek-v3.2-maas": {
    "azure": { id: "deepseek-v3.2", narrows: { context: 128000 } },
    "deepinfra": "deepseek-ai/DeepSeek-V3.2",
    "friendli": "deepseek-ai/DeepSeek-V3.2",
    "google-vertex": { id: "deepseek-ai/deepseek-v3.2-maas", endpoint: "google-vertex.chatMaas" },
    "huggingface": "deepseek-ai/DeepSeek-V3.2",
    "openrouter": "deepseek/deepseek-v3.2",
    "vercel": { id: "deepseek/deepseek-v3.2", narrows: { context: 128000 } },
  },
  "gemini-2.5-flash": {
    "google": "gemini-2.5-flash",
    "google-vertex": "gemini-2.5-flash",
    "openrouter": "google/gemini-2.5-flash",
    "vercel": "google/gemini-2.5-flash",
  },
  "gemini-2.5-flash-image": {
    "google": { id: "gemini-2.5-flash-image", narrows: { drops: ["pdf"] } },
    "google-vertex": "gemini-2.5-flash-image",
    "openrouter": { id: "google/gemini-2.5-flash-image", narrows: { drops: ["pdf"] } },
    "vercel": { id: "google/gemini-2.5-flash-image", narrows: { drops: ["pdf"] } },
  },
  "gemini-2.5-flash-lite": {
    "google": "gemini-2.5-flash-lite",
    "google-vertex": "gemini-2.5-flash-lite",
    "openrouter": "google/gemini-2.5-flash-lite",
    "vercel": { id: "google/gemini-2.5-flash-lite", narrows: { drops: ["audio", "video"] } },
  },
  "gemini-2.5-pro": {
    "google": "gemini-2.5-pro",
    "google-vertex": "gemini-2.5-pro",
    "openrouter": "google/gemini-2.5-pro",
    "vercel": "google/gemini-2.5-pro",
  },
  "gemini-3-flash-preview": {
    "google": "gemini-3-flash-preview",
    "google-vertex": "gemini-3-flash-preview",
    "openrouter": "google/gemini-3-flash-preview",
  },
  "gemini-3-pro-image": {
    "google": { id: "gemini-3-pro-image", narrows: { drops: ["pdf"] } },
    "google-vertex": "gemini-3-pro-image",
    "openrouter": { id: "google/gemini-3-pro-image", narrows: { drops: ["pdf"] } },
    "vercel": { id: "google/gemini-3-pro-image", narrows: { drops: ["pdf"] } },
  },
  "gemini-3.1-flash-image": {
    "google": "gemini-3.1-flash-image",
    "google-vertex": "gemini-3.1-flash-image",
    "openrouter": { id: "google/gemini-3.1-flash-image", narrows: { drops: ["video", "pdf"] } },
    "vercel": { id: "google/gemini-3.1-flash-image", narrows: { drops: ["video", "pdf"] } },
  },
  "gemini-3.1-flash-lite": {
    "google": "gemini-3.1-flash-lite",
    "google-vertex": "gemini-3.1-flash-lite",
    "openrouter": "google/gemini-3.1-flash-lite",
    "vercel": { id: "google/gemini-3.1-flash-lite", narrows: { context: 1000000, drops: ["video", "audio"] } },
  },
  "gemini-3.1-flash-lite-image": {
    "google": "gemini-3.1-flash-lite-image",
    "google-vertex": "gemini-3.1-flash-lite-image",
    "openrouter": "google/gemini-3.1-flash-lite-image",
  },
  "gemini-3.1-pro-preview": {
    "google": "gemini-3.1-pro-preview",
    "google-vertex": "gemini-3.1-pro-preview",
    "openrouter": "google/gemini-3.1-pro-preview",
    "vercel": { id: "google/gemini-3.1-pro-preview", narrows: { context: 1000000, drops: ["video", "audio"] } },
  },
  "gemini-3.1-pro-preview-customtools": {
    "google": "gemini-3.1-pro-preview-customtools",
    "google-vertex": "gemini-3.1-pro-preview-customtools",
    "openrouter": "google/gemini-3.1-pro-preview-customtools",
  },
  "gemini-3.5-flash": {
    "google": "gemini-3.5-flash",
    "google-vertex": "gemini-3.5-flash",
    "openrouter": "google/gemini-3.5-flash",
    "vercel": { id: "google/gemini-3.5-flash", narrows: { context: 1000000, drops: ["video", "audio"] } },
  },
  "gemini-3.5-flash-lite": {
    "google": "gemini-3.5-flash-lite",
    "google-vertex": "gemini-3.5-flash-lite",
    "openrouter": "google/gemini-3.5-flash-lite",
    "vercel": { id: "google/gemini-3.5-flash-lite", narrows: { context: 1000000, drops: ["video", "audio"] } },
  },
  "gemini-3.6-flash": {
    "google": "gemini-3.6-flash",
    "google-vertex": "gemini-3.6-flash",
    "openrouter": "google/gemini-3.6-flash",
    "vercel": { id: "google/gemini-3.6-flash", narrows: { context: 1000000, drops: ["video", "audio"] } },
  },
  "gemini-3.7-flash": {
    "google": "gemini-3.7-flash",
    "google-vertex": "gemini-3.7-flash",
    "openrouter": "google/gemini-3.7-flash",
    "vercel": { id: "google/gemini-3.7-flash", narrows: { context: 1000000, drops: ["video", "audio"] } },
  },
  "gemini-3.8-flash": {
    "google": "gemini-3.8-flash",
    "google-vertex": "gemini-3.8-flash",
    "openrouter": "google/gemini-3.8-flash",
    "vercel": { id: "google/gemini-3.8-flash", narrows: { context: 1000000, drops: ["video", "audio"] } },
  },
  "gemini-nano-banana-2.1": {
    "google-vertex": "gemini-nano-banana-2.1",
    "openrouter": { id: "google/gemini-nano-banana-2.1", narrows: { context: 65536, drops: ["video"] } },
  },
  "google/gemma-4-26b-a4b-it-maas": {
    "cloudflare-workers-ai": { id: "@cf/google/gemma-4-26b-a4b-it", narrows: { context: 256000 } },
    "deepinfra": "google/gemma-4-26B-A4B-it",
    "google": "gemma-4-26b-a4b-it",
    "google-vertex": { id: "google/gemma-4-26b-a4b-it-maas", endpoint: "google-vertex.chatMaas" },
    "huggingface": "google/gemma-4-26B-A4B-it",
    "novita-ai": "google/gemma-4-26b-a4b-it",
    "openrouter": "google/gemma-4-26b-a4b-it",
    "scaleway": { id: "gemma-4-26b-a4b-it", narrows: { context: 256000 } },
    "siliconflow": { id: "google/gemma-4-26B-A4B-it", narrows: { drops: ["image"] } },
    "vercel": "google/gemma-4-26b-a4b-it",
  },
  "meta/llama-3.3-70b-instruct-maas": {
    "azure": "llama-3.3-70b-instruct",
    "google-vertex": { id: "meta/llama-3.3-70b-instruct-maas", endpoint: "google-vertex.chatMaas" },
    "huggingface": "meta-llama/Llama-3.3-70B-Instruct",
    "novita-ai": { id: "meta-llama/llama-3.3-70b-instruct", narrows: { context: 12288 } },
    "nvidia": "meta/llama-3.3-70b-instruct",
    "openrouter": "meta-llama/llama-3.3-70b-instruct",
    "scaleway": { id: "llama-3.3-70b-instruct", narrows: { context: 100000 } },
  },
  "meta/llama-4-maverick-17b-128e-instruct-maas": {
    "google-vertex": { id: "meta/llama-4-maverick-17b-128e-instruct-maas", endpoint: "google-vertex.chatMaas" },
    "nvidia": { id: "meta/llama-4-maverick-17b-128e-instruct", narrows: { context: 128000 } },
  },
  "meta/llama-4-scout-17b-16e-instruct-maas": {
    "google-vertex": { id: "meta/llama-4-scout-17b-16e-instruct-maas", endpoint: "google-vertex.chatMaas" },
    "novita-ai": { id: "meta-llama/llama-4-scout-17b-16e-instruct", narrows: { context: 131072 } },
  },
  "mistral-medium-3": {
    "google-vertex": "mistral-medium-3",
    "openrouter": "mistralai/mistral-medium-3",
  },
  "mistral-small-2503": {
    "google-vertex": "mistral-small-2503",
  },
  "moonshotai/kimi-k2-thinking-maas": {
    "amazon-bedrock": "moonshot.kimi-k2-thinking",
    "google-vertex": { id: "moonshotai/kimi-k2-thinking-maas", endpoint: "google-vertex.chatMaas" },
    "huggingface": "moonshotai/Kimi-K2-Thinking",
    "novita-ai": "moonshotai/kimi-k2-thinking",
    "openrouter": "moonshotai/kimi-k2-thinking",
  },
  "openai/gpt-oss-120b-maas": {
    "amazon-bedrock": "openai.gpt-oss-120b",
    "cerebras": "gpt-oss-120b",
    "cloudflare-workers-ai": { id: "@cf/openai/gpt-oss-120b", narrows: { context: 128000 } },
    "deepinfra": "openai/gpt-oss-120b",
    "fireworks-ai": "accounts/fireworks/models/gpt-oss-120b",
    "google-vertex": { id: "openai/gpt-oss-120b-maas", endpoint: "google-vertex.chatMaas" },
    "groq": "openai/gpt-oss-120b",
    "huggingface": "openai/gpt-oss-120b",
    "nebius": "openai/gpt-oss-120b",
    "novita-ai": "openai/gpt-oss-120b",
    "openrouter": "openai/gpt-oss-120b",
    "scaleway": { id: "gpt-oss-120b", narrows: { context: 128000 } },
    "togetherai": "openai/gpt-oss-120b",
    "vercel": "openai/gpt-oss-120b",
  },
  "openai/gpt-oss-20b-maas": {
    "amazon-bedrock": "openai.gpt-oss-20b",
    "cloudflare-workers-ai": { id: "@cf/openai/gpt-oss-20b", narrows: { context: 128000 } },
    "deepinfra": "openai/gpt-oss-20b",
    "google-vertex": { id: "openai/gpt-oss-20b-maas", endpoint: "google-vertex.chatMaas" },
    "groq": "openai/gpt-oss-20b",
    "huggingface": "openai/gpt-oss-20b",
    "nvidia": "openai/gpt-oss-20b",
    "openrouter": "openai/gpt-oss-20b",
    "vercel": "openai/gpt-oss-20b",
  },
  "qwen/qwen3-235b-a22b-instruct-2507-maas": {
    "google-vertex": { id: "qwen/qwen3-235b-a22b-instruct-2507-maas", endpoint: "google-vertex.chatMaas" },
  },
  "xai/grok-4.1-fast-non-reasoning": {
    "azure": "grok-4-1-fast-non-reasoning",
    "google-vertex": "xai/grok-4.1-fast-non-reasoning",
  },
  "xai/grok-4.1-fast-reasoning": {
    "azure": "grok-4-1-fast-reasoning",
    "google-vertex": "xai/grok-4.1-fast-reasoning",
  },
  "xai/grok-4.20-non-reasoning": {
    "azure": { id: "grok-4-20-non-reasoning", narrows: { context: 262000, drops: ["image"] } },
    "google-vertex": "xai/grok-4.20-non-reasoning",
  },
  "xai/grok-4.20-reasoning": {
    "azure": { id: "grok-4-20-reasoning", narrows: { context: 262000, drops: ["image"] } },
    "google-vertex": "xai/grok-4.20-reasoning",
  },
  "xai/grok-4.3": {
    "amazon-bedrock": "xai.grok-4.3",
    "google-vertex": "xai/grok-4.3",
    "openrouter": "x-ai/grok-4.3",
    "vercel": "spacexai/grok-4.3",
    "xai": "grok-4.3",
  },
  "xai/grok-4.6": {
    "amazon-bedrock": { id: "xai.grok-4.6", narrows: { context: 500000 } },
    "azure": { id: "grok-4.6", narrows: { context: 200000 } },
    "google-vertex": "xai/grok-4.6",
    "openrouter": { id: "x-ai/grok-4.6", narrows: { context: 500000 } },
    "vercel": { id: "spacexai/grok-4.6", narrows: { context: 500000 } },
    "xai": { id: "grok-4.6", narrows: { context: 500000 } },
  },
  "xai/grok-4.7": {
    "amazon-bedrock": { id: "us.xai.grok-4.7", narrows: { context: 500000 } },
    "azure": { id: "grok-4.7", narrows: { context: 500000 } },
    "google-vertex": "xai/grok-4.7",
    "openrouter": { id: "x-ai/grok-4.7", narrows: { context: 500000 } },
    "vercel": { id: "spacexai/grok-4.7", narrows: { context: 500000 } },
    "xai": { id: "grok-4.7", narrows: { context: 500000 } },
  },
  "zai-org/glm-4.7-maas": {
    "amazon-bedrock": "zai.glm-4.7",
    "baseten": "zai-org/GLM-4.7",
    "deepinfra": "zai-org/GLM-4.7",
    "google-vertex": { id: "zai-org/glm-4.7-maas", endpoint: "google-vertex.chatMaas" },
    "huggingface": "zai-org/GLM-4.7",
    "novita-ai": "zai-org/glm-4.7",
    "openrouter": "z-ai/glm-4.7",
    "vercel": "zai/glm-4.7",
    "zhipuai": "glm-4.7",
  },
  "zai-org/glm-5-maas": {
    "amazon-bedrock": "zai.glm-5",
    "baseten": "zai-org/GLM-5",
    "deepinfra": "zai-org/GLM-5",
    "google-vertex": { id: "zai-org/glm-5-maas", endpoint: "google-vertex.chatMaas" },
    "huggingface": "zai-org/GLM-5",
    "novita-ai": "zai-org/glm-5",
    "openrouter": "z-ai/glm-5",
    "togetherai": "zai-org/GLM-5",
    "vercel": "zai/glm-5",
    "zhipuai": "glm-5",
  },
  "zai-org/glm-5.2-maas": {
    "alibaba": "glm-5.2",
    "baseten": "zai-org/GLM-5.2",
    "cloudflare-workers-ai": { id: "@cf/zai-org/glm-5.2", narrows: { context: 262144 } },
    "deepinfra": "zai-org/GLM-5.2",
    "friendli": "zai-org/GLM-5.2",
    "google-vertex": { id: "zai-org/glm-5.2-maas", endpoint: "google-vertex.chatMaas" },
    "huggingface": { id: "zai-org/GLM-5.2", narrows: { context: 262144 } },
    "mistral": "glm-5-2",
    "nebius": "zai-org/GLM-5.2",
    "novita-ai": "zai-org/glm-5.2",
    "nvidia": "z-ai/glm-5.2",
    "openrouter": "z-ai/glm-5.2",
    "scaleway": { id: "glm-5.2", narrows: { context: 256000 } },
    "siliconflow": "zai-org/GLM-5.2",
    "togetherai": "zai-org/GLM-5.2",
    "vercel": "zai/glm-5.2",
    "zhipuai": "glm-5.2",
  },
} as const satisfies AvailabilityMap;

export type GoogleVertexAvailability = typeof availability;
