// Generated by scripts/codegen.ts — DO NOT EDIT.
// Derived from data/models-dev.json (https://models.dev/api.json) by the conjunction
// heuristic in scripts/availability.ts, filtered by data/availability-overrides.json.
// Regenerate with `bun run codegen` (or `bun run codegen:refresh` to update the snapshot).

import type { AvailabilityMap } from "../../core/translate/availability-types";

/**
 * Which providers serve mistral's chat models, and what each one calls
 * them. Source model id → target provider id → the target's own id.
 *
 * mistral itself is always among the targets: a provider serves its own
 * models by definition, so the identity retarget `.toApi("mistral")` is
 * valid (and lossless) for every row here, including rows nobody else serves.
 *
 * A bare string means the target's default endpoint; the object form carries
 * a non-default `endpoint` and/or `narrows` metadata (a smaller context
 * window, or input modalities the target does not accept) so `.toApi` can
 * warn without loading the target provider's catalog.
 */
export const availability = {
  "codestral-2508": {
    "mistral": "codestral-2508",
    "openrouter": "mistralai/codestral-2508",
  },
  "codestral-latest": {
    "mistral": "codestral-latest",
  },
  "devstral-2512": {
    "mistral": "devstral-2512",
    "openrouter": "mistralai/devstral-2512",
  },
  "devstral-latest": {
    "mistral": "devstral-latest",
  },
  "devstral-medium-2507": {
    "mistral": "devstral-medium-2507",
  },
  "devstral-medium-latest": {
    "mistral": "devstral-medium-latest",
  },
  "devstral-small-2505": {
    "mistral": "devstral-small-2505",
  },
  "devstral-small-2507": {
    "mistral": "devstral-small-2507",
  },
  "glm-5-2": {
    "alibaba": { id: "glm-5.2", narrows: { context: 1000000 } },
    "baseten": "zai-org/GLM-5.2",
    "cloudflare-workers-ai": { id: "@cf/zai-org/glm-5.2", narrows: { context: 262144 } },
    "deepinfra": "zai-org/GLM-5.2",
    "friendli": "zai-org/GLM-5.2",
    "google-vertex": { id: "zai-org/glm-5.2-maas", endpoint: "google-vertex.chatMaas", narrows: { context: 1000000 } },
    "huggingface": { id: "zai-org/GLM-5.2", narrows: { context: 262144 } },
    "mistral": "glm-5-2",
    "nebius": "zai-org/GLM-5.2",
    "novita-ai": "zai-org/glm-5.2",
    "nvidia": { id: "z-ai/glm-5.2", narrows: { context: 1000000 } },
    "openrouter": "z-ai/glm-5.2",
    "scaleway": { id: "glm-5.2", narrows: { context: 256000 } },
    "siliconflow": "zai-org/GLM-5.2",
    "togetherai": { id: "zai-org/GLM-5.2", narrows: { context: 1048575 } },
    "vercel": { id: "zai/glm-5.2", narrows: { context: 1000000 } },
    "zhipuai": { id: "glm-5.2", narrows: { context: 1000000 } },
  },
  "labs-devstral-small-2512": {
    "mistral": "labs-devstral-small-2512",
  },
  "labs-leanstral-1-5-1": {
    "mistral": "labs-leanstral-1-5-1",
  },
  "magistral-medium-latest": {
    "mistral": "magistral-medium-latest",
  },
  "ministral-14b-2512": {
    "mistral": "ministral-14b-2512",
  },
  "ministral-3b-2512": {
    "mistral": "ministral-3b-2512",
  },
  "ministral-3b-latest": {
    "mistral": "ministral-3b-latest",
  },
  "ministral-8b-2512": {
    "mistral": "ministral-8b-2512",
  },
  "ministral-8b-latest": {
    "mistral": "ministral-8b-latest",
  },
  "mistral-large-2411": {
    "mistral": "mistral-large-2411",
  },
  "mistral-large-2512": {
    "mistral": "mistral-large-2512",
    "openrouter": "mistralai/mistral-large-2512",
  },
  "mistral-large-4": {
    "mistral": "mistral-large-4",
    "vercel": { id: "mistral/mistral-large-4", narrows: { context: 524288 } },
  },
  "mistral-large-latest": {
    "mistral": "mistral-large-latest",
  },
  "mistral-medium-2505": {
    "azure": { id: "mistral-medium-2505", narrows: { context: 128000 } },
    "mistral": "mistral-medium-2505",
  },
  "mistral-medium-2508": {
    "mistral": "mistral-medium-2508",
  },
  "mistral-medium-2604": {
    "mistral": "mistral-medium-2604",
  },
  "mistral-medium-latest": {
    "mistral": "mistral-medium-latest",
  },
  "mistral-nemo": {
    "mistral": "mistral-nemo",
    "openrouter": "mistralai/mistral-nemo",
    "vercel": "mistral/mistral-nemo",
  },
  "mistral-small-2506": {
    "mistral": "mistral-small-2506",
  },
  "mistral-small-2603": {
    "mistral": "mistral-small-2603",
    "openrouter": "mistralai/mistral-small-2603",
  },
  "mistral-small-latest": {
    "mistral": "mistral-small-latest",
  },
  "open-mistral-7b": {
    "mistral": "open-mistral-7b",
  },
  "open-mistral-nemo": {
    "mistral": "open-mistral-nemo",
  },
  "open-mixtral-8x22b": {
    "mistral": "open-mixtral-8x22b",
  },
  "open-mixtral-8x7b": {
    "mistral": "open-mixtral-8x7b",
  },
  "pixtral-12b": {
    "mistral": "pixtral-12b",
  },
  "pixtral-large-latest": {
    "mistral": "pixtral-large-latest",
  },
  "voxtral-mini-latest": {
    "mistral": "voxtral-mini-latest",
  },
  "voxtral-small-2507": {
    "mistral": "voxtral-small-2507",
  },
  "voxtral-small-latest": {
    "mistral": "voxtral-small-latest",
  },
  "zai-glm-5-2": {
    "mistral": "zai-glm-5-2",
  },
  "zai-glm-5-3": {
    "mistral": "zai-glm-5-3",
  },
} as const satisfies AvailabilityMap;

export type MistralAvailability = typeof availability;
