// Generated by scripts/codegen.ts — DO NOT EDIT.
// Derived from data/models-dev.json (https://models.dev/api.json) by the conjunction
// heuristic in scripts/availability.ts, filtered by data/availability-overrides.json.
// Regenerate with `bun run codegen` (or `bun run codegen:refresh` to update the snapshot).

import type { AvailabilityMap } from "../../core/translate/availability-types";

/**
 * Which other providers serve mistral's chat models, and what each one
 * calls them. Source model id → target provider id → the target's own id.
 *
 * A bare string means the target's default endpoint; the object form carries
 * a non-default `endpoint` and/or `narrows` metadata (a smaller context
 * window, or input modalities the target does not accept) so `.toApi` can
 * warn without loading the target provider's catalog.
 */
export const availability = {
  "magistral-small": {
    "vercel": "mistral/magistral-small",
  },
  "mistral-large-2512": {
    "openrouter": "mistralai/mistral-large-2512",
  },
  "mistral-medium-2505": {
    "azure": { id: "mistral-medium-2505", narrows: { context: 128000 } },
  },
  "mistral-nemo": {
    "novita-ai": { id: "mistralai/mistral-nemo", narrows: { context: 60288 } },
    "openrouter": "mistralai/mistral-nemo",
    "vercel": "mistral/mistral-nemo",
  },
  "mistral-small-2603": {
    "openrouter": "mistralai/mistral-small-2603",
  },
  "pixtral-12b": {
    "vercel": "mistral/pixtral-12b",
  },
} as const satisfies AvailabilityMap;

export type MistralAvailability = typeof availability;
