// Generated by scripts/codegen.ts — DO NOT EDIT.
// Derived from data/models-dev.json (https://models.dev/api.json) by the conjunction
// heuristic in scripts/availability.ts, filtered by data/availability-overrides.json.
// Regenerate with `bun run codegen` (or `bun run codegen:refresh` to update the snapshot).

import type { AvailabilityMap } from "../../core/translate/availability-types";

/**
 * Which other providers serve openrouter's chat models, and what each one
 * calls them. Source model id → target provider id → the target's own id.
 *
 * A bare string means the target's default endpoint; the object form carries
 * a non-default `endpoint` and/or `narrows` metadata (a smaller context
 * window, or input modalities the target does not accept) so `.toApi` can
 * warn without loading the target provider's catalog.
 */
export const availability = {
  "anthropic/claude-fable-5": {
    "amazon-bedrock": "anthropic.claude-fable-5",
    "anthropic": "claude-fable-5",
    "vercel": "anthropic/claude-fable-5",
  },
  "anthropic/claude-haiku-4.5": {
    "amazon-bedrock": "anthropic.claude-haiku-4-5-20251001-v1:0",
    "anthropic": "claude-haiku-4-5",
    "vercel": "anthropic/claude-haiku-4.5",
  },
  "anthropic/claude-opus-4": {
    "vercel": "anthropic/claude-opus-4",
  },
  "anthropic/claude-opus-4.5": {
    "amazon-bedrock": "anthropic.claude-opus-4-5-20251101-v1:0",
    "anthropic": "claude-opus-4-5",
    "vercel": "anthropic/claude-opus-4.5",
  },
  "anthropic/claude-opus-4.6": {
    "anthropic": "claude-opus-4-6",
    "vercel": "anthropic/claude-opus-4.6",
  },
  "anthropic/claude-opus-4.7": {
    "amazon-bedrock": "anthropic.claude-opus-4-7",
    "anthropic": "claude-opus-4-7",
    "vercel": "anthropic/claude-opus-4.7",
  },
  "anthropic/claude-opus-4.8": {
    "amazon-bedrock": "anthropic.claude-opus-4-8",
    "anthropic": "claude-opus-4-8",
    "vercel": "anthropic/claude-opus-4.8",
  },
  "anthropic/claude-opus-4.8-fast": {
    "vercel": "anthropic/claude-opus-4.8-fast",
  },
  "anthropic/claude-opus-5": {
    "amazon-bedrock": "anthropic.claude-opus-5",
    "anthropic": "claude-opus-5",
    "vercel": "anthropic/claude-opus-5",
  },
  "anthropic/claude-opus-5-fast": {
    "vercel": "anthropic/claude-opus-5-fast",
  },
  "anthropic/claude-sonnet-4": {
    "vercel": "anthropic/claude-sonnet-4",
  },
  "anthropic/claude-sonnet-4.5": {
    "amazon-bedrock": { id: "anthropic.claude-sonnet-4-5-20250929-v1:0", narrows: { context: 200000 } },
    "anthropic": "claude-sonnet-4-5",
    "vercel": "anthropic/claude-sonnet-4.5",
  },
  "anthropic/claude-sonnet-4.6": {
    "amazon-bedrock": "anthropic.claude-sonnet-4-6",
    "anthropic": "claude-sonnet-4-6",
    "vercel": "anthropic/claude-sonnet-4.6",
  },
  "anthropic/claude-sonnet-5": {
    "amazon-bedrock": "anthropic.claude-sonnet-5",
    "anthropic": "claude-sonnet-5",
    "vercel": "anthropic/claude-sonnet-5",
  },
  "arcee-ai/trinity-large-thinking": {
    "vercel": { id: "arcee-ai/trinity-large-thinking", narrows: { context: 262100 } },
  },
  "baidu/ernie-4.5-vl-424b-a47b": {
    "novita-ai": "baidu/ernie-4.5-vl-424b-a47b",
  },
  "bytedance-seed/seed-1.6": {
    "vercel": { id: "bytedance/seed-1.6", narrows: { context: 256000, drops: ["video"] } },
  },
  "bytedance-seed/seed-2.0-code": {
    "deepinfra": { id: "ByteDance/Seed-2.0-code", narrows: { context: 256000, drops: ["video"] } },
  },
  "cohere/command-a": {
    "vercel": "cohere/command-a",
  },
  "deepcogito/cogito-v2.1-671b": {
    "togetherai": "deepcogito/cogito-v2-1-671b",
  },
  "deepseek/deepseek-chat": {
    "deepseek": "deepseek-chat",
  },
  "deepseek/deepseek-r1": {
    "azure": "deepseek-r1",
    "huggingface": { id: "deepseek-ai/DeepSeek-R1", narrows: { context: 64000 } },
    "togetherai": { id: "deepseek-ai/DeepSeek-R1", narrows: { context: 163839 } },
    "vercel": { id: "deepseek/deepseek-r1", narrows: { context: 128000 } },
  },
  "deepseek/deepseek-v3.1-terminus": {
    "novita-ai": { id: "deepseek/deepseek-v3.1-terminus", narrows: { context: 131072 } },
    "vercel": { id: "deepseek/deepseek-v3.1-terminus", narrows: { context: 131072 } },
  },
  "deepseek/deepseek-v3.2": {
    "azure": { id: "deepseek-v3.2", narrows: { context: 128000 } },
    "deepinfra": "deepseek-ai/DeepSeek-V3.2",
    "friendli": "deepseek-ai/DeepSeek-V3.2",
    "google-vertex": { id: "deepseek-ai/deepseek-v3.2-maas", endpoint: "google-vertex.chat" },
    "huggingface": "deepseek-ai/DeepSeek-V3.2",
    "nebius": { id: "deepseek-ai/DeepSeek-V3.2", narrows: { context: 163000 } },
    "novita-ai": "deepseek/deepseek-v3.2",
    "vercel": { id: "deepseek/deepseek-v3.2", narrows: { context: 128000 } },
  },
  "deepseek/deepseek-v3.2-exp": {
    "novita-ai": "deepseek/deepseek-v3.2-exp",
  },
  "deepseek/deepseek-v4-flash": {
    "azure": { id: "deepseek-v4-flash", narrows: { context: 1000000 } },
    "deepinfra": "deepseek-ai/DeepSeek-V4-Flash",
    "deepseek": { id: "deepseek-v4-flash", narrows: { context: 1000000 } },
    "fireworks-ai": { id: "accounts/fireworks/models/deepseek-v4-flash", narrows: { context: 1000000 } },
    "huggingface": "deepseek-ai/DeepSeek-V4-Flash",
    "nebius": { id: "deepseek-ai/DeepSeek-V4-Flash", narrows: { context: 131072 } },
    "novita-ai": "deepseek/deepseek-v4-flash",
    "nvidia": "deepseek-ai/deepseek-v4-flash",
    "siliconflow": { id: "deepseek-ai/DeepSeek-V4-Flash", narrows: { context: 1000000 } },
    "vercel": { id: "deepseek/deepseek-v4-flash", narrows: { context: 1000000 } },
  },
  "deepseek/deepseek-v4-flash-0731": {
    "alibaba": { id: "deepseek-v4-flash-0731", narrows: { context: 1000000 } },
    "baseten": "deepseek-ai/DeepSeek-V4-Flash-0731",
    "deepinfra": "deepseek-ai/DeepSeek-V4-Flash-0731",
    "fireworks-ai": { id: "accounts/fireworks/models/deepseek-v4-flash-0731", narrows: { context: 1000000 } },
    "huggingface": "deepseek-ai/DeepSeek-V4-Flash-0731",
    "togetherai": { id: "deepseek-ai/DeepSeek-V4-Flash-0731", narrows: { context: 1000000 } },
    "vercel": { id: "deepseek/deepseek-v4-flash-0731", narrows: { context: 1000000 } },
  },
  "deepseek/deepseek-v4-pro": {
    "azure": { id: "deepseek-v4-pro", narrows: { context: 1000000 } },
    "baseten": { id: "deepseek-ai/DeepSeek-V4-Pro", narrows: { context: 262144 } },
    "deepinfra": "deepseek-ai/DeepSeek-V4-Pro",
    "deepseek": { id: "deepseek-v4-pro", narrows: { context: 1000000 } },
    "fireworks-ai": { id: "accounts/fireworks/models/deepseek-v4-pro", narrows: { context: 1000000 } },
    "huggingface": "deepseek-ai/DeepSeek-V4-Pro",
    "nebius": { id: "deepseek-ai/DeepSeek-V4-Pro", narrows: { context: 1000000 } },
    "novita-ai": "deepseek/deepseek-v4-pro",
    "nvidia": "deepseek-ai/deepseek-v4-pro",
    "siliconflow": { id: "deepseek-ai/DeepSeek-V4-Pro", narrows: { context: 1000000 } },
    "togetherai": { id: "deepseek-ai/DeepSeek-V4-Pro", narrows: { context: 512000 } },
    "vercel": "deepseek/deepseek-v4-pro",
  },
  "deepseek/deepseek-v4-pro-0813": {
    "vercel": { id: "deepseek/deepseek-v4-pro-0813", narrows: { context: 1000000 } },
  },
  "google/gemini-2.5-flash": {
    "google": "gemini-2.5-flash",
    "google-vertex": "gemini-2.5-flash",
    "vercel": "google/gemini-2.5-flash",
  },
  "google/gemini-2.5-flash-image": {
    "google": "gemini-2.5-flash-image",
    "google-vertex": "gemini-2.5-flash-image",
    "vercel": "google/gemini-2.5-flash-image",
  },
  "google/gemini-2.5-flash-lite": {
    "google": "gemini-2.5-flash-lite",
    "google-vertex": "gemini-2.5-flash-lite",
    "vercel": { id: "google/gemini-2.5-flash-lite", narrows: { drops: ["audio", "video"] } },
  },
  "google/gemini-2.5-pro": {
    "google": "gemini-2.5-pro",
    "google-vertex": "gemini-2.5-pro",
    "vercel": "google/gemini-2.5-pro",
  },
  "google/gemini-3-flash-preview": {
    "google": "gemini-3-flash-preview",
    "google-vertex": "gemini-3-flash-preview",
  },
  "google/gemini-3-pro-image": {
    "google": "gemini-3-pro-image",
    "google-vertex": { id: "gemini-3-pro-image", narrows: { context: 65536 } },
    "vercel": { id: "google/gemini-3-pro-image", narrows: { context: 65536 } },
  },
  "google/gemini-3-pro-image-preview": {
    "google": "gemini-3-pro-image-preview",
  },
  "google/gemini-3.1-flash-image": {
    "google": { id: "gemini-3.1-flash-image", narrows: { context: 65536 } },
    "google-vertex": "gemini-3.1-flash-image",
    "vercel": "google/gemini-3.1-flash-image",
  },
  "google/gemini-3.1-flash-image-preview": {
    "google": "gemini-3.1-flash-image-preview",
  },
  "google/gemini-3.1-flash-lite": {
    "google": "gemini-3.1-flash-lite",
    "google-vertex": "gemini-3.1-flash-lite",
    "vercel": { id: "google/gemini-3.1-flash-lite", narrows: { context: 1000000, drops: ["video", "audio"] } },
  },
  "google/gemini-3.1-flash-lite-image": {
    "google": "gemini-3.1-flash-lite-image",
  },
  "google/gemini-3.1-flash-lite-preview": {
    "google": "gemini-3.1-flash-lite-preview",
    "google-vertex": "gemini-3.1-flash-lite-preview",
  },
  "google/gemini-3.1-pro-preview": {
    "google": "gemini-3.1-pro-preview",
    "google-vertex": "gemini-3.1-pro-preview",
    "vercel": { id: "google/gemini-3.1-pro-preview", narrows: { context: 1000000, drops: ["video", "audio"] } },
  },
  "google/gemini-3.1-pro-preview-customtools": {
    "google": "gemini-3.1-pro-preview-customtools",
    "google-vertex": "gemini-3.1-pro-preview-customtools",
  },
  "google/gemini-3.5-flash": {
    "google": "gemini-3.5-flash",
    "google-vertex": "gemini-3.5-flash",
    "vercel": { id: "google/gemini-3.5-flash", narrows: { context: 1000000, drops: ["video", "audio"] } },
  },
  "google/gemini-3.5-flash-lite": {
    "google": "gemini-3.5-flash-lite",
    "google-vertex": "gemini-3.5-flash-lite",
    "vercel": { id: "google/gemini-3.5-flash-lite", narrows: { context: 1000000, drops: ["video", "audio"] } },
  },
  "google/gemini-3.6-flash": {
    "google": "gemini-3.6-flash",
    "google-vertex": "gemini-3.6-flash",
    "vercel": { id: "google/gemini-3.6-flash", narrows: { context: 1000000, drops: ["video", "audio"] } },
  },
  "google/gemma-3-12b-it": {
    "novita-ai": "google/gemma-3-12b-it",
  },
  "google/gemma-3-27b-it": {
    "novita-ai": { id: "google/gemma-3-27b-it", narrows: { context: 98304 } },
  },
  "google/gemma-4-26b-a4b-it": {
    "cloudflare-workers-ai": { id: "@cf/google/gemma-4-26b-a4b-it", narrows: { context: 256000, drops: ["video"] } },
    "deepinfra": { id: "google/gemma-4-26B-A4B-it", narrows: { drops: ["video"] } },
    "google": { id: "gemma-4-26b-a4b-it", narrows: { drops: ["video"] } },
    "huggingface": { id: "google/gemma-4-26B-A4B-it", narrows: { drops: ["video"] } },
    "scaleway": { id: "gemma-4-26b-a4b-it", narrows: { context: 256000, drops: ["video"] } },
    "siliconflow": { id: "google/gemma-4-26B-A4B-it", narrows: { drops: ["image", "video"] } },
    "vercel": { id: "google/gemma-4-26b-a4b-it", narrows: { drops: ["video"] } },
  },
  "google/gemma-4-26b-a4b-it:free": {
    "novita-ai": { id: "google/gemma-4-26b-a4b-it", narrows: { drops: ["video"] } },
  },
  "google/gemma-4-31b-it": {
    "deepinfra": "google/gemma-4-31B-it",
    "friendli": { id: "google/gemma-4-31B-it", narrows: { drops: ["video"] } },
    "google": { id: "gemma-4-31b-it", narrows: { drops: ["video"] } },
    "huggingface": { id: "google/gemma-4-31B-it", narrows: { drops: ["video"] } },
    "nvidia": { id: "google/gemma-4-31b-it", narrows: { context: 256000 } },
    "siliconflow": { id: "google/gemma-4-31B-it", narrows: { drops: ["image", "video"] } },
    "vercel": { id: "google/gemma-4-31b-it", narrows: { context: 256000, drops: ["video"] } },
  },
  "google/gemma-4-31b-it:free": {
    "novita-ai": { id: "google/gemma-4-31b-it", narrows: { drops: ["video"] } },
  },
  "inception/mercury-2": {
    "inception": "mercury-2",
    "vercel": "inception/mercury-2",
  },
  "inclusionai/ling-2.6-1t": {
    "novita-ai": "inclusionai/ling-2.6-1t",
  },
  "inclusionai/ling-2.6-flash": {
    "novita-ai": "inclusionai/ling-2.6-flash",
  },
  "inclusionai/ling-3.0-flash": {
    "vercel": { id: "inclusionai/ling-3.0-flash", narrows: { context: 256000 } },
  },
  "inclusionai/ring-2.6-1t": {
    "novita-ai": "inclusionai/ring-2.6-1t",
  },
  "kwaipilot/kat-coder-air-v2.5": {
    "vercel": "kwaipilot/kat-coder-air-v2.5",
  },
  "kwaipilot/kat-coder-pro-v2": {
    "vercel": { id: "kwaipilot/kat-coder-pro-v2", narrows: { context: 256000 } },
  },
  "kwaipilot/kat-coder-pro-v2.5": {
    "vercel": "kwaipilot/kat-coder-pro-v2.5",
  },
  "meituan/longcat-2.0": {
    "longcat": { id: "LongCat-2.0", narrows: { context: 1000000 } },
  },
  "meta-llama/llama-3.1-70b-instruct": {
    "nvidia": { id: "meta/llama-3.1-70b-instruct", narrows: { context: 128000 } },
  },
  "meta-llama/llama-3.1-8b-instruct": {
    "novita-ai": { id: "meta-llama/llama-3.1-8b-instruct", narrows: { context: 16384 } },
    "nvidia": { id: "meta/llama-3.1-8b-instruct", narrows: { context: 16000 } },
  },
  "meta-llama/llama-3.2-1b-instruct": {
    "cloudflare-workers-ai": "@cf/meta/llama-3.2-1b-instruct",
    "nvidia": "meta/llama-3.2-1b-instruct",
  },
  "meta-llama/llama-3.2-3b-instruct": {
    "cloudflare-workers-ai": { id: "@cf/meta/llama-3.2-3b-instruct", narrows: { context: 80000 } },
    "novita-ai": { id: "meta-llama/llama-3.2-3b-instruct", narrows: { context: 32768 } },
    "nvidia": { id: "meta/llama-3.2-3b-instruct", narrows: { context: 32768 } },
  },
  "meta-llama/llama-3.3-70b-instruct": {
    "azure": { id: "llama-3.3-70b-instruct", narrows: { context: 128000 } },
    "google-vertex": { id: "meta/llama-3.3-70b-instruct-maas", endpoint: "google-vertex.chat", narrows: { context: 128000 } },
    "huggingface": "meta-llama/Llama-3.3-70B-Instruct",
    "nebius": { id: "meta-llama/Llama-3.3-70B-Instruct", narrows: { context: 128000 } },
    "novita-ai": "meta-llama/llama-3.3-70b-instruct",
    "nvidia": { id: "meta/llama-3.3-70b-instruct", narrows: { context: 128000 } },
    "scaleway": { id: "llama-3.3-70b-instruct", narrows: { context: 100000 } },
  },
  "meta-llama/llama-guard-4-12b": {
    "nvidia": { id: "meta/llama-guard-4-12b", narrows: { context: 128000 } },
  },
  "meta/muse-glimmer-30b": {
    "vercel": "meta/muse-glimmer-30b",
  },
  "meta/muse-spark-1.1": {
    "meta": { id: "muse-spark-1.1", narrows: { context: 1000000, drops: ["audio"] } },
    "vercel": { id: "meta/muse-spark-1.1", narrows: { drops: ["video", "audio"] } },
  },
  "meta/muse-spark-1.2": {
    "meta": "muse-spark-1.2",
    "vercel": { id: "meta/muse-spark-1.2", narrows: { drops: ["video", "audio"] } },
  },
  "microsoft/phi-4": {
    "azure": "phi-4",
  },
  "microsoft/wizardlm-2-8x22b": {
    "novita-ai": "microsoft/wizardlm-2-8x22b",
  },
  "minimax/minimax-m2": {
    "amazon-bedrock": { id: "minimax.minimax-m2", narrows: { context: 204608 } },
    "huggingface": "MiniMaxAI/MiniMax-M2",
    "minimax": { id: "MiniMax-M2", narrows: { context: 196608 } },
    "novita-ai": "minimax/minimax-m2",
    "vercel": "minimax/minimax-m2",
  },
  "minimax/minimax-m2.1": {
    "amazon-bedrock": "minimax.minimax-m2.1",
    "huggingface": "MiniMaxAI/MiniMax-M2.1",
    "minimax": "MiniMax-M2.1",
    "novita-ai": "minimax/minimax-m2.1",
    "vercel": "minimax/minimax-m2.1",
  },
  "minimax/minimax-m2.5": {
    "amazon-bedrock": { id: "minimax.minimax-m2.5", narrows: { context: 196608 } },
    "baseten": { id: "MiniMaxAI/MiniMax-M2.5", narrows: { context: 204000 } },
    "deepinfra": { id: "MiniMaxAI/MiniMax-M2.5", narrows: { context: 196608 } },
    "friendli": { id: "MiniMaxAI/MiniMax-M2.5", narrows: { context: 196608 } },
    "huggingface": "MiniMaxAI/MiniMax-M2.5",
    "minimax": "MiniMax-M2.5",
    "nebius": { id: "MiniMaxAI/MiniMax-M2.5", narrows: { context: 196608 } },
    "novita-ai": "minimax/minimax-m2.5",
    "togetherai": "MiniMaxAI/MiniMax-M2.5",
    "vercel": "minimax/minimax-m2.5",
  },
  "minimax/minimax-m2.7": {
    "deepinfra": { id: "MiniMaxAI/MiniMax-M2.7", narrows: { context: 196608 } },
    "huggingface": "MiniMaxAI/MiniMax-M2.7",
    "minimax": "MiniMax-M2.7",
    "novita-ai": "minimax/minimax-m2.7",
    "nvidia": "minimaxai/minimax-m2.7",
    "togetherai": { id: "MiniMaxAI/MiniMax-M2.7", narrows: { context: 202752 } },
    "vercel": "minimax/minimax-m2.7",
  },
  "minimax/minimax-m3": {
    "deepinfra": { id: "MiniMaxAI/MiniMax-M3", narrows: { context: 524288 } },
    "fireworks-ai": { id: "accounts/fireworks/models/minimax-m3", narrows: { context: 512000 } },
    "huggingface": { id: "MiniMaxAI/MiniMax-M3", narrows: { context: 524288, drops: ["video"] } },
    "minimax": { id: "MiniMax-M3", narrows: { context: 1000000 } },
    "nebius": { id: "MiniMaxAI/MiniMax-M3", narrows: { drops: ["image", "video"] } },
    "nvidia": { id: "minimaxai/minimax-m3", narrows: { context: 1000000 } },
    "togetherai": { id: "MiniMaxAI/MiniMax-M3", narrows: { context: 524288, drops: ["video"] } },
    "vercel": { id: "minimax/minimax-m3", narrows: { context: 1000000, drops: ["video"] } },
  },
  "mistralai/mistral-large-2512": {
    "mistral": { id: "mistral-large-2512", narrows: { drops: ["pdf"] } },
  },
  "mistralai/mistral-nemo": {
    "mistral": { id: "mistral-nemo", narrows: { context: 128000 } },
    "novita-ai": { id: "mistralai/mistral-nemo", narrows: { context: 60288 } },
    "vercel": { id: "mistral/mistral-nemo", narrows: { context: 128000 } },
  },
  "mistralai/mistral-small-2603": {
    "mistral": { id: "mistral-small-2603", narrows: { context: 256000 } },
  },
  "mistralai/mixtral-8x22b-instruct": {
    "nvidia": { id: "mistralai/mixtral-8x22b-instruct", narrows: { drops: ["pdf"] } },
  },
  "mistralai/voxtral-small-24b-2507": {
    "amazon-bedrock": { id: "mistral.voxtral-small-24b-2507", narrows: { drops: ["pdf"] } },
  },
  "moonshotai/kimi-k2-0905": {
    "novita-ai": "moonshotai/kimi-k2-0905",
  },
  "moonshotai/kimi-k2-thinking": {
    "amazon-bedrock": { id: "moonshot.kimi-k2-thinking", narrows: { context: 262143 } },
    "google-vertex": { id: "moonshotai/kimi-k2-thinking-maas", endpoint: "google-vertex.chat" },
    "huggingface": "moonshotai/Kimi-K2-Thinking",
    "moonshotai": "kimi-k2-thinking",
    "novita-ai": "moonshotai/kimi-k2-thinking",
    "vercel": { id: "moonshotai/kimi-k2-thinking", narrows: { context: 216144 } },
  },
  "moonshotai/kimi-k2.5": {
    "azure": "kimi-k2.5",
    "baseten": { id: "moonshotai/Kimi-K2.5", narrows: { context: 262000 } },
    "deepinfra": "moonshotai/Kimi-K2.5",
    "huggingface": "moonshotai/Kimi-K2.5",
    "moonshotai": "kimi-k2.5",
    "nebius": { id: "moonshotai/Kimi-K2.5", narrows: { context: 256000 } },
    "novita-ai": "moonshotai/kimi-k2.5",
    "togetherai": "moonshotai/Kimi-K2.5",
    "vercel": { id: "moonshotai/kimi-k2.5", narrows: { context: 262114 } },
  },
  "moonshotai/kimi-k2.6": {
    "azure": "kimi-k2.6",
    "baseten": { id: "moonshotai/Kimi-K2.6", narrows: { context: 262000 } },
    "cloudflare-workers-ai": "@cf/moonshotai/kimi-k2.6",
    "deepinfra": "moonshotai/Kimi-K2.6",
    "huggingface": "moonshotai/Kimi-K2.6",
    "moonshotai": "kimi-k2.6",
    "novita-ai": "moonshotai/kimi-k2.6",
    "nvidia": "moonshotai/kimi-k2.6",
    "togetherai": "moonshotai/Kimi-K2.6",
    "vercel": { id: "moonshotai/kimi-k2.6", narrows: { context: 262000 } },
  },
  "moonshotai/kimi-k2.7-code": {
    "azure": "kimi-k2.7-code",
    "baseten": { id: "moonshotai/Kimi-K2.7-Code", narrows: { context: 262000 } },
    "cloudflare-workers-ai": "@cf/moonshotai/kimi-k2.7-code",
    "deepinfra": "moonshotai/Kimi-K2.7-Code",
    "huggingface": "moonshotai/Kimi-K2.7-Code",
    "moonshotai": "kimi-k2.7-code",
    "nebius": { id: "moonshotai/Kimi-K2.7-Code", narrows: { drops: ["image"] } },
    "novita-ai": "moonshotai/kimi-k2.7-code",
    "togetherai": { id: "moonshotai/Kimi-K2.7-Code", narrows: { drops: ["image"] } },
    "vercel": { id: "moonshotai/kimi-k2.7-code", narrows: { context: 256000 } },
  },
  "moonshotai/kimi-k3": {
    "baseten": { id: "moonshotai/Kimi-K3", narrows: { drops: ["video"] } },
    "deepinfra": { id: "moonshotai/Kimi-K3", narrows: { drops: ["video"] } },
    "fireworks-ai": { id: "accounts/fireworks/models/kimi-k3", narrows: { drops: ["video"] } },
    "huggingface": { id: "moonshotai/Kimi-K3", narrows: { context: 1000000, drops: ["video"] } },
    "moonshotai": "kimi-k3",
    "nebius": { id: "moonshotai/Kimi-K3", narrows: { drops: ["image", "video"] } },
    "novita-ai": "moonshotai/kimi-k3",
    "togetherai": "moonshotai/Kimi-K3",
    "vercel": { id: "moonshotai/kimi-k3", narrows: { context: 1000000, drops: ["video"] } },
  },
  "morph/morph-v3-fast": {
    "vercel": { id: "morph/morph-v3-fast", narrows: { context: 16000 } },
  },
  "morph/morph-v3-large": {
    "vercel": { id: "morph/morph-v3-large", narrows: { context: 32000 } },
  },
  "nousresearch/hermes-4-405b": {
    "nebius": { id: "NousResearch/Hermes-4-405B", narrows: { context: 128000 } },
  },
  "nousresearch/hermes-4-70b": {
    "nebius": { id: "NousResearch/Hermes-4-70B", narrows: { context: 128000 } },
  },
  "nvidia/nemotron-3-nano-30b-a3b": {
    "deepinfra": "nvidia/Nemotron-3-Nano-30B-A3B",
    "nvidia": { id: "nvidia/nemotron-3-nano-30b-a3b", narrows: { context: 131072 } },
    "vercel": "nvidia/nemotron-3-nano-30b-a3b",
  },
  "nvidia/nemotron-3-nano-30b-a3b:free": {
    "deepinfra": "nvidia/Nemotron-3-Nano-30B-A3B",
    "nvidia": { id: "nvidia/nemotron-3-nano-30b-a3b", narrows: { context: 131072 } },
    "vercel": "nvidia/nemotron-3-nano-30b-a3b",
  },
  "nvidia/nemotron-3-nano-omni-30b-a3b-reasoning:free": {
    "nvidia": "nvidia/nemotron-3-nano-omni-30b-a3b-reasoning",
  },
  "nvidia/nemotron-3-super-120b-a12b": {
    "nebius": { id: "nvidia/nemotron-3-super-120b-a12b", narrows: { context: 256000 } },
  },
  "nvidia/nemotron-3-super-120b-a12b:free": {
    "nvidia": "nvidia/nemotron-3-super-120b-a12b",
  },
  "nvidia/nemotron-3-ultra-550b-a55b": {
    "nvidia": "nvidia/nemotron-3-ultra-550b-a55b",
    "togetherai": "nvidia/nemotron-3-ultra-550b-a55b",
  },
  "nvidia/nemotron-3-ultra-550b-a55b:free": {
    "vercel": "nvidia/nemotron-3-ultra-550b-a55b",
  },
  "openai/gpt-3.5-turbo": {
    "openai": "gpt-3.5-turbo",
    "vercel": "openai/gpt-3.5-turbo",
  },
  "openai/gpt-3.5-turbo-instruct": {
    "azure": "gpt-3.5-turbo-instruct",
  },
  "openai/gpt-4": {
    "openai": "gpt-4",
  },
  "openai/gpt-4-turbo": {
    "azure": "gpt-4-turbo",
    "openai": "gpt-4-turbo",
    "vercel": "openai/gpt-4-turbo",
  },
  "openai/gpt-4.1": {
    "azure": { id: "gpt-4.1", narrows: { drops: ["pdf"] } },
    "openai": "gpt-4.1",
    "vercel": "openai/gpt-4.1",
  },
  "openai/gpt-4.1-mini": {
    "azure": { id: "gpt-4.1-mini", narrows: { drops: ["pdf"] } },
    "openai": "gpt-4.1-mini",
    "vercel": "openai/gpt-4.1-mini",
  },
  "openai/gpt-4.1-nano": {
    "azure": { id: "gpt-4.1-nano", narrows: { drops: ["pdf"] } },
    "openai": { id: "gpt-4.1-nano", narrows: { drops: ["pdf"] } },
    "vercel": { id: "openai/gpt-4.1-nano", narrows: { drops: ["pdf"] } },
  },
  "openai/gpt-4o": {
    "azure": { id: "gpt-4o", narrows: { drops: ["pdf"] } },
    "openai": "gpt-4o",
    "vercel": "openai/gpt-4o",
  },
  "openai/gpt-4o-2024-05-13": {
    "openai": { id: "gpt-4o-2024-05-13", narrows: { drops: ["pdf"] } },
  },
  "openai/gpt-4o-2024-08-06": {
    "openai": { id: "gpt-4o-2024-08-06", narrows: { drops: ["pdf"] } },
  },
  "openai/gpt-4o-2024-11-20": {
    "openai": { id: "gpt-4o-2024-11-20", narrows: { drops: ["pdf"] } },
  },
  "openai/gpt-4o-mini": {
    "azure": { id: "gpt-4o-mini", narrows: { drops: ["pdf"] } },
    "openai": "gpt-4o-mini",
    "vercel": "openai/gpt-4o-mini",
  },
  "openai/gpt-5": {
    "azure": { id: "gpt-5", narrows: { drops: ["pdf"] } },
    "openai": { id: "gpt-5", narrows: { drops: ["pdf"] } },
    "vercel": { id: "openai/gpt-5", narrows: { drops: ["pdf"] } },
  },
  "openai/gpt-5-mini": {
    "azure": { id: "gpt-5-mini", narrows: { drops: ["pdf"] } },
    "openai": { id: "gpt-5-mini", narrows: { drops: ["pdf"] } },
    "vercel": { id: "openai/gpt-5-mini", narrows: { drops: ["pdf"] } },
  },
  "openai/gpt-5-nano": {
    "azure": { id: "gpt-5-nano", narrows: { drops: ["pdf"] } },
    "openai": { id: "gpt-5-nano", narrows: { drops: ["pdf"] } },
    "vercel": { id: "openai/gpt-5-nano", narrows: { drops: ["pdf"] } },
  },
  "openai/gpt-5-pro": {
    "azure": { id: "gpt-5-pro", narrows: { drops: ["pdf"] } },
    "openai": { id: "gpt-5-pro", narrows: { drops: ["pdf"] } },
    "vercel": "openai/gpt-5-pro",
  },
  "openai/gpt-5.1": {
    "azure": { id: "gpt-5.1", narrows: { drops: ["pdf"] } },
    "openai": { id: "gpt-5.1", narrows: { drops: ["pdf"] } },
  },
  "openai/gpt-5.1-codex": {
    "azure": "gpt-5.1-codex",
    "vercel": "openai/gpt-5.1-codex",
  },
  "openai/gpt-5.1-codex-max": {
    "azure": "gpt-5.1-codex-max",
    "vercel": "openai/gpt-5.1-codex-max",
  },
  "openai/gpt-5.1-codex-mini": {
    "azure": "gpt-5.1-codex-mini",
    "vercel": "openai/gpt-5.1-codex-mini",
  },
  "openai/gpt-5.2": {
    "azure": { id: "gpt-5.2", narrows: { drops: ["pdf"] } },
    "openai": { id: "gpt-5.2", narrows: { drops: ["pdf"] } },
    "vercel": "openai/gpt-5.2",
  },
  "openai/gpt-5.2-codex": {
    "azure": "gpt-5.2-codex",
    "vercel": "openai/gpt-5.2-codex",
  },
  "openai/gpt-5.2-pro": {
    "openai": { id: "gpt-5.2-pro", narrows: { drops: ["pdf"] } },
  },
  "openai/gpt-5.3-codex": {
    "azure": { id: "gpt-5.3-codex", narrows: { drops: ["pdf"] } },
    "openai": "gpt-5.3-codex",
    "vercel": "openai/gpt-5.3-codex",
  },
  "openai/gpt-5.4": {
    "amazon-bedrock": { id: "openai.gpt-5.4", narrows: { context: 272000 } },
    "azure": "gpt-5.4",
    "openai": "gpt-5.4",
    "vercel": "openai/gpt-5.4",
  },
  "openai/gpt-5.4-mini": {
    "azure": "gpt-5.4-mini",
    "openai": { id: "gpt-5.4-mini", narrows: { drops: ["pdf"] } },
    "vercel": "openai/gpt-5.4-mini",
  },
  "openai/gpt-5.4-nano": {
    "azure": "gpt-5.4-nano",
    "openai": { id: "gpt-5.4-nano", narrows: { drops: ["pdf"] } },
    "vercel": "openai/gpt-5.4-nano",
  },
  "openai/gpt-5.4-pro": {
    "azure": { id: "gpt-5.4-pro", narrows: { drops: ["pdf"] } },
    "openai": { id: "gpt-5.4-pro", narrows: { drops: ["pdf"] } },
    "vercel": "openai/gpt-5.4-pro",
  },
  "openai/gpt-5.5": {
    "amazon-bedrock": { id: "openai.gpt-5.5", narrows: { context: 272000 } },
    "azure": "gpt-5.5",
    "openai": "gpt-5.5",
    "vercel": { id: "openai/gpt-5.5", narrows: { context: 1000000 } },
  },
  "openai/gpt-5.5-pro": {
    "openai": "gpt-5.5-pro",
    "vercel": { id: "openai/gpt-5.5-pro", narrows: { context: 1000000 } },
  },
  "openai/gpt-5.6-luna": {
    "amazon-bedrock": "openai.gpt-5.6-luna",
    "azure": "gpt-5.6-luna",
    "openai": "gpt-5.6-luna",
    "vercel": "openai/gpt-5.6-luna",
  },
  "openai/gpt-5.6-sol": {
    "amazon-bedrock": "openai.gpt-5.6-sol",
    "azure": "gpt-5.6-sol",
    "openai": "gpt-5.6-sol",
    "vercel": "openai/gpt-5.6-sol",
  },
  "openai/gpt-5.6-terra": {
    "amazon-bedrock": "openai.gpt-5.6-terra",
    "azure": "gpt-5.6-terra",
    "openai": "gpt-5.6-terra",
    "vercel": "openai/gpt-5.6-terra",
  },
  "openai/gpt-chat-latest": {
    "azure": { id: "gpt-chat-latest", narrows: { context: 128000 } },
  },
  "openai/gpt-oss-120b": {
    "amazon-bedrock": { id: "openai.gpt-oss-120b", narrows: { context: 128000 } },
    "cerebras": "gpt-oss-120b",
    "cloudflare-workers-ai": { id: "@cf/openai/gpt-oss-120b", narrows: { context: 128000 } },
    "deepinfra": "openai/gpt-oss-120b",
    "fireworks-ai": "accounts/fireworks/models/gpt-oss-120b",
    "google-vertex": { id: "openai/gpt-oss-120b-maas", endpoint: "google-vertex.chat" },
    "groq": "openai/gpt-oss-120b",
    "huggingface": "openai/gpt-oss-120b",
    "nebius": { id: "openai/gpt-oss-120b", narrows: { context: 128000 } },
    "nvidia": { id: "openai/gpt-oss-120b", narrows: { context: 128000 } },
    "scaleway": { id: "gpt-oss-120b", narrows: { context: 128000 } },
    "togetherai": "openai/gpt-oss-120b",
    "vercel": "openai/gpt-oss-120b",
  },
  "openai/gpt-oss-20b": {
    "amazon-bedrock": { id: "openai.gpt-oss-20b", narrows: { context: 128000 } },
    "cloudflare-workers-ai": { id: "@cf/openai/gpt-oss-20b", narrows: { context: 128000 } },
    "deepinfra": "openai/gpt-oss-20b",
    "fireworks-ai": "accounts/fireworks/models/gpt-oss-20b",
    "google-vertex": { id: "openai/gpt-oss-20b-maas", endpoint: "google-vertex.chat" },
    "groq": "openai/gpt-oss-20b",
    "huggingface": "openai/gpt-oss-20b",
    "novita-ai": "openai/gpt-oss-20b",
    "nvidia": "openai/gpt-oss-20b",
    "togetherai": "openai/gpt-oss-20b",
    "vercel": "openai/gpt-oss-20b",
  },
  "openai/gpt-oss-20b:free": {
    "amazon-bedrock": { id: "openai.gpt-oss-20b", narrows: { context: 128000 } },
    "cloudflare-workers-ai": { id: "@cf/openai/gpt-oss-20b", narrows: { context: 128000 } },
    "deepinfra": "openai/gpt-oss-20b",
    "fireworks-ai": "accounts/fireworks/models/gpt-oss-20b",
    "google-vertex": { id: "openai/gpt-oss-20b-maas", endpoint: "google-vertex.chat" },
    "groq": "openai/gpt-oss-20b",
    "huggingface": "openai/gpt-oss-20b",
    "novita-ai": "openai/gpt-oss-20b",
    "nvidia": "openai/gpt-oss-20b",
    "togetherai": "openai/gpt-oss-20b",
    "vercel": "openai/gpt-oss-20b",
  },
  "openai/gpt-oss-safeguard-20b": {
    "amazon-bedrock": { id: "openai.gpt-oss-safeguard-20b", narrows: { context: 128000 } },
    "vercel": "openai/gpt-oss-safeguard-20b",
  },
  "openai/o1": {
    "azure": { id: "o1", narrows: { drops: ["pdf"] } },
    "openai": "o1",
    "vercel": "openai/o1",
  },
  "openai/o1-pro": {
    "openai": { id: "o1-pro", narrows: { drops: ["pdf"] } },
  },
  "openai/o3": {
    "azure": { id: "o3", narrows: { drops: ["pdf"] } },
    "openai": "o3",
    "vercel": "openai/o3",
  },
  "openai/o3-mini": {
    "azure": { id: "o3-mini", narrows: { drops: ["pdf"] } },
    "openai": { id: "o3-mini", narrows: { drops: ["pdf"] } },
    "vercel": { id: "openai/o3-mini", narrows: { drops: ["pdf"] } },
  },
  "openai/o3-pro": {
    "openai": { id: "o3-pro", narrows: { drops: ["pdf"] } },
    "vercel": "openai/o3-pro",
  },
  "openai/o4-mini": {
    "azure": { id: "o4-mini", narrows: { drops: ["pdf"] } },
    "openai": { id: "o4-mini", narrows: { drops: ["pdf"] } },
    "vercel": { id: "openai/o4-mini", narrows: { drops: ["pdf"] } },
  },
  "perplexity/sonar": {
    "perplexity": { id: "sonar", narrows: { drops: ["image"] } },
    "vercel": { id: "perplexity/sonar", narrows: { context: 127000 } },
  },
  "perplexity/sonar-pro": {
    "perplexity": "sonar-pro",
    "vercel": "perplexity/sonar-pro",
  },
  "perplexity/sonar-reasoning-pro": {
    "perplexity": "sonar-reasoning-pro",
    "vercel": { id: "perplexity/sonar-reasoning-pro", narrows: { context: 127000 } },
  },
  "poolside/laguna-s-2.1": {
    "vercel": { id: "poolside/laguna-s-2.1", narrows: { context: 1000000 } },
  },
  "poolside/laguna-s-2.1:free": {
    "vercel": "poolside/laguna-s-2.1",
  },
  "poolside/laguna-xs-2.1": {
    "nvidia": "poolside/laguna-xs-2.1",
  },
  "poolside/laguna-xs-2.1:free": {
    "nvidia": "poolside/laguna-xs-2.1",
  },
  "qwen/qwen-2.5-72b-instruct": {
    "novita-ai": { id: "qwen/qwen-2.5-72b-instruct", narrows: { context: 32000 } },
  },
  "qwen/qwen-plus": {
    "alibaba": "qwen-plus",
  },
  "qwen/qwen2.5-vl-72b-instruct": {
    "alibaba": "qwen2-5-vl-72b-instruct",
    "nebius": "Qwen/Qwen2.5-VL-72B-Instruct",
    "novita-ai": { id: "qwen/qwen2.5-vl-72b-instruct", narrows: { context: 32768 } },
  },
  "qwen/qwen3-14b": {
    "alibaba": "qwen3-14b",
  },
  "qwen/qwen3-235b-a22b": {
    "alibaba": "qwen3-235b-a22b",
    "huggingface": { id: "Qwen/Qwen3-235B-A22B", narrows: { context: 40960 } },
  },
  "qwen/qwen3-235b-a22b-thinking-2507": {
    "huggingface": "Qwen/Qwen3-235B-A22B-Thinking-2507",
    "novita-ai": { id: "qwen/qwen3-235b-a22b-thinking-2507", narrows: { context: 131072 } },
  },
  "qwen/qwen3-30b-a3b-instruct-2507": {
    "nebius": { id: "Qwen/Qwen3-30B-A3B-Instruct-2507", narrows: { context: 128000 } },
  },
  "qwen/qwen3-32b": {
    "alibaba": "qwen3-32b",
    "amazon-bedrock": { id: "qwen.qwen3-32b-v1:0", narrows: { context: 16384 } },
    "deepinfra": { id: "Qwen/Qwen3-32B", narrows: { context: 40960 } },
    "huggingface": "Qwen/Qwen3-32B",
    "nebius": { id: "Qwen/Qwen3-32B", narrows: { context: 128000 } },
  },
  "qwen/qwen3-8b": {
    "alibaba": "qwen3-8b",
  },
  "qwen/qwen3-coder-30b-a3b-instruct": {
    "alibaba": "qwen3-coder-30b-a3b-instruct",
    "huggingface": "Qwen/Qwen3-Coder-30B-A3B-Instruct",
    "novita-ai": { id: "qwen/qwen3-coder-30b-a3b-instruct", narrows: { context: 160000 } },
    "scaleway": { id: "qwen3-coder-30b-a3b-instruct", narrows: { context: 128000 } },
  },
  "qwen/qwen3-coder-flash": {
    "alibaba": "qwen3-coder-flash",
  },
  "qwen/qwen3-coder-next": {
    "amazon-bedrock": { id: "qwen.qwen3-coder-next", narrows: { context: 131072 } },
    "huggingface": "Qwen/Qwen3-Coder-Next",
    "novita-ai": "qwen/qwen3-coder-next",
    "vercel": { id: "alibaba/qwen3-coder-next", narrows: { context: 256000 } },
  },
  "qwen/qwen3-coder-plus": {
    "alibaba": "qwen3-coder-plus",
    "vercel": "alibaba/qwen3-coder-plus",
  },
  "qwen/qwen3-max": {
    "alibaba": "qwen3-max",
    "deepinfra": { id: "Qwen/Qwen3-Max", narrows: { context: 256000 } },
    "novita-ai": "qwen/qwen3-max",
    "vercel": "alibaba/qwen3-max",
  },
  "qwen/qwen3-max-thinking": {
    "vercel": { id: "alibaba/qwen3-max-thinking", narrows: { context: 256000 } },
  },
  "qwen/qwen3-next-80b-a3b-instruct": {
    "alibaba": { id: "qwen3-next-80b-a3b-instruct", narrows: { context: 131072 } },
    "deepinfra": "Qwen/Qwen3-Next-80B-A3B-Instruct",
    "huggingface": "Qwen/Qwen3-Next-80B-A3B-Instruct",
    "novita-ai": { id: "qwen/qwen3-next-80b-a3b-instruct", narrows: { context: 131072 } },
    "nvidia": "qwen/qwen3-next-80b-a3b-instruct",
    "vercel": { id: "alibaba/qwen3-next-80b-a3b-instruct", narrows: { context: 131072 } },
  },
  "qwen/qwen3-next-80b-a3b-thinking": {
    "alibaba": { id: "qwen3-next-80b-a3b-thinking", narrows: { context: 131072 } },
  },
  "qwen/qwen3-vl-235b-a22b-instruct": {
    "novita-ai": { id: "qwen/qwen3-vl-235b-a22b-instruct", narrows: { context: 131072 } },
    "vercel": { id: "alibaba/qwen3-vl-235b-a22b-instruct", narrows: { context: 131072 } },
  },
  "qwen/qwen3-vl-235b-a22b-thinking": {
    "novita-ai": "qwen/qwen3-vl-235b-a22b-thinking",
  },
  "qwen/qwen3.5-122b-a10b": {
    "alibaba": "qwen3.5-122b-a10b",
    "deepinfra": "Qwen/Qwen3.5-122B-A10B",
    "huggingface": { id: "Qwen/Qwen3.5-122B-A10B", narrows: { drops: ["video"] } },
    "novita-ai": "qwen/qwen3.5-122b-a10b",
    "nvidia": "qwen/qwen3.5-122b-a10b",
    "siliconflow": { id: "Qwen/Qwen3.5-122B-A10B", narrows: { drops: ["image", "video"] } },
  },
  "qwen/qwen3.5-27b": {
    "alibaba": "qwen3.5-27b",
    "deepinfra": "Qwen/Qwen3.5-27B",
    "huggingface": { id: "Qwen/Qwen3.5-27B", narrows: { drops: ["video"] } },
    "novita-ai": "qwen/qwen3.5-27b",
    "siliconflow": { id: "Qwen/Qwen3.5-27B", narrows: { drops: ["image", "video"] } },
  },
  "qwen/qwen3.5-35b-a3b": {
    "alibaba": "qwen3.5-35b-a3b",
    "deepinfra": "Qwen/Qwen3.5-35B-A3B",
    "huggingface": { id: "Qwen/Qwen3.5-35B-A3B", narrows: { drops: ["video"] } },
    "novita-ai": "qwen/qwen3.5-35b-a3b",
    "siliconflow": { id: "Qwen/Qwen3.5-35B-A3B", narrows: { drops: ["image", "video"] } },
  },
  "qwen/qwen3.5-397b-a17b": {
    "alibaba": "qwen3.5-397b-a17b",
    "deepinfra": "Qwen/Qwen3.5-397B-A17B",
    "huggingface": { id: "Qwen/Qwen3.5-397B-A17B", narrows: { drops: ["video"] } },
    "nebius": { id: "Qwen/Qwen3.5-397B-A17B", narrows: { drops: ["image", "video"] } },
    "novita-ai": "qwen/qwen3.5-397b-a17b",
    "nvidia": { id: "qwen/qwen3.5-397b-a17b", narrows: { drops: ["video"] } },
    "scaleway": { id: "qwen3.5-397b-a17b", narrows: { context: 256000 } },
    "siliconflow": { id: "Qwen/Qwen3.5-397B-A17B", narrows: { drops: ["image", "video"] } },
    "togetherai": { id: "Qwen/Qwen3.5-397B-A17B", narrows: { drops: ["video"] } },
  },
  "qwen/qwen3.5-9b": {
    "deepinfra": "Qwen/Qwen3.5-9B",
    "huggingface": { id: "Qwen/Qwen3.5-9B", narrows: { drops: ["video"] } },
    "togetherai": { id: "Qwen/Qwen3.5-9B", narrows: { drops: ["video"] } },
  },
  "qwen/qwen3.6-27b": {
    "alibaba": "qwen3.6-27b",
    "deepinfra": "Qwen/Qwen3.6-27B",
    "groq": { id: "qwen/qwen3.6-27b", narrows: { context: 131072, drops: ["video"] } },
    "huggingface": { id: "Qwen/Qwen3.6-27B", narrows: { drops: ["video"] } },
    "siliconflow": { id: "Qwen/Qwen3.6-27B", narrows: { drops: ["image", "video"] } },
    "vercel": { id: "alibaba/qwen3.6-27b", narrows: { context: 256000, drops: ["video"] } },
  },
  "qwen/qwen3.6-35b-a3b": {
    "alibaba": "qwen3.6-35b-a3b",
    "deepinfra": "Qwen/Qwen3.6-35B-A3B",
    "huggingface": { id: "Qwen/Qwen3.6-35B-A3B", narrows: { drops: ["video"] } },
    "scaleway": { id: "qwen3.6-35b-a3b", narrows: { context: 128000, drops: ["video"] } },
    "siliconflow": { id: "Qwen/Qwen3.6-35B-A3B", narrows: { drops: ["image", "video"] } },
  },
  "qwen/qwen3.6-flash": {
    "alibaba": "qwen3.6-flash",
  },
  "qwen/qwen3.6-max-preview": {
    "alibaba": "qwen3.6-max-preview",
  },
  "qwen/qwen3.6-plus": {
    "alibaba": "qwen3.6-plus",
    "togetherai": { id: "Qwen/Qwen3.6-Plus", narrows: { drops: ["image", "video"] } },
    "vercel": { id: "alibaba/qwen3.6-plus", narrows: { drops: ["video"] } },
  },
  "qwen/qwen3.7-flash": {
    "vercel": { id: "alibaba/qwen3.7-flash", narrows: { context: 991000, drops: ["video"] } },
  },
  "qwen/qwen3.7-max": {
    "alibaba": "qwen3.7-max",
    "deepinfra": { id: "Qwen/Qwen3.7-Max", narrows: { context: 256000 } },
    "novita-ai": "qwen/qwen3.7-max",
    "togetherai": "Qwen/Qwen3.7-Max",
    "vercel": { id: "alibaba/qwen3.7-max", narrows: { context: 991000 } },
  },
  "qwen/qwen3.7-plus": {
    "alibaba": "qwen3.7-plus",
    "vercel": "alibaba/qwen3.7-plus",
  },
  "qwen/qwen3.8-max": {
    "alibaba": "qwen3.8-max",
    "deepinfra": { id: "Qwen/Qwen3.8-Max", narrows: { context: 256000 } },
    "vercel": { id: "alibaba/qwen3.8-max", narrows: { drops: ["video"] } },
  },
  "sakana/fugu-ultra": {
    "vercel": "sakana/fugu-ultra",
  },
  "stepfun/step-3.5-flash": {
    "huggingface": "stepfun-ai/Step-3.5-Flash",
    "nvidia": { id: "stepfun-ai/step-3.5-flash", narrows: { context: 256000 } },
    "stepfun": { id: "step-3.5-flash", narrows: { context: 256000 } },
  },
  "stepfun/step-3.7-flash": {
    "deepinfra": "stepfun-ai/Step-3.7-Flash",
    "huggingface": "stepfun-ai/Step-3.7-Flash",
    "nvidia": { id: "stepfun-ai/step-3.7-flash", narrows: { context: 256000, drops: ["video"] } },
    "stepfun": { id: "step-3.7-flash", narrows: { context: 256000 } },
    "vercel": { id: "stepfun/step-3.7-flash", narrows: { context: 256000, drops: ["video"] } },
  },
  "tencent/hy3": {
    "deepinfra": "tencent/Hy3",
    "huggingface": "tencent/Hy3",
    "vercel": "tencent/hy3",
  },
  "tencent/hy3-preview": {
    "siliconflow": "tencent/Hy3-preview",
  },
  "thinkingmachines/inkling": {
    "baseten": { id: "thinkingmachines/inkling", narrows: { drops: ["audio"] } },
    "deepinfra": { id: "thinkingmachines/Inkling", narrows: { context: 524288 } },
    "huggingface": { id: "thinkingmachines/Inkling", narrows: { drops: ["audio"] } },
    "nvidia": "thinkingmachines/inkling",
    "togetherai": { id: "thinkingmachines/Inkling", narrows: { context: 524288 } },
    "vercel": { id: "thinkingmachines/inkling", narrows: { context: 256000, drops: ["audio"] } },
  },
  "thinkingmachines/inkling-small": {
    "baseten": { id: "thinkingmachines/inkling-small", narrows: { drops: ["audio"] } },
    "deepinfra": "thinkingmachines/Inkling-Small",
    "huggingface": { id: "thinkingmachines/Inkling-Small", narrows: { drops: ["audio"] } },
    "vercel": { id: "thinkingmachines/inkling-small", narrows: { drops: ["audio"] } },
  },
  "upstage/solar-pro4": {
    "upstage": "solar-pro4",
  },
  "writer/palmyra-x5": {
    "amazon-bedrock": "writer.palmyra-x5-v1:0",
  },
  "x-ai/grok-4.20-multi-agent": {
    "vercel": "xai/grok-4.20-multi-agent",
  },
  "x-ai/grok-4.3": {
    "amazon-bedrock": { id: "xai.grok-4.3", narrows: { drops: ["pdf"] } },
    "vercel": "xai/grok-4.3",
    "xai": "grok-4.3",
  },
  "x-ai/grok-4.5": {
    "vercel": "xai/grok-4.5",
    "xai": "grok-4.5",
  },
  "x-ai/grok-4.6": {
    "vercel": { id: "xai/grok-4.6", narrows: { drops: ["image", "pdf"] } },
    "xai": "grok-4.6",
  },
  "x-ai/grok-build-0.1": {
    "vercel": { id: "xai/grok-build-0.1", narrows: { drops: ["pdf"] } },
    "xai": "grok-build-0.1",
  },
  "xiaomi/mimo-v2.5": {
    "deepinfra": { id: "XiaomiMiMo/MiMo-V2.5", narrows: { context: 262144 } },
    "huggingface": { id: "XiaomiMiMo/MiMo-V2.5", narrows: { context: 262144, drops: ["image", "audio", "video"] } },
  },
  "xiaomi/mimo-v2.5-pro": {
    "deepinfra": { id: "XiaomiMiMo/MiMo-V2.5-Pro", narrows: { context: 1048576 } },
    "huggingface": { id: "XiaomiMiMo/MiMo-V2.5-Pro", narrows: { context: 1048576 } },
    "novita-ai": { id: "xiaomimimo/mimo-v2.5-pro", narrows: { context: 1048576 } },
    "vercel": "xiaomi/mimo-v2.5-pro",
  },
  "z-ai/glm-4.5": {
    "huggingface": "zai-org/GLM-4.5",
    "novita-ai": "zai-org/glm-4.5",
    "vercel": { id: "zai/glm-4.5", narrows: { context: 128000 } },
    "zhipuai": "glm-4.5",
  },
  "z-ai/glm-4.5-air": {
    "huggingface": "zai-org/GLM-4.5-Air",
    "novita-ai": "zai-org/glm-4.5-air",
    "vercel": { id: "zai/glm-4.5-air", narrows: { context: 128000 } },
    "zhipuai": "glm-4.5-air",
  },
  "z-ai/glm-4.5v": {
    "huggingface": "zai-org/GLM-4.5V",
    "novita-ai": "zai-org/glm-4.5v",
    "vercel": "zai/glm-4.5v",
    "zhipuai": { id: "glm-4.5v", narrows: { context: 64000 } },
  },
  "z-ai/glm-4.6": {
    "deepinfra": { id: "zai-org/GLM-4.6", narrows: { context: 202752 } },
    "huggingface": "zai-org/GLM-4.6",
    "novita-ai": "zai-org/glm-4.6",
    "vercel": { id: "zai/glm-4.6", narrows: { context: 200000 } },
    "zhipuai": "glm-4.6",
  },
  "z-ai/glm-4.6v": {
    "novita-ai": "zai-org/glm-4.6v",
    "vercel": { id: "zai/glm-4.6v", narrows: { context: 128000, drops: ["video"] } },
    "zhipuai": { id: "glm-4.6v", narrows: { context: 128000 } },
  },
  "z-ai/glm-4.7": {
    "amazon-bedrock": "zai.glm-4.7",
    "baseten": { id: "zai-org/GLM-4.7", narrows: { context: 200000 } },
    "deepinfra": { id: "zai-org/GLM-4.7", narrows: { context: 202752 } },
    "google-vertex": { id: "zai-org/glm-4.7-maas", endpoint: "google-vertex.chat", narrows: { context: 200000 } },
    "huggingface": "zai-org/GLM-4.7",
    "novita-ai": "zai-org/glm-4.7",
    "vercel": { id: "zai/glm-4.7", narrows: { context: 200000 } },
    "zhipuai": "glm-4.7",
  },
  "z-ai/glm-4.7-flash": {
    "amazon-bedrock": { id: "zai.glm-4.7-flash", narrows: { context: 200000 } },
    "cloudflare-workers-ai": { id: "@cf/zai-org/glm-4.7-flash", narrows: { context: 131072 } },
    "deepinfra": "zai-org/GLM-4.7-Flash",
    "huggingface": { id: "zai-org/GLM-4.7-Flash", narrows: { context: 200000 } },
    "novita-ai": { id: "zai-org/glm-4.7-flash", narrows: { context: 200000 } },
    "vercel": { id: "zai/glm-4.7-flash", narrows: { context: 200000 } },
    "zhipuai": { id: "glm-4.7-flash", narrows: { context: 200000 } },
  },
  "z-ai/glm-5": {
    "amazon-bedrock": { id: "zai.glm-5", narrows: { context: 202752 } },
    "baseten": { id: "zai-org/GLM-5", narrows: { context: 202800 } },
    "deepinfra": { id: "zai-org/GLM-5", narrows: { context: 202752 } },
    "google-vertex": { id: "zai-org/glm-5-maas", endpoint: "google-vertex.chat", narrows: { context: 202752 } },
    "huggingface": { id: "zai-org/GLM-5", narrows: { context: 202752 } },
    "nebius": { id: "zai-org/GLM-5", narrows: { context: 200000 } },
    "novita-ai": { id: "zai-org/glm-5", narrows: { context: 202800 } },
    "togetherai": { id: "zai-org/GLM-5", narrows: { context: 202752 } },
    "vercel": { id: "zai/glm-5", narrows: { context: 202800 } },
    "zhipuai": "glm-5",
  },
  "z-ai/glm-5-turbo": {
    "vercel": "zai/glm-5-turbo",
  },
  "z-ai/glm-5.1": {
    "baseten": { id: "zai-org/GLM-5.1", narrows: { context: 202800 } },
    "deepinfra": { id: "zai-org/GLM-5.1", narrows: { context: 202752 } },
    "friendli": { id: "zai-org/GLM-5.1", narrows: { context: 202752 } },
    "huggingface": { id: "zai-org/GLM-5.1", narrows: { context: 202752 } },
    "novita-ai": "zai-org/glm-5.1",
    "togetherai": { id: "zai-org/GLM-5.1", narrows: { context: 202752 } },
    "vercel": { id: "zai/glm-5.1", narrows: { context: 202800 } },
    "zhipuai": { id: "glm-5.1", narrows: { context: 200000 } },
  },
  "z-ai/glm-5.2": {
    "alibaba": { id: "glm-5.2", narrows: { context: 1000000 } },
    "baseten": "zai-org/GLM-5.2",
    "cloudflare-workers-ai": { id: "@cf/zai-org/glm-5.2", narrows: { context: 262144 } },
    "deepinfra": "zai-org/GLM-5.2",
    "friendli": { id: "zai-org/GLM-5.2", narrows: { context: 1000000 } },
    "huggingface": { id: "zai-org/GLM-5.2", narrows: { context: 262144 } },
    "nebius": { id: "zai-org/GLM-5.2", narrows: { context: 432000 } },
    "novita-ai": "zai-org/glm-5.2",
    "nvidia": { id: "z-ai/glm-5.2", narrows: { context: 1000000 } },
    "scaleway": { id: "glm-5.2", narrows: { context: 256000 } },
    "siliconflow": "zai-org/GLM-5.2",
    "togetherai": { id: "zai-org/GLM-5.2", narrows: { context: 512000 } },
    "vercel": { id: "zai/glm-5.2", narrows: { context: 1000000 } },
    "zhipuai": { id: "glm-5.2", narrows: { context: 1000000 } },
  },
  "z-ai/glm-5v-turbo": {
    "vercel": { id: "zai/glm-5v-turbo", narrows: { context: 200000, drops: ["video"] } },
    "zhipuai": { id: "glm-5v-turbo", narrows: { context: 200000 } },
  },
} as const satisfies AvailabilityMap;

export type OpenrouterAvailability = typeof availability;
