// Generated by scripts/codegen.ts — DO NOT EDIT.
// Derived from data/models-dev.json (https://models.dev/api.json) by the conjunction
// heuristic in scripts/availability.ts, filtered by data/availability-overrides.json.
// Regenerate with `bun run codegen` (or `bun run codegen:refresh` to update the snapshot).

import type { AvailabilityMap } from "../../core/translate/availability-types";

/**
 * Which providers serve scaleway's chat models, and what each one calls
 * them. Source model id → target provider id → the target's own id.
 *
 * scaleway itself is always among the targets: a provider serves its own
 * models by definition, so the identity retarget `.toApi("scaleway")` is
 * valid (and lossless) for every row here, including rows nobody else serves.
 *
 * A bare string means the target's default endpoint; the object form carries
 * a non-default `endpoint` and/or `narrows` metadata (a smaller context
 * window, or input modalities the target does not accept) so `.toApi` can
 * warn without loading the target provider's catalog.
 */
export const availability = {
  "gemma-4-26b-a4b-it": {
    "cloudflare-workers-ai": "@cf/google/gemma-4-26b-a4b-it",
    "deepinfra": "google/gemma-4-26B-A4B-it",
    "google": "gemma-4-26b-a4b-it",
    "huggingface": "google/gemma-4-26B-A4B-it",
    "openrouter": "google/gemma-4-26b-a4b-it",
    "scaleway": "gemma-4-26b-a4b-it",
    "siliconflow": { id: "google/gemma-4-26B-A4B-it", narrows: { drops: ["image"] } },
    "vercel": "google/gemma-4-26b-a4b-it",
  },
  "glm-5.2": {
    "alibaba": "glm-5.2",
    "baseten": "zai-org/GLM-5.2",
    "cloudflare-workers-ai": "@cf/zai-org/glm-5.2",
    "deepinfra": "zai-org/GLM-5.2",
    "friendli": "zai-org/GLM-5.2",
    "huggingface": "zai-org/GLM-5.2",
    "nebius": "zai-org/GLM-5.2",
    "novita-ai": "zai-org/glm-5.2",
    "nvidia": "z-ai/glm-5.2",
    "openrouter": "z-ai/glm-5.2",
    "scaleway": "glm-5.2",
    "siliconflow": "zai-org/GLM-5.2",
    "togetherai": "zai-org/GLM-5.2",
    "vercel": "zai/glm-5.2",
    "zhipuai": "glm-5.2",
  },
  "gpt-oss-120b": {
    "amazon-bedrock": "openai.gpt-oss-120b",
    "cerebras": "gpt-oss-120b",
    "cloudflare-workers-ai": "@cf/openai/gpt-oss-120b",
    "deepinfra": "openai/gpt-oss-120b",
    "fireworks-ai": "accounts/fireworks/models/gpt-oss-120b",
    "google-vertex": { id: "openai/gpt-oss-120b-maas", endpoint: "google-vertex.chat" },
    "groq": "openai/gpt-oss-120b",
    "huggingface": "openai/gpt-oss-120b",
    "nebius": "openai/gpt-oss-120b",
    "nvidia": "openai/gpt-oss-120b",
    "openrouter": "openai/gpt-oss-120b",
    "scaleway": "gpt-oss-120b",
    "togetherai": "openai/gpt-oss-120b",
    "vercel": "openai/gpt-oss-120b",
  },
  "llama-3.3-70b-instruct": {
    "azure": "llama-3.3-70b-instruct",
    "google-vertex": { id: "meta/llama-3.3-70b-instruct-maas", endpoint: "google-vertex.chat" },
    "huggingface": "meta-llama/Llama-3.3-70B-Instruct",
    "nebius": "meta-llama/Llama-3.3-70B-Instruct",
    "novita-ai": "meta-llama/llama-3.3-70b-instruct",
    "nvidia": "meta/llama-3.3-70b-instruct",
    "openrouter": "meta-llama/llama-3.3-70b-instruct",
    "scaleway": "llama-3.3-70b-instruct",
  },
  "mistral-medium-3.5-128b": {
    "scaleway": "mistral-medium-3.5-128b",
  },
  "mistral-small-3.2-24b-instruct-2506": {
    "scaleway": "mistral-small-3.2-24b-instruct-2506",
  },
  "pixtral-12b-2409": {
    "scaleway": "pixtral-12b-2409",
  },
  "qwen3-235b-a22b-instruct-2507": {
    "deepinfra": "Qwen/Qwen3-235B-A22B-Instruct-2507",
    "huggingface": "Qwen/Qwen3-235B-A22B-Instruct-2507",
    "nebius": "Qwen/Qwen3-235B-A22B-Instruct-2507",
    "novita-ai": { id: "qwen/qwen3-235b-a22b-instruct-2507", narrows: { context: 131072 } },
    "scaleway": "qwen3-235b-a22b-instruct-2507",
  },
  "qwen3-coder-30b-a3b-instruct": {
    "alibaba": "qwen3-coder-30b-a3b-instruct",
    "huggingface": "Qwen/Qwen3-Coder-30B-A3B-Instruct",
    "novita-ai": "qwen/qwen3-coder-30b-a3b-instruct",
    "openrouter": "qwen/qwen3-coder-30b-a3b-instruct",
    "scaleway": "qwen3-coder-30b-a3b-instruct",
  },
  "qwen3.5-397b-a17b": {
    "alibaba": "qwen3.5-397b-a17b",
    "deepinfra": "Qwen/Qwen3.5-397B-A17B",
    "huggingface": { id: "Qwen/Qwen3.5-397B-A17B", narrows: { drops: ["video"] } },
    "nebius": { id: "Qwen/Qwen3.5-397B-A17B", narrows: { drops: ["image", "video"] } },
    "novita-ai": "qwen/qwen3.5-397b-a17b",
    "nvidia": { id: "qwen/qwen3.5-397b-a17b", narrows: { drops: ["video"] } },
    "openrouter": "qwen/qwen3.5-397b-a17b",
    "scaleway": "qwen3.5-397b-a17b",
    "siliconflow": { id: "Qwen/Qwen3.5-397B-A17B", narrows: { drops: ["image", "video"] } },
    "togetherai": { id: "Qwen/Qwen3.5-397B-A17B", narrows: { drops: ["video"] } },
  },
  "qwen3.6-35b-a3b": {
    "alibaba": "qwen3.6-35b-a3b",
    "deepinfra": "Qwen/Qwen3.6-35B-A3B",
    "huggingface": "Qwen/Qwen3.6-35B-A3B",
    "openrouter": "qwen/qwen3.6-35b-a3b",
    "scaleway": "qwen3.6-35b-a3b",
    "siliconflow": { id: "Qwen/Qwen3.6-35B-A3B", narrows: { drops: ["image"] } },
  },
} as const satisfies AvailabilityMap;

export type ScalewayAvailability = typeof availability;
