// Generated by scripts/codegen.ts — DO NOT EDIT.
// Derived from data/models-dev.json (https://models.dev/api.json) by the conjunction
// heuristic in scripts/availability.ts, filtered by data/availability-overrides.json.
// Regenerate with `bun run codegen` (or `bun run codegen:refresh` to update the snapshot).

import type { AvailabilityMap } from "../../core/translate/availability-types";

/**
 * Which providers serve siliconflow's chat models, and what each one calls
 * them. Source model id → target provider id → the target's own id.
 *
 * siliconflow itself is always among the targets: a provider serves its own
 * models by definition, so the identity retarget `.toApi("siliconflow")` is
 * valid (and lossless) for every row here, including rows nobody else serves.
 *
 * A bare string means the target's default endpoint; the object form carries
 * a non-default `endpoint` and/or `narrows` metadata (a smaller context
 * window, or input modalities the target does not accept) so `.toApi` can
 * warn without loading the target provider's catalog.
 */
export const availability = {
  "ByteDance-Seed/Seed-OSS-36B-Instruct": {
    "nvidia": "bytedance/seed-oss-36b-instruct",
    "siliconflow": "ByteDance-Seed/Seed-OSS-36B-Instruct",
  },
  "MiniMaxAI/MiniMax-M2.5": {
    "siliconflow": "MiniMaxAI/MiniMax-M2.5",
  },
  "Qwen/Qwen2.5-72B-Instruct": {
    "siliconflow": "Qwen/Qwen2.5-72B-Instruct",
  },
  "Qwen/Qwen2.5-7B-Instruct": {
    "siliconflow": "Qwen/Qwen2.5-7B-Instruct",
  },
  "Qwen/Qwen3-14B": {
    "siliconflow": "Qwen/Qwen3-14B",
  },
  "Qwen/Qwen3-235B-A22B-Thinking-2507": {
    "siliconflow": "Qwen/Qwen3-235B-A22B-Thinking-2507",
  },
  "Qwen/Qwen3-30B-A3B-Instruct-2507": {
    "siliconflow": "Qwen/Qwen3-30B-A3B-Instruct-2507",
  },
  "Qwen/Qwen3-32B": {
    "siliconflow": "Qwen/Qwen3-32B",
  },
  "Qwen/Qwen3-8B": {
    "siliconflow": "Qwen/Qwen3-8B",
  },
  "Qwen/Qwen3-Coder-30B-A3B-Instruct": {
    "siliconflow": "Qwen/Qwen3-Coder-30B-A3B-Instruct",
  },
  "Qwen/Qwen3-Coder-480B-A35B-Instruct": {
    "siliconflow": "Qwen/Qwen3-Coder-480B-A35B-Instruct",
  },
  "Qwen/Qwen3-VL-235B-A22B-Instruct": {
    "siliconflow": "Qwen/Qwen3-VL-235B-A22B-Instruct",
  },
  "Qwen/Qwen3-VL-235B-A22B-Thinking": {
    "siliconflow": "Qwen/Qwen3-VL-235B-A22B-Thinking",
  },
  "Qwen/Qwen3-VL-30B-A3B-Instruct": {
    "novita-ai": { id: "qwen/qwen3-vl-30b-a3b-instruct", narrows: { context: 131072 } },
    "siliconflow": "Qwen/Qwen3-VL-30B-A3B-Instruct",
  },
  "Qwen/Qwen3-VL-30B-A3B-Thinking": {
    "novita-ai": { id: "qwen/qwen3-vl-30b-a3b-thinking", narrows: { context: 131072 } },
    "siliconflow": "Qwen/Qwen3-VL-30B-A3B-Thinking",
  },
  "Qwen/Qwen3-VL-32B-Instruct": {
    "siliconflow": "Qwen/Qwen3-VL-32B-Instruct",
  },
  "Qwen/Qwen3-VL-32B-Thinking": {
    "siliconflow": "Qwen/Qwen3-VL-32B-Thinking",
  },
  "Qwen/Qwen3-VL-8B-Instruct": {
    "novita-ai": { id: "qwen/qwen3-vl-8b-instruct", narrows: { context: 131072 } },
    "siliconflow": "Qwen/Qwen3-VL-8B-Instruct",
  },
  "Qwen/Qwen3.5-122B-A10B": {
    "alibaba": "qwen3.5-122b-a10b",
    "deepinfra": "Qwen/Qwen3.5-122B-A10B",
    "huggingface": "Qwen/Qwen3.5-122B-A10B",
    "novita-ai": "qwen/qwen3.5-122b-a10b",
    "nvidia": "qwen/qwen3.5-122b-a10b",
    "openrouter": "qwen/qwen3.5-122b-a10b",
    "siliconflow": "Qwen/Qwen3.5-122B-A10B",
  },
  "Qwen/Qwen3.5-27B": {
    "alibaba": "qwen3.5-27b",
    "deepinfra": "Qwen/Qwen3.5-27B",
    "huggingface": "Qwen/Qwen3.5-27B",
    "novita-ai": "qwen/qwen3.5-27b",
    "openrouter": "qwen/qwen3.5-27b",
    "siliconflow": "Qwen/Qwen3.5-27B",
  },
  "Qwen/Qwen3.5-35B-A3B": {
    "alibaba": "qwen3.5-35b-a3b",
    "deepinfra": "Qwen/Qwen3.5-35B-A3B",
    "huggingface": "Qwen/Qwen3.5-35B-A3B",
    "novita-ai": "qwen/qwen3.5-35b-a3b",
    "openrouter": "qwen/qwen3.5-35b-a3b",
    "siliconflow": "Qwen/Qwen3.5-35B-A3B",
  },
  "Qwen/Qwen3.5-397B-A17B": {
    "alibaba": "qwen3.5-397b-a17b",
    "deepinfra": "Qwen/Qwen3.5-397B-A17B",
    "huggingface": "Qwen/Qwen3.5-397B-A17B",
    "nebius": "Qwen/Qwen3.5-397B-A17B",
    "novita-ai": "qwen/qwen3.5-397b-a17b",
    "nvidia": "qwen/qwen3.5-397b-a17b",
    "openrouter": "qwen/qwen3.5-397b-a17b",
    "scaleway": { id: "qwen3.5-397b-a17b", narrows: { context: 256000 } },
    "siliconflow": "Qwen/Qwen3.5-397B-A17B",
    "togetherai": "Qwen/Qwen3.5-397B-A17B",
  },
  "Qwen/Qwen3.5-9B": {
    "siliconflow": "Qwen/Qwen3.5-9B",
  },
  "Qwen/Qwen3.6-27B": {
    "alibaba": "qwen3.6-27b",
    "deepinfra": "Qwen/Qwen3.6-27B",
    "groq": { id: "qwen/qwen3.6-27b", narrows: { context: 131072 } },
    "huggingface": "Qwen/Qwen3.6-27B",
    "openrouter": "qwen/qwen3.6-27b",
    "siliconflow": "Qwen/Qwen3.6-27B",
    "vercel": { id: "alibaba/qwen3.6-27b", narrows: { context: 256000 } },
  },
  "Qwen/Qwen3.6-35B-A3B": {
    "alibaba": "qwen3.6-35b-a3b",
    "deepinfra": "Qwen/Qwen3.6-35B-A3B",
    "huggingface": "Qwen/Qwen3.6-35B-A3B",
    "openrouter": "qwen/qwen3.6-35b-a3b",
    "scaleway": { id: "qwen3.6-35b-a3b", narrows: { context: 128000 } },
    "siliconflow": "Qwen/Qwen3.6-35B-A3B",
  },
  "baidu/ERNIE-4.5-300B-A47B": {
    "siliconflow": "baidu/ERNIE-4.5-300B-A47B",
  },
  "deepseek-ai/DeepSeek-R1": {
    "siliconflow": "deepseek-ai/DeepSeek-R1",
  },
  "deepseek-ai/DeepSeek-V3": {
    "siliconflow": "deepseek-ai/DeepSeek-V3",
  },
  "deepseek-ai/DeepSeek-V3.1": {
    "siliconflow": "deepseek-ai/DeepSeek-V3.1",
  },
  "deepseek-ai/DeepSeek-V3.1-Terminus": {
    "siliconflow": "deepseek-ai/DeepSeek-V3.1-Terminus",
  },
  "deepseek-ai/DeepSeek-V3.2": {
    "siliconflow": "deepseek-ai/DeepSeek-V3.2",
  },
  "deepseek-ai/DeepSeek-V3.2-Exp": {
    "siliconflow": "deepseek-ai/DeepSeek-V3.2-Exp",
  },
  "deepseek-ai/DeepSeek-V4-Flash": {
    "azure": "deepseek-v4-flash",
    "deepinfra": "deepseek-ai/DeepSeek-V4-Flash",
    "deepseek": "deepseek-v4-flash",
    "huggingface": "deepseek-ai/DeepSeek-V4-Flash",
    "nebius": { id: "deepseek-ai/DeepSeek-V4-Flash", narrows: { context: 131072 } },
    "novita-ai": "deepseek/deepseek-v4-flash",
    "nvidia": "deepseek-ai/deepseek-v4-flash",
    "openrouter": "deepseek/deepseek-v4-flash",
    "siliconflow": "deepseek-ai/DeepSeek-V4-Flash",
    "vercel": "deepseek/deepseek-v4-flash",
  },
  "deepseek-ai/DeepSeek-V4-Pro": {
    "azure": "deepseek-v4-pro",
    "baseten": "deepseek-ai/DeepSeek-V4-Pro",
    "deepinfra": "deepseek-ai/DeepSeek-V4-Pro",
    "deepseek": "deepseek-v4-pro",
    "huggingface": "deepseek-ai/DeepSeek-V4-Pro",
    "nebius": "deepseek-ai/DeepSeek-V4-Pro",
    "novita-ai": "deepseek/deepseek-v4-pro",
    "nvidia": "deepseek-ai/deepseek-v4-pro",
    "openrouter": "deepseek/deepseek-v4-pro",
    "siliconflow": "deepseek-ai/DeepSeek-V4-Pro",
    "togetherai": { id: "deepseek-ai/DeepSeek-V4-Pro", narrows: { context: 512000 } },
    "vercel": "deepseek/deepseek-v4-pro",
  },
  "google/gemma-4-26B-A4B-it": {
    "cloudflare-workers-ai": { id: "@cf/google/gemma-4-26b-a4b-it", narrows: { context: 256000 } },
    "deepinfra": "google/gemma-4-26B-A4B-it",
    "google": "gemma-4-26b-a4b-it",
    "huggingface": "google/gemma-4-26B-A4B-it",
    "openrouter": "google/gemma-4-26b-a4b-it",
    "scaleway": { id: "gemma-4-26b-a4b-it", narrows: { context: 256000 } },
    "siliconflow": "google/gemma-4-26B-A4B-it",
    "vercel": "google/gemma-4-26b-a4b-it",
  },
  "google/gemma-4-31B-it": {
    "deepinfra": "google/gemma-4-31B-it",
    "friendli": "google/gemma-4-31B-it",
    "google": "gemma-4-31b-it",
    "huggingface": "google/gemma-4-31B-it",
    "nvidia": { id: "google/gemma-4-31b-it", narrows: { context: 256000 } },
    "openrouter": "google/gemma-4-31b-it",
    "siliconflow": "google/gemma-4-31B-it",
    "vercel": "google/gemma-4-31b-it",
  },
  "inclusionAI/Ling-flash-2.0": {
    "siliconflow": "inclusionAI/Ling-flash-2.0",
  },
  "moonshotai/Kimi-K2.5": {
    "siliconflow": "moonshotai/Kimi-K2.5",
  },
  "moonshotai/Kimi-K2.6": {
    "siliconflow": "moonshotai/Kimi-K2.6",
  },
  "openai/gpt-oss-120b": {
    "novita-ai": "openai/gpt-oss-120b",
    "siliconflow": "openai/gpt-oss-120b",
  },
  "openai/gpt-oss-20b": {
    "siliconflow": "openai/gpt-oss-20b",
  },
  "stepfun-ai/Step-3.5-Flash": {
    "siliconflow": "stepfun-ai/Step-3.5-Flash",
  },
  "tencent/Hunyuan-A13B-Instruct": {
    "siliconflow": "tencent/Hunyuan-A13B-Instruct",
  },
  "tencent/Hy3-preview": {
    "openrouter": "tencent/hy3-preview",
    "siliconflow": "tencent/Hy3-preview",
  },
  "zai-org/GLM-4.5-Air": {
    "siliconflow": "zai-org/GLM-4.5-Air",
  },
  "zai-org/GLM-5": {
    "siliconflow": "zai-org/GLM-5",
  },
  "zai-org/GLM-5.1": {
    "siliconflow": "zai-org/GLM-5.1",
  },
  "zai-org/GLM-5.2": {
    "alibaba": { id: "glm-5.2", narrows: { context: 1000000 } },
    "baseten": { id: "zai-org/GLM-5.2", narrows: { context: 1048576 } },
    "cloudflare-workers-ai": { id: "@cf/zai-org/glm-5.2", narrows: { context: 262144 } },
    "deepinfra": { id: "zai-org/GLM-5.2", narrows: { context: 1048576 } },
    "friendli": { id: "zai-org/GLM-5.2", narrows: { context: 1000000 } },
    "huggingface": { id: "zai-org/GLM-5.2", narrows: { context: 262144 } },
    "nebius": { id: "zai-org/GLM-5.2", narrows: { context: 432000 } },
    "novita-ai": { id: "zai-org/glm-5.2", narrows: { context: 1048576 } },
    "nvidia": { id: "z-ai/glm-5.2", narrows: { context: 1000000 } },
    "openrouter": { id: "z-ai/glm-5.2", narrows: { context: 1048576 } },
    "scaleway": { id: "glm-5.2", narrows: { context: 256000 } },
    "siliconflow": "zai-org/GLM-5.2",
    "togetherai": { id: "zai-org/GLM-5.2", narrows: { context: 512000 } },
    "vercel": { id: "zai/glm-5.2", narrows: { context: 1000000 } },
    "zhipuai": { id: "glm-5.2", narrows: { context: 1000000 } },
  },
  "zai-org/GLM-5V-Turbo": {
    "siliconflow": "zai-org/GLM-5V-Turbo",
  },
} as const satisfies AvailabilityMap;

export type SiliconflowAvailability = typeof availability;
