// Generated by scripts/codegen.ts — DO NOT EDIT.
// Derived from data/models-dev.json (https://models.dev/api.json) by the conjunction
// heuristic in scripts/availability.ts, filtered by data/availability-overrides.json.
// Regenerate with `bun run codegen` (or `bun run codegen:refresh` to update the snapshot).

import type { AvailabilityMap } from "../../core/translate/availability-types";

/**
 * Which providers serve stepfun's chat models, and what each one calls
 * them. Source model id → target provider id → the target's own id.
 *
 * stepfun itself is always among the targets: a provider serves its own
 * models by definition, so the identity retarget `.toApi("stepfun")` is
 * valid (and lossless) for every row here, including rows nobody else serves.
 *
 * A bare string means the target's default endpoint; the object form carries
 * a non-default `endpoint` and/or `narrows` metadata (a smaller context
 * window, or input modalities the target does not accept) so `.toApi` can
 * warn without loading the target provider's catalog.
 */
export const availability = {
  "step-1-32k": {
    "stepfun": "step-1-32k",
  },
  "step-2-16k": {
    "stepfun": "step-2-16k",
  },
  "step-3.5-flash": {
    "huggingface": "stepfun-ai/Step-3.5-Flash",
    "nvidia": "stepfun-ai/step-3.5-flash",
    "openrouter": "stepfun/step-3.5-flash",
    "stepfun": "step-3.5-flash",
  },
  "step-3.5-flash-2603": {
    "stepfun": "step-3.5-flash-2603",
  },
  "step-3.7-flash": {
    "deepinfra": "stepfun-ai/Step-3.7-Flash",
    "huggingface": "stepfun-ai/Step-3.7-Flash",
    "nvidia": { id: "stepfun-ai/step-3.7-flash", narrows: { drops: ["video"] } },
    "openrouter": "stepfun/step-3.7-flash",
    "stepfun": "step-3.7-flash",
    "vercel": { id: "stepfun/step-3.7-flash", narrows: { drops: ["video"] } },
  },
  "stepaudio-2.5-asr": {
    "stepfun": "stepaudio-2.5-asr",
  },
} as const satisfies AvailabilityMap;

export type StepfunAvailability = typeof availability;
