// Generated by scripts/codegen.ts — DO NOT EDIT.
// Derived from data/models-dev.json (https://models.dev/api.json) by the conjunction
// heuristic in scripts/availability.ts, filtered by data/availability-overrides.json.
// Regenerate with `bun run codegen` (or `bun run codegen:refresh` to update the snapshot).

import type { AvailabilityMap } from "../../core/translate/availability-types";

/**
 * Which providers serve upstage's chat models, and what each one calls
 * them. Source model id → target provider id → the target's own id.
 *
 * upstage itself is always among the targets: a provider serves its own
 * models by definition, so the identity retarget `.toApi("upstage")` is
 * valid (and lossless) for every row here, including rows nobody else serves.
 *
 * A bare string means the target's default endpoint; the object form carries
 * a non-default `endpoint` and/or `narrows` metadata (a smaller context
 * window, or input modalities the target does not accept) so `.toApi` can
 * warn without loading the target provider's catalog.
 */
export const availability = {
  "solar-mini": {
    "upstage": "solar-mini",
  },
  "solar-pro2": {
    "upstage": "solar-pro2",
  },
  "solar-pro3": {
    "upstage": "solar-pro3",
  },
  "solar-pro4": {
    "openrouter": "upstage/solar-pro4",
    "upstage": "solar-pro4",
  },
} as const satisfies AvailabilityMap;

export type UpstageAvailability = typeof availability;
