// Generated by scripts/codegen.ts — DO NOT EDIT.
// Derived from data/models-dev.json (https://models.dev/api.json) by the conjunction
// heuristic in scripts/availability.ts, filtered by data/availability-overrides.json.
// Regenerate with `bun run codegen` (or `bun run codegen:refresh` to update the snapshot).

import type { AvailabilityMap } from "../../core/translate/availability-types";

/**
 * Which providers serve zhipuai's chat models, and what each one calls
 * them. Source model id → target provider id → the target's own id.
 *
 * zhipuai itself is always among the targets: a provider serves its own
 * models by definition, so the identity retarget `.toApi("zhipuai")` is
 * valid (and lossless) for every row here, including rows nobody else serves.
 *
 * A bare string means the target's default endpoint; the object form carries
 * a non-default `endpoint` and/or `narrows` metadata (a smaller context
 * window, or input modalities the target does not accept) so `.toApi` can
 * warn without loading the target provider's catalog.
 */
export const availability = {
  "glm-4.5": {
    "huggingface": "zai-org/GLM-4.5",
    "novita-ai": "zai-org/glm-4.5",
    "openrouter": "z-ai/glm-4.5",
    "vercel": { id: "zai/glm-4.5", narrows: { context: 128000 } },
    "zhipuai": "glm-4.5",
  },
  "glm-4.5-air": {
    "huggingface": "zai-org/GLM-4.5-Air",
    "novita-ai": "zai-org/glm-4.5-air",
    "openrouter": "z-ai/glm-4.5-air",
    "vercel": { id: "zai/glm-4.5-air", narrows: { context: 128000 } },
    "zhipuai": "glm-4.5-air",
  },
  "glm-4.5-flash": {
    "zhipuai": "glm-4.5-flash",
  },
  "glm-4.5v": {
    "huggingface": { id: "zai-org/GLM-4.5V", narrows: { drops: ["video"] } },
    "novita-ai": "zai-org/glm-4.5v",
    "openrouter": { id: "z-ai/glm-4.5v", narrows: { drops: ["video"] } },
    "vercel": { id: "zai/glm-4.5v", narrows: { drops: ["video"] } },
    "zhipuai": "glm-4.5v",
  },
  "glm-4.6": {
    "deepinfra": { id: "zai-org/GLM-4.6", narrows: { context: 202752 } },
    "huggingface": "zai-org/GLM-4.6",
    "novita-ai": "zai-org/glm-4.6",
    "openrouter": "z-ai/glm-4.6",
    "vercel": { id: "zai/glm-4.6", narrows: { context: 200000 } },
    "zhipuai": "glm-4.6",
  },
  "glm-4.6v": {
    "novita-ai": "zai-org/glm-4.6v",
    "openrouter": "z-ai/glm-4.6v",
    "zhipuai": "glm-4.6v",
  },
  "glm-4.7": {
    "amazon-bedrock": "zai.glm-4.7",
    "baseten": { id: "zai-org/GLM-4.7", narrows: { context: 200000 } },
    "deepinfra": { id: "zai-org/GLM-4.7", narrows: { context: 202752 } },
    "google-vertex": { id: "zai-org/glm-4.7-maas", endpoint: "google-vertex.chatMaas", narrows: { context: 200000 } },
    "huggingface": "zai-org/GLM-4.7",
    "novita-ai": "zai-org/glm-4.7",
    "openrouter": "z-ai/glm-4.7",
    "vercel": { id: "zai/glm-4.7", narrows: { context: 200000 } },
    "zhipuai": "glm-4.7",
  },
  "glm-4.7-flash": {
    "amazon-bedrock": "zai.glm-4.7-flash",
    "cloudflare-workers-ai": { id: "@cf/zai-org/glm-4.7-flash", narrows: { context: 131072 } },
    "deepinfra": "zai-org/GLM-4.7-Flash",
    "huggingface": "zai-org/GLM-4.7-Flash",
    "novita-ai": "zai-org/glm-4.7-flash",
    "openrouter": "z-ai/glm-4.7-flash",
    "vercel": "zai/glm-4.7-flash",
    "zhipuai": "glm-4.7-flash",
  },
  "glm-4.7-flashx": {
    "vercel": "zai/glm-4.7-flashx",
    "zhipuai": "glm-4.7-flashx",
  },
  "glm-5": {
    "amazon-bedrock": { id: "zai.glm-5", narrows: { context: 202752 } },
    "baseten": { id: "zai-org/GLM-5", narrows: { context: 202800 } },
    "deepinfra": { id: "zai-org/GLM-5", narrows: { context: 202752 } },
    "google-vertex": { id: "zai-org/glm-5-maas", endpoint: "google-vertex.chatMaas", narrows: { context: 202752 } },
    "huggingface": { id: "zai-org/GLM-5", narrows: { context: 202752 } },
    "nebius": { id: "zai-org/GLM-5", narrows: { context: 200000 } },
    "novita-ai": { id: "zai-org/glm-5", narrows: { context: 202800 } },
    "openrouter": "z-ai/glm-5",
    "togetherai": { id: "zai-org/GLM-5", narrows: { context: 202752 } },
    "vercel": { id: "zai/glm-5", narrows: { context: 202800 } },
    "zhipuai": "glm-5",
  },
  "glm-5.1": {
    "baseten": "zai-org/GLM-5.1",
    "deepinfra": "zai-org/GLM-5.1",
    "friendli": "zai-org/GLM-5.1",
    "huggingface": "zai-org/GLM-5.1",
    "novita-ai": "zai-org/glm-5.1",
    "openrouter": "z-ai/glm-5.1",
    "togetherai": "zai-org/GLM-5.1",
    "vercel": "zai/glm-5.1",
    "zhipuai": "glm-5.1",
  },
  "glm-5.2": {
    "alibaba": "glm-5.2",
    "baseten": "zai-org/GLM-5.2",
    "cloudflare-workers-ai": { id: "@cf/zai-org/glm-5.2", narrows: { context: 262144 } },
    "deepinfra": "zai-org/GLM-5.2",
    "friendli": "zai-org/GLM-5.2",
    "huggingface": { id: "zai-org/GLM-5.2", narrows: { context: 262144 } },
    "nebius": { id: "zai-org/GLM-5.2", narrows: { context: 432000 } },
    "novita-ai": "zai-org/glm-5.2",
    "nvidia": "z-ai/glm-5.2",
    "openrouter": "z-ai/glm-5.2",
    "scaleway": { id: "glm-5.2", narrows: { context: 256000 } },
    "siliconflow": "zai-org/GLM-5.2",
    "togetherai": { id: "zai-org/GLM-5.2", narrows: { context: 512000 } },
    "vercel": "zai/glm-5.2",
    "zhipuai": "glm-5.2",
  },
  "glm-5.3": {
    "baseten": "zai-org/GLM-5.3",
    "cloudflare-workers-ai": "@cf/zai-org/glm-5.3",
    "deepinfra": "zai-org/GLM-5.3",
    "friendli": "zai-org/GLM-5.3",
    "huggingface": "zai-org/GLM-5.3",
    "openrouter": "z-ai/glm-5.3",
    "togetherai": "zai-org/GLM-5.3",
    "vercel": "zai/glm-5.3",
    "zhipuai": "glm-5.3",
  },
  "glm-5.3-flash": {
    "baseten": { id: "zai-org/GLM-5.3-Flash", narrows: { drops: ["video", "pdf"] } },
    "cloudflare-workers-ai": { id: "@cf/zai-org/glm-5.3-flash", narrows: { drops: ["video", "pdf"] } },
    "deepinfra": "zai-org/GLM-5.3-Flash",
    "huggingface": { id: "zai-org/GLM-5.3-Flash", narrows: { drops: ["video", "pdf"] } },
    "openrouter": { id: "z-ai/glm-5.3-flash", narrows: { drops: ["pdf"] } },
    "togetherai": { id: "zai-org/GLM-5.3-Flash", narrows: { drops: ["pdf"] } },
    "vercel": { id: "zai/glm-5.3-flash", narrows: { drops: ["video", "pdf"] } },
    "zhipuai": "glm-5.3-flash",
  },
  "glm-5v-turbo": {
    "openrouter": { id: "z-ai/glm-5v-turbo", narrows: { drops: ["pdf"] } },
    "vercel": { id: "zai/glm-5v-turbo", narrows: { drops: ["video"] } },
    "zhipuai": "glm-5v-turbo",
  },
} as const satisfies AvailabilityMap;

export type ZhipuaiAvailability = typeof availability;
