// Generated by scripts/codegen.ts — DO NOT EDIT.
// Source: https://models.dev/api.json (committed snapshot: data/models-dev.json)
// Regenerate with `bun run codegen` (or `bun run codegen:refresh` to update the snapshot).

import type { ModelInfo, ProviderInfo } from "../core/catalog-types";

export const provider = {
  id: "agnes",
  name: "Agnes AI",
  env: ["AGNES_API_KEY"],
  doc: "https://agnes-ai.com/doc",
  api: "https://apihub.agnes-ai.com/v1",
} as const satisfies ProviderInfo;

export const models = {
  "agnes-2.0-flash": {
    id: "agnes-2.0-flash",
    name: "Agnes 2.0 Flash",
    attachment: true,
    reasoning: true,
    toolCall: true,
    structuredOutput: true,
    temperature: true,
    openWeights: false,
    releaseDate: "2026-05-25",
    lastUpdated: "2026-05-25",
    modalities: { input: ["text", "image"], output: ["text"] },
    limit: { context: 512000, output: 65536 },
    cost: { input: 0, output: 0 },
  },
  "agnes-2.5-flash": {
    id: "agnes-2.5-flash",
    name: "Agnes 2.5 Flash",
    attachment: true,
    reasoning: true,
    toolCall: true,
    structuredOutput: true,
    temperature: true,
    openWeights: false,
    releaseDate: "2026-07",
    lastUpdated: "2026-07",
    modalities: { input: ["text", "image"], output: ["text"] },
    limit: { context: 512000, output: 65536 },
    cost: { input: 0, output: 0 },
  },
  "agnes-2.5-pro-alpha": {
    id: "agnes-2.5-pro-alpha",
    name: "Agnes 2.5 Pro Alpha",
    attachment: true,
    reasoning: true,
    toolCall: true,
    structuredOutput: true,
    temperature: true,
    openWeights: true,
    releaseDate: "2026-07-24",
    lastUpdated: "2026-07-24",
    modalities: { input: ["text", "image"], output: ["text"] },
    limit: { context: 1000000, output: 65536 },
    cost: { input: 0.45, output: 0.9, cacheRead: 0.0038 },
  },
} as const satisfies Record<string, ModelInfo>;

export type AgnesModelId = keyof typeof models;
export type AgnesTextModelId = "agnes-2.0-flash" | "agnes-2.5-flash" | "agnes-2.5-pro-alpha";
export type AgnesImageModelId = never;
export type AgnesAudioModelId = never;
export type AgnesVideoModelId = never;
