// Generated by scripts/codegen.ts — DO NOT EDIT.
// Source: https://models.dev/api.json (committed snapshot: data/models-dev.json)
// Regenerate with `bun run codegen` (or `bun run codegen:refresh` to update the snapshot).

import type { ModelInfo, ProviderInfo } from "../core/catalog-types";

export const provider = {
  id: "ai-router",
  name: "AI-ROUTER",
  env: ["AI_ROUTER_API_KEY"],
  doc: "https://ai-router.dev/openai-compatible-api-gateway/",
  api: "https://api.ai-router.dev/v1",
} as const satisfies ProviderInfo;

export const models = {
  "gpt-5.4": {
    id: "gpt-5.4",
    name: "GPT-5.4",
    family: "gpt",
    attachment: true,
    reasoning: true,
    toolCall: true,
    structuredOutput: true,
    temperature: true,
    openWeights: false,
    knowledge: "2025-08-31",
    releaseDate: "2026-03-05",
    lastUpdated: "2026-03-05",
    modalities: { input: ["text", "image", "pdf"], output: ["text"] },
    limit: { context: 1050000, output: 128000, input: 922000 },
    cost: { input: 2.5, output: 15, cacheRead: 0.25 },
  },
  "gpt-5.5": {
    id: "gpt-5.5",
    name: "GPT-5.5",
    family: "gpt",
    attachment: true,
    reasoning: true,
    toolCall: true,
    structuredOutput: true,
    temperature: false,
    openWeights: false,
    knowledge: "2025-12-01",
    releaseDate: "2026-04-23",
    lastUpdated: "2026-04-23",
    modalities: { input: ["text", "image", "pdf"], output: ["text"] },
    limit: { context: 1050000, output: 128000, input: 922000 },
    cost: { input: 5, output: 30, cacheRead: 0.5 },
  },
  "gpt-5.6-luna": {
    id: "gpt-5.6-luna",
    name: "GPT-5.6 Luna",
    family: "gpt-luna",
    attachment: true,
    reasoning: true,
    toolCall: true,
    structuredOutput: true,
    temperature: false,
    openWeights: false,
    knowledge: "2026-02-16",
    releaseDate: "2026-07-09",
    lastUpdated: "2026-07-09",
    modalities: { input: ["text", "image", "pdf"], output: ["text"] },
    limit: { context: 1050000, output: 128000, input: 922000 },
    cost: { input: 1, output: 6, cacheRead: 0.1, cacheWrite: 1.25 },
  },
  "gpt-5.6-sol": {
    id: "gpt-5.6-sol",
    name: "GPT-5.6 Sol",
    family: "gpt-sol",
    attachment: true,
    reasoning: true,
    toolCall: true,
    structuredOutput: true,
    temperature: false,
    openWeights: false,
    knowledge: "2026-02-16",
    releaseDate: "2026-07-09",
    lastUpdated: "2026-07-09",
    modalities: { input: ["text", "image", "pdf"], output: ["text"] },
    limit: { context: 1050000, output: 128000, input: 922000 },
    cost: { input: 5, output: 30, cacheRead: 0.5, cacheWrite: 6.25 },
  },
  "gpt-5.6-terra": {
    id: "gpt-5.6-terra",
    name: "GPT-5.6 Terra",
    family: "gpt-terra",
    attachment: true,
    reasoning: true,
    toolCall: true,
    structuredOutput: true,
    temperature: false,
    openWeights: false,
    knowledge: "2026-02-16",
    releaseDate: "2026-07-09",
    lastUpdated: "2026-07-09",
    modalities: { input: ["text", "image", "pdf"], output: ["text"] },
    limit: { context: 1050000, output: 128000, input: 922000 },
    cost: { input: 2.5, output: 15, cacheRead: 0.25, cacheWrite: 3.125 },
  },
} as const satisfies Record<string, ModelInfo>;

export type AiRouterModelId = keyof typeof models;
export type AiRouterTextModelId = "gpt-5.4" | "gpt-5.5" | "gpt-5.6-luna" | "gpt-5.6-sol" | "gpt-5.6-terra";
export type AiRouterImageModelId = never;
export type AiRouterAudioModelId = never;
export type AiRouterVideoModelId = never;
