// Generated by scripts/codegen.ts — DO NOT EDIT.
// Source: https://models.dev/api.json (committed snapshot: data/models-dev.json)
// Regenerate with `bun run codegen` (or `bun run codegen:refresh` to update the snapshot).

import type { ModelInfo, ProviderInfo } from "../core/catalog-types";

export const provider = {
  id: "ainetcafe",
  name: "ainetcafe",
  env: ["AINETCAFE_API_KEY"],
  doc: "https://ainetcafe.com/k3/guides/",
  api: "https://microquickjs.com/v1",
} as const satisfies ProviderInfo;

export const models = {
  "Kimi-K3": {
    id: "Kimi-K3",
    name: "Kimi K3",
    family: "kimi-k3",
    attachment: true,
    reasoning: true,
    toolCall: true,
    structuredOutput: true,
    temperature: false,
    openWeights: true,
    releaseDate: "2026-07-16",
    lastUpdated: "2026-07-16",
    modalities: { input: ["text", "image"], output: ["text"] },
    limit: { context: 262144, output: 32768 },
    cost: { input: 2.1, output: 10.5, cacheRead: 0.3 },
  },
} as const satisfies Record<string, ModelInfo>;

export type AinetcafeModelId = keyof typeof models;
export type AinetcafeTextModelId = "Kimi-K3";
export type AinetcafeImageModelId = never;
export type AinetcafeAudioModelId = never;
export type AinetcafeVideoModelId = never;
