// Generated by scripts/codegen.ts — DO NOT EDIT.
// Source: https://models.dev/api.json (committed snapshot: data/models-dev.json)
// Regenerate with `bun run codegen` (or `bun run codegen:refresh` to update the snapshot).

import type { ModelInfo, ProviderInfo } from "../core/catalog-types";

export const provider = {
  id: "atomic-chat",
  name: "Atomic Chat",
  env: ["ATOMIC_CHAT_API_KEY"],
  doc: "https://atomic.chat",
  api: "http://127.0.0.1:1337/v1",
} as const satisfies ProviderInfo;

export const models = {
  "Meta-Llama-3_1-8B-Instruct-GGUF": {
    id: "Meta-Llama-3_1-8B-Instruct-GGUF",
    name: "Meta Llama 3.1 8B Instruct (GGUF)",
    family: "llama",
    attachment: false,
    reasoning: false,
    toolCall: true,
    temperature: true,
    openWeights: true,
    releaseDate: "2024-07-23",
    lastUpdated: "2024-07-23",
    modalities: { input: ["text"], output: ["text"] },
    limit: { context: 131072, output: 4096 },
    cost: { input: 0, output: 0 },
  },
  "Qwen3_5-9B-MLX-4bit": {
    id: "Qwen3_5-9B-MLX-4bit",
    name: "Qwen 3.5 9B (MLX 4-bit)",
    family: "qwen",
    attachment: true,
    reasoning: false,
    toolCall: true,
    temperature: true,
    openWeights: true,
    releaseDate: "2026-03-05",
    lastUpdated: "2026-04-04",
    modalities: { input: ["text", "image"], output: ["text"] },
    limit: { context: 32768, output: 8192 },
    cost: { input: 0, output: 0 },
  },
  "Qwen3_5-9B-Q4_K_M": {
    id: "Qwen3_5-9B-Q4_K_M",
    name: "Qwen 3.5 9B (Q4_K_M)",
    family: "qwen",
    attachment: true,
    reasoning: false,
    toolCall: true,
    temperature: true,
    openWeights: true,
    releaseDate: "2026-03-05",
    lastUpdated: "2026-04-04",
    modalities: { input: ["text", "image"], output: ["text"] },
    limit: { context: 32768, output: 8192 },
    cost: { input: 0, output: 0 },
  },
  "gemma-4-E4B-it-IQ4_XS": {
    id: "gemma-4-E4B-it-IQ4_XS",
    name: "Gemma 4 E4B Instruct (IQ4_XS)",
    family: "gemma",
    attachment: false,
    reasoning: false,
    toolCall: false,
    temperature: true,
    openWeights: true,
    releaseDate: "2026-04-02",
    lastUpdated: "2026-04-02",
    modalities: { input: ["text"], output: ["text"] },
    limit: { context: 32768, output: 8192 },
    cost: { input: 0, output: 0 },
  },
  "gemma-4-E4B-it-MLX-4bit": {
    id: "gemma-4-E4B-it-MLX-4bit",
    name: "Gemma 4 E4B Instruct (MLX 4-bit)",
    family: "gemma",
    attachment: false,
    reasoning: false,
    toolCall: false,
    temperature: true,
    openWeights: true,
    releaseDate: "2026-04-02",
    lastUpdated: "2026-04-02",
    modalities: { input: ["text"], output: ["text"] },
    limit: { context: 32768, output: 8192 },
    cost: { input: 0, output: 0 },
  },
} as const satisfies Record<string, ModelInfo>;

export type AtomicChatModelId = keyof typeof models;
export type AtomicChatTextModelId = "Meta-Llama-3_1-8B-Instruct-GGUF" | "Qwen3_5-9B-MLX-4bit" | "Qwen3_5-9B-Q4_K_M" | "gemma-4-E4B-it-IQ4_XS" | "gemma-4-E4B-it-MLX-4bit";
export type AtomicChatImageModelId = never;
export type AtomicChatAudioModelId = never;
export type AtomicChatVideoModelId = never;
