// Generated by scripts/codegen.ts — DO NOT EDIT.
// Source: https://models.dev/api.json (committed snapshot: data/models-dev.json)
// Regenerate with `bun run codegen` (or `bun run codegen:refresh` to update the snapshot).

import type { ModelInfo, ProviderInfo } from "../core/catalog-types";

export const provider = {
  id: "bailing",
  name: "Bailing",
  env: ["BAILING_API_TOKEN"],
  doc: "https://alipaytbox.yuque.com/sxs0ba/ling/intro",
  api: "https://api.tbox.cn/api/llm/v1/chat/completions",
} as const satisfies ProviderInfo;

export const models = {
  "Ling-1T": {
    id: "Ling-1T",
    name: "Ling-1T",
    family: "ling",
    attachment: false,
    reasoning: false,
    toolCall: true,
    temperature: true,
    openWeights: true,
    knowledge: "2024-06",
    releaseDate: "2025-10",
    lastUpdated: "2025-10",
    modalities: { input: ["text"], output: ["text"] },
    limit: { context: 128000, output: 32000 },
    cost: { input: 0.57, output: 2.29 },
  },
  "Ring-1T": {
    id: "Ring-1T",
    name: "Ring-1T",
    family: "ring",
    attachment: false,
    reasoning: true,
    toolCall: false,
    temperature: true,
    openWeights: true,
    knowledge: "2024-06",
    releaseDate: "2025-10",
    lastUpdated: "2025-10",
    modalities: { input: ["text"], output: ["text"] },
    limit: { context: 128000, output: 32000 },
    cost: { input: 0.57, output: 2.29 },
  },
} as const satisfies Record<string, ModelInfo>;

export type BailingModelId = keyof typeof models;
export type BailingTextModelId = "Ling-1T" | "Ring-1T";
export type BailingImageModelId = never;
export type BailingAudioModelId = never;
export type BailingVideoModelId = never;
