// Generated by scripts/codegen.ts — DO NOT EDIT.
// Source: https://models.dev/api.json (committed snapshot: data/models-dev.json)
// Regenerate with `bun run codegen` (or `bun run codegen:refresh` to update the snapshot).

import type { ModelInfo, ProviderInfo } from "../core/catalog-types";

export const provider = {
  id: "bee",
  name: "Bee by HEOSSI",
  env: ["BEE_API_KEY"],
  doc: "https://bee.heossi.com/docs/sdks",
  api: "https://api.bee.heossi.com/bee",
} as const satisfies ProviderInfo;

export const models = {
  "bee-brood": {
    id: "bee-brood",
    name: "Bee Brood 1.0",
    attachment: true,
    reasoning: true,
    toolCall: true,
    structuredOutput: false,
    temperature: true,
    openWeights: false,
    releaseDate: "2026-07-10",
    lastUpdated: "2026-09-28",
    modalities: { input: ["text", "image", "video"], output: ["text"] },
    limit: { context: 262144, output: 16384 },
    cost: { input: 0.6, output: 2.4, cacheRead: 0.06, cacheWrite: 0.72 },
  },
  "bee-buzz": {
    id: "bee-buzz",
    name: "Bee Buzz 1.0",
    attachment: true,
    reasoning: true,
    toolCall: true,
    structuredOutput: true,
    temperature: true,
    openWeights: false,
    releaseDate: "2026-07-10",
    lastUpdated: "2026-09-28",
    modalities: { input: ["text", "image", "video"], output: ["text"] },
    limit: { context: 262144, output: 24576 },
    cost: { input: 2.5, output: 10, cacheRead: 0.25, cacheWrite: 3 },
  },
  "bee-cell": {
    id: "bee-cell",
    name: "Bee Cell 1.0",
    attachment: true,
    reasoning: false,
    toolCall: true,
    structuredOutput: false,
    temperature: true,
    openWeights: false,
    releaseDate: "2026-07-10",
    lastUpdated: "2026-09-28",
    modalities: { input: ["text", "image"], output: ["text"] },
    limit: { context: 131072, output: 8192 },
    cost: { input: 0.3, output: 1.2, cacheRead: 0.03, cacheWrite: 0.36 },
  },
  "bee-comb": {
    id: "bee-comb",
    name: "Bee Comb 2.0",
    attachment: true,
    reasoning: true,
    toolCall: true,
    structuredOutput: true,
    temperature: true,
    openWeights: false,
    releaseDate: "2026-07-10",
    lastUpdated: "2026-09-28",
    modalities: { input: ["text", "image", "video"], output: ["text"] },
    limit: { context: 262144, output: 16384 },
    cost: { input: 1.25, output: 5, cacheRead: 0.125, cacheWrite: 1.5 },
  },
  "bee-hive": {
    id: "bee-hive",
    name: "Bee Hive 1.0",
    attachment: true,
    reasoning: true,
    toolCall: true,
    structuredOutput: true,
    temperature: true,
    openWeights: false,
    releaseDate: "2026-07-10",
    lastUpdated: "2026-09-28",
    modalities: { input: ["text", "image", "video"], output: ["text"] },
    limit: { context: 262144, output: 32768 },
    cost: { input: 5, output: 20, cacheRead: 0.5, cacheWrite: 6 },
  },
  "bee-swarm": {
    id: "bee-swarm",
    name: "Bee Swarm 1.0",
    attachment: true,
    reasoning: true,
    toolCall: false,
    structuredOutput: false,
    openWeights: false,
    releaseDate: "2026-07-10",
    lastUpdated: "2026-09-28",
    modalities: { input: ["text", "image"], output: ["text"] },
    limit: { context: 1000000, output: 64000 },
    cost: { input: 25, output: 150, cacheRead: 2.5, cacheWrite: 30 },
  },
} as const satisfies Record<string, ModelInfo>;

export type BeeModelId = keyof typeof models;
export type BeeTextModelId = "bee-brood" | "bee-buzz" | "bee-cell" | "bee-comb" | "bee-hive" | "bee-swarm";
export type BeeImageModelId = never;
export type BeeAudioModelId = never;
export type BeeVideoModelId = never;
