// Generated by scripts/codegen.ts — DO NOT EDIT.
// Source: https://models.dev/api.json (committed snapshot: data/models-dev.json)
// Regenerate with `bun run codegen` (or `bun run codegen:refresh` to update the snapshot).

import type { ModelInfo, ProviderInfo } from "../core/catalog-types";

export const provider = {
  id: "blueclaw",
  name: "Blue Claw",
  env: ["BLUECLAW_API_KEY"],
  doc: "https://blueclaw.network",
  api: "https://openai.blueclaw.network/v1",
} as const satisfies ProviderInfo;

export const models = {
  "Qwen3.8-27B": {
    id: "Qwen3.8-27B",
    name: "Qwen3.8 27B",
    family: "qwen",
    attachment: false,
    reasoning: true,
    toolCall: true,
    structuredOutput: true,
    temperature: true,
    openWeights: true,
    releaseDate: "2026-08-14",
    lastUpdated: "2026-08-14",
    status: "beta",
    modalities: { input: ["text"], output: ["text"] },
    limit: { context: 131072, output: 32768 },
  },
} as const satisfies Record<string, ModelInfo>;

export type BlueclawModelId = keyof typeof models;
export type BlueclawTextModelId = "Qwen3.8-27B";
export type BlueclawImageModelId = never;
export type BlueclawAudioModelId = never;
export type BlueclawVideoModelId = never;
