// Generated by scripts/codegen.ts — DO NOT EDIT.
// Source: https://models.dev/api.json (committed snapshot: data/models-dev.json)
// Regenerate with `bun run codegen` (or `bun run codegen:refresh` to update the snapshot).

import type { ModelInfo, ProviderInfo } from "../core/catalog-types";

export const provider = {
  id: "bothub",
  name: "Bothub",
  env: ["BOTHUB_API_KEY"],
  doc: "https://bothub.ru/models",
  api: "https://openai.bothub.ru/v1",
} as const satisfies ProviderInfo;

export const models = {
  "gemma-4-31b-it:free": {
    id: "gemma-4-31b-it:free",
    name: "Gemma 4 31B IT (free)",
    family: "gemma",
    attachment: true,
    reasoning: true,
    toolCall: true,
    structuredOutput: true,
    temperature: true,
    openWeights: true,
    releaseDate: "2026-04-02",
    lastUpdated: "2026-04-02",
    modalities: { input: ["text", "image"], output: ["text"] },
    limit: { context: 262144, output: 32768 },
    cost: { input: 0, output: 0 },
  },
  "nemotron-3-ultra-550b-a55b:free": {
    id: "nemotron-3-ultra-550b-a55b:free",
    name: "Nemotron 3 Ultra (free)",
    family: "nemotron",
    attachment: false,
    reasoning: true,
    toolCall: true,
    temperature: true,
    openWeights: true,
    releaseDate: "2026-06-04",
    lastUpdated: "2026-06-04",
    modalities: { input: ["text"], output: ["text"] },
    limit: { context: 1000000, output: 128000 },
    cost: { input: 0, output: 0 },
  },
} as const satisfies Record<string, ModelInfo>;

export type BothubModelId = keyof typeof models;
export type BothubTextModelId = "gemma-4-31b-it:free" | "nemotron-3-ultra-550b-a55b:free";
export type BothubImageModelId = never;
export type BothubAudioModelId = never;
export type BothubVideoModelId = never;
