// Generated by scripts/codegen.ts — DO NOT EDIT.
// Source: https://models.dev/api.json (committed snapshot: data/models-dev.json)
// Regenerate with `bun run codegen` (or `bun run codegen:refresh` to update the snapshot).

import type { ModelInfo, ProviderInfo } from "../core/catalog-types";

export const provider = {
  id: "coralbricks",
  name: "CoralBricks",
  env: ["CORAL_API_KEY"],
  doc: "https://www.coralbricks.ai/docs",
  api: "https://inference.coralbricks.ai/v1",
} as const satisfies ProviderInfo;

export const models = {
  "glm-5.2-fp4": {
    id: "glm-5.2-fp4",
    name: "GLM 5.2 FP4",
    family: "glm",
    attachment: false,
    reasoning: true,
    toolCall: true,
    structuredOutput: true,
    temperature: true,
    openWeights: true,
    releaseDate: "2026-06-13",
    lastUpdated: "2026-06-13",
    modalities: { input: ["text"], output: ["text"] },
    limit: { context: 1048576, output: 131072 },
    cost: { input: 1.12, output: 4.4, cacheRead: 0 },
  },
  "gpt-oss-120b": {
    id: "gpt-oss-120b",
    name: "GPT OSS 120B",
    family: "gpt-oss",
    attachment: false,
    reasoning: true,
    toolCall: true,
    structuredOutput: true,
    temperature: true,
    openWeights: true,
    releaseDate: "2025-08-05",
    lastUpdated: "2025-08-05",
    modalities: { input: ["text"], output: ["text"] },
    limit: { context: 131072, output: 32768 },
    cost: { input: 0.12, output: 0.6, cacheRead: 0 },
  },
  "kimi-k3": {
    id: "kimi-k3",
    name: "Kimi K3",
    family: "kimi-k3",
    attachment: true,
    reasoning: true,
    toolCall: true,
    structuredOutput: true,
    temperature: false,
    openWeights: true,
    releaseDate: "2026-07-16",
    lastUpdated: "2026-07-16",
    modalities: { input: ["text", "image", "video"], output: ["text"] },
    limit: { context: 1048576, output: 131072 },
    cost: { input: 3, output: 15, cacheRead: 0 },
  },
} as const satisfies Record<string, ModelInfo>;

export type CoralbricksModelId = keyof typeof models;
export type CoralbricksTextModelId = "glm-5.2-fp4" | "gpt-oss-120b" | "kimi-k3";
export type CoralbricksImageModelId = never;
export type CoralbricksAudioModelId = never;
export type CoralbricksVideoModelId = never;
