// Generated by scripts/codegen.ts — DO NOT EDIT.
// Source: https://models.dev/api.json (committed snapshot: data/models-dev.json)
// Regenerate with `bun run codegen` (or `bun run codegen:refresh` to update the snapshot).

import type { ModelInfo, ProviderInfo } from "../core/catalog-types";

export const provider = {
  id: "coralbricks",
  name: "CoralBricks",
  env: ["CORAL_API_KEY"],
  doc: "https://www.coralbricks.ai/docs",
  api: "https://inference.coralbricks.ai/v1",
} as const satisfies ProviderInfo;

export const models = {
  "deepseek-v4.1-flash-fast-fp4": {
    id: "deepseek-v4.1-flash-fast-fp4",
    name: "DeepSeek V4.1 Flash FP4",
    family: "deepseek-flash",
    attachment: true,
    reasoning: true,
    toolCall: true,
    structuredOutput: true,
    temperature: true,
    openWeights: true,
    knowledge: "2025-05",
    releaseDate: "2026-09-10",
    lastUpdated: "2026-09-10",
    modalities: { input: ["text", "image"], output: ["text"] },
    limit: { context: 1048576, output: 131072 },
    cost: { input: 0.3, output: 1.2, cacheRead: 0, cacheWrite: 0.09 },
  },
  "glm-5.3-flash-fp4": {
    id: "glm-5.3-flash-fp4",
    name: "GLM 5.3 Flash FP4",
    family: "glm-flash",
    attachment: true,
    reasoning: true,
    toolCall: true,
    structuredOutput: true,
    temperature: true,
    openWeights: true,
    releaseDate: "2026-08-26",
    lastUpdated: "2026-08-26",
    modalities: { input: ["text", "image", "video"], output: ["text"] },
    limit: { context: 1048576, output: 131072 },
    cost: { input: 0.15, output: 0.5, cacheRead: 0, cacheWrite: 0.23 },
  },
  "glm-5.3-fp4": {
    id: "glm-5.3-fp4",
    name: "GLM 5.3 FP4",
    family: "glm",
    attachment: false,
    reasoning: true,
    toolCall: true,
    structuredOutput: true,
    temperature: true,
    openWeights: true,
    releaseDate: "2026-08-14",
    lastUpdated: "2026-08-14",
    modalities: { input: ["text"], output: ["text"] },
    limit: { context: 1048576, output: 131072 },
    cost: { input: 1.12, output: 4.4, cacheRead: 0, cacheWrite: 1.68 },
  },
} as const satisfies Record<string, ModelInfo>;

export type CoralbricksModelId = keyof typeof models;
export type CoralbricksTextModelId = "deepseek-v4.1-flash-fast-fp4" | "glm-5.3-flash-fp4" | "glm-5.3-fp4";
export type CoralbricksImageModelId = never;
export type CoralbricksAudioModelId = never;
export type CoralbricksVideoModelId = never;
