// Generated by scripts/codegen.ts — DO NOT EDIT.
// Source: https://models.dev/api.json (committed snapshot: data/models-dev.json)
// Regenerate with `bun run codegen` (or `bun run codegen:refresh` to update the snapshot).

import type { ModelInfo, ProviderInfo } from "../core/catalog-types";

export const provider = {
  id: "dinference",
  name: "DInference",
  env: ["DINFERENCE_API_KEY"],
  doc: "https://dinference.com",
  api: "https://api.dinference.com/v1",
} as const satisfies ProviderInfo;

export const models = {
  "glm-4.7": {
    id: "glm-4.7",
    name: "GLM-4.7",
    family: "glm",
    attachment: false,
    reasoning: true,
    toolCall: true,
    temperature: true,
    openWeights: true,
    knowledge: "2025-04",
    releaseDate: "2025-12-22",
    lastUpdated: "2025-12-22",
    modalities: { input: ["text"], output: ["text"] },
    limit: { context: 200000, output: 128000 },
    cost: { input: 0.45, output: 1.65 },
  },
  "glm-5": {
    id: "glm-5",
    name: "GLM-5",
    family: "glm",
    attachment: false,
    reasoning: true,
    toolCall: true,
    temperature: true,
    openWeights: true,
    releaseDate: "2026-02-12",
    lastUpdated: "2026-02-12",
    modalities: { input: ["text"], output: ["text"] },
    limit: { context: 200000, output: 128000 },
    cost: { input: 0.75, output: 2.4 },
  },
  "glm-5.1": {
    id: "glm-5.1",
    name: "GLM-5.1",
    family: "glm",
    attachment: false,
    reasoning: true,
    toolCall: true,
    structuredOutput: true,
    temperature: true,
    openWeights: true,
    releaseDate: "2026-04-07",
    lastUpdated: "2026-04-07",
    modalities: { input: ["text"], output: ["text"] },
    limit: { context: 200000, output: 128000 },
    cost: { input: 1.25, output: 3.89 },
  },
  "glm-5.2": {
    id: "glm-5.2",
    name: "GLM-5.2",
    family: "glm",
    attachment: false,
    reasoning: true,
    toolCall: true,
    structuredOutput: true,
    temperature: true,
    openWeights: true,
    releaseDate: "2026-06-13",
    lastUpdated: "2026-06-13",
    modalities: { input: ["text"], output: ["text"] },
    limit: { context: 1000000, output: 128000 },
    cost: { input: 1.25, output: 3.89 },
  },
  "gpt-oss-120b": {
    id: "gpt-oss-120b",
    name: "GPT OSS 120B",
    attachment: false,
    reasoning: false,
    toolCall: true,
    temperature: true,
    openWeights: true,
    releaseDate: "2025-08",
    lastUpdated: "2025-08",
    modalities: { input: ["text"], output: ["text"] },
    limit: { context: 131072, output: 32768 },
    cost: { input: 0.0675, output: 0.27 },
  },
  "minimax-m2.5": {
    id: "minimax-m2.5",
    name: "MiniMax-M2.5",
    family: "minimax",
    attachment: false,
    reasoning: true,
    toolCall: true,
    temperature: true,
    openWeights: true,
    releaseDate: "2026-02-12",
    lastUpdated: "2026-02-12",
    modalities: { input: ["text"], output: ["text"] },
    limit: { context: 200000, output: 32000 },
    cost: { input: 0.22, output: 0.88 },
  },
} as const satisfies Record<string, ModelInfo>;

export type DinferenceModelId = keyof typeof models;
export type DinferenceTextModelId = "glm-4.7" | "glm-5" | "glm-5.1" | "glm-5.2" | "gpt-oss-120b" | "minimax-m2.5";
export type DinferenceImageModelId = never;
export type DinferenceAudioModelId = never;
export type DinferenceVideoModelId = never;
