// Generated by scripts/codegen.ts — DO NOT EDIT.
// Source: https://models.dev/api.json (committed snapshot: data/models-dev.json)
// Regenerate with `bun run codegen` (or `bun run codegen:refresh` to update the snapshot).

import type { ModelInfo, ProviderInfo } from "../core/catalog-types";

export const provider = {
  id: "drun",
  name: "D.Run (China)",
  env: ["DRUN_API_KEY"],
  doc: "https://www.d.run",
  api: "https://chat.d.run/v1",
} as const satisfies ProviderInfo;

export const models = {
  "public/deepseek-r1": {
    id: "public/deepseek-r1",
    name: "DeepSeek R1",
    family: "deepseek-thinking",
    attachment: false,
    reasoning: true,
    toolCall: true,
    temperature: true,
    openWeights: true,
    knowledge: "2024-12",
    releaseDate: "2025-01-20",
    lastUpdated: "2025-01-20",
    modalities: { input: ["text"], output: ["text"] },
    limit: { context: 131072, output: 32000 },
    cost: { input: 0.55, output: 2.2 },
  },
  "public/deepseek-v3": {
    id: "public/deepseek-v3",
    name: "DeepSeek V3",
    family: "deepseek",
    attachment: false,
    reasoning: false,
    toolCall: true,
    temperature: true,
    openWeights: true,
    knowledge: "2024-07",
    releaseDate: "2024-12-26",
    lastUpdated: "2024-12-26",
    modalities: { input: ["text"], output: ["text"] },
    limit: { context: 131072, output: 8192 },
    cost: { input: 0.28, output: 1.1 },
  },
  "public/minimax-m25": {
    id: "public/minimax-m25",
    name: "MiniMax M2.5",
    family: "minimax",
    attachment: false,
    reasoning: true,
    toolCall: true,
    temperature: true,
    openWeights: false,
    releaseDate: "2025-03-01",
    lastUpdated: "2025-03-01",
    modalities: { input: ["text"], output: ["text"] },
    limit: { context: 204800, output: 131072 },
    cost: { input: 0.29, output: 1.16 },
  },
} as const satisfies Record<string, ModelInfo>;

export type DrunModelId = keyof typeof models;
export type DrunTextModelId = "public/deepseek-r1" | "public/deepseek-v3" | "public/minimax-m25";
export type DrunImageModelId = never;
export type DrunAudioModelId = never;
export type DrunVideoModelId = never;
