// Generated by scripts/codegen.ts — DO NOT EDIT.
// Source: https://models.dev/api.json (committed snapshot: data/models-dev.json)
// Regenerate with `bun run codegen` (or `bun run codegen:refresh` to update the snapshot).

import type { ModelInfo, ProviderInfo } from "../core/catalog-types";
import { catalogTyped } from "./typed.gen";

export interface ProviderCatalog {
  provider: ProviderInfo;
  models: Record<string, ModelInfo>;
}

export type ProviderId =
  | "302ai"
  | "abacus"
  | "abliteration-ai"
  | "ai-router"
  | "aiand"
  | "aihubmix"
  | "aki-io"
  | "alibaba"
  | "alibaba-cn"
  | "alibaba-coding-plan"
  | "alibaba-coding-plan-cn"
  | "alibaba-token-plan"
  | "alibaba-token-plan-cn"
  | "amazon-bedrock"
  | "ambient"
  | "anthropic"
  | "anyapi"
  | "atomic-chat"
  | "auriko"
  | "azure"
  | "azure-cognitive-services"
  | "bailing"
  | "baseten"
  | "berget"
  | "blueclaw"
  | "cerebras"
  | "chutes"
  | "clarifai"
  | "claudinio"
  | "cline-pass"
  | "cloudferro-sherlock"
  | "cloudflare-ai-gateway"
  | "cloudflare-workers-ai"
  | "cohere"
  | "coralbricks"
  | "cortecs"
  | "crof"
  | "crossmodel"
  | "daoxe"
  | "databricks"
  | "deepinfra"
  | "deepseek"
  | "digitalocean"
  | "dinference"
  | "drun"
  | "ebcloud"
  | "edenai"
  | "empiriolabs"
  | "evroc"
  | "fastrouter"
  | "fireworks-ai"
  | "freemodel"
  | "friendli"
  | "frogbot"
  | "github-copilot"
  | "gitlab"
  | "gmicloud"
  | "google"
  | "google-vertex"
  | "google-vertex-anthropic"
  | "greenpt"
  | "groq"
  | "helicone"
  | "hetzner"
  | "hpc-ai"
  | "huggingface"
  | "hyper"
  | "iflowcn"
  | "impossibl"
  | "inception"
  | "inceptron"
  | "inference"
  | "inferx"
  | "infomaniak"
  | "io-net"
  | "jiekou"
  | "kenari"
  | "kilo"
  | "kimi-for-coding"
  | "kuae-cloud-coding-plan"
  | "lilac"
  | "llama"
  | "llmgateway"
  | "llmtr"
  | "lmstudio"
  | "longcat"
  | "lucidquery"
  | "lynkr"
  | "meganova"
  | "merge-gateway"
  | "meta"
  | "minimax"
  | "minimax-cn"
  | "minimax-cn-coding-plan"
  | "minimax-coding-plan"
  | "mistral"
  | "mixlayer"
  | "moark"
  | "modal"
  | "model-oracle-ai"
  | "modelis"
  | "modelscope"
  | "moonshotai"
  | "moonshotai-cn"
  | "morph"
  | "nano-gpt"
  | "nearai"
  | "nebius"
  | "neon"
  | "neuralwatt"
  | "nova"
  | "novita-ai"
  | "nvidia"
  | "ofox"
  | "ollama-cloud"
  | "openai"
  | "opencode"
  | "opencode-go"
  | "openrouter"
  | "orcarouter"
  | "ovhcloud"
  | "perplexity"
  | "perplexity-agent"
  | "pioneer"
  | "poe"
  | "poolside"
  | "privatemode-ai"
  | "qihang-ai"
  | "qiniu-ai"
  | "qvac"
  | "regolo-ai"
  | "requesty"
  | "routing-run"
  | "sakana"
  | "salad-cloud"
  | "sap-ai-core"
  | "sarvam"
  | "scaleway"
  | "scx"
  | "siliconflow"
  | "siliconflow-cn"
  | "snowflake-cortex"
  | "stackit"
  | "stepfun"
  | "stepfun-ai"
  | "stepfun-ai-step-plan"
  | "stepfun-step-plan"
  | "subconscious"
  | "submodel"
  | "synthetic"
  | "tencent-coding-plan"
  | "tencent-token-plan"
  | "tencent-tokenhub"
  | "tensorx"
  | "the-grid-ai"
  | "thinkingmachines"
  | "tinfoil"
  | "togetherai"
  | "trustedrouter"
  | "umans-ai"
  | "umans-ai-coding-plan"
  | "unorouter"
  | "upstage"
  | "v0"
  | "venice"
  | "vercel"
  | "vivgrid"
  | "vultr"
  | "wafer.ai"
  | "wandb"
  | "watsonx"
  | "xai"
  | "xiaomi"
  | "xiaomi-token-plan-ams"
  | "xiaomi-token-plan-cn"
  | "xiaomi-token-plan-sgp"
  | "xpersona"
  | "zai"
  | "zai-coding-plan"
  | "zeldoc"
  | "zenifra"
  | "zenmux"
  | "zhipuai"
  | "zhipuai-coding-plan";

/**
 * The full registry, deliberately widened to ModelInfo (no literal types).
 *
 * The widening is a BUNDLE decision, not a taste one, and it is the reason
 * `unmodel/catalog/typed` exists next to this entry. The annotation erases all
 * 184 `.gen` namespaces from this module's declaration —
 * `dist/catalog/index.d.ts` imports nothing but `catalog-types` and stays a
 * few KiB. Dropping it in favour of `satisfies` pulls every generated
 * namespace into the bundled declaration and takes that file to ~3.6 MB, which
 * every downstream project that touches `unmodel/catalog` then pays — including
 * one that only wanted the `ProviderId` type. docs/decisions.md §3 already
 * settled this shape for `unmodel/chat`: the cheap path has to be the only
 * path, and the heavy artefact gets its own specifier.
 *
 * So: this export is the cheap one, `unmodel/catalog/typed` is the same object
 * with its literals intact, and provider subpaths with validators (e.g.
 * `unmodel/openai`) re-export their own catalog slice for the 71 providers
 * that have one. Both entries are pinned in test/bundle-budget.test.ts.
 */
export const catalog: Record<ProviderId, ProviderCatalog> = catalogTyped;

export function getProvider(providerId: ProviderId | (string & {})): ProviderCatalog | undefined {
  // Object.hasOwn: ids like "constructor" must not resolve to inherited
  // Object.prototype members.
  return Object.hasOwn(catalog, providerId)
    ? (catalog as Record<string, ProviderCatalog>)[providerId]
    : undefined;
}

export function getModel(
  providerId: ProviderId | (string & {}),
  modelId: string,
): ModelInfo | undefined {
  const models = getProvider(providerId)?.models;
  return models !== undefined && Object.hasOwn(models, modelId) ? models[modelId] : undefined;
}
