// Generated by scripts/codegen.ts — DO NOT EDIT.
// Source: https://models.dev/api.json (committed snapshot: data/models-dev.json)
// Regenerate with `bun run codegen` (or `bun run codegen:refresh` to update the snapshot).

import type { ModelInfo, ProviderInfo } from "../core/catalog-types";

export const provider = {
  id: "kimi-for-coding",
  name: "Kimi For Coding",
  env: ["KIMI_API_KEY"],
  doc: "https://www.kimi.com/code/docs/en/kimi-code/models.html",
  api: "https://api.kimi.com/coding/v1",
} as const satisfies ProviderInfo;

export const models = {
  "k3": {
    id: "k3",
    name: "Kimi K3",
    family: "kimi-k3",
    attachment: true,
    reasoning: true,
    toolCall: true,
    structuredOutput: true,
    temperature: false,
    openWeights: true,
    releaseDate: "2026-07-16",
    lastUpdated: "2026-07-16",
    modalities: { input: ["text", "image", "video"], output: ["text"] },
    limit: { context: 1048576, output: 131072 },
    cost: { input: 0, output: 0, cacheRead: 0, cacheWrite: 0 },
  },
  "k3-256k": {
    id: "k3-256k",
    name: "Kimi K3-256K",
    family: "kimi-k3",
    attachment: true,
    reasoning: true,
    toolCall: true,
    structuredOutput: true,
    temperature: false,
    openWeights: true,
    releaseDate: "2026-07-16",
    lastUpdated: "2026-07-16",
    modalities: { input: ["text", "image"], output: ["text"] },
    limit: { context: 262144, output: 131072 },
    cost: { input: 0, output: 0, cacheRead: 0, cacheWrite: 0 },
  },
  "kimi-for-coding": {
    id: "kimi-for-coding",
    name: "Kimi K2.7 Code",
    family: "kimi-k2",
    attachment: true,
    reasoning: true,
    toolCall: true,
    structuredOutput: true,
    temperature: false,
    openWeights: true,
    knowledge: "2025-01",
    releaseDate: "2026-06-12",
    lastUpdated: "2026-06-12",
    modalities: { input: ["text", "image", "video"], output: ["text"] },
    limit: { context: 262144, output: 32768 },
    cost: { input: 0, output: 0, cacheRead: 0, cacheWrite: 0 },
  },
  "kimi-for-coding-highspeed": {
    id: "kimi-for-coding-highspeed",
    name: "Kimi For Coding HighSpeed",
    family: "kimi-k2",
    attachment: true,
    reasoning: true,
    toolCall: true,
    structuredOutput: true,
    temperature: false,
    openWeights: true,
    knowledge: "2025-01",
    releaseDate: "2026-06-12",
    lastUpdated: "2026-06-12",
    modalities: { input: ["text", "image", "video"], output: ["text"] },
    limit: { context: 262144, output: 32768 },
    cost: { input: 0, output: 0, cacheRead: 0, cacheWrite: 0 },
  },
} as const satisfies Record<string, ModelInfo>;

export type KimiForCodingModelId = keyof typeof models;
export type KimiForCodingTextModelId = "k3" | "k3-256k" | "kimi-for-coding" | "kimi-for-coding-highspeed";
export type KimiForCodingImageModelId = never;
export type KimiForCodingAudioModelId = never;
export type KimiForCodingVideoModelId = never;
