// Generated by scripts/codegen.ts — DO NOT EDIT.
// Source: https://models.dev/api.json (committed snapshot: data/models-dev.json)
// Regenerate with `bun run codegen` (or `bun run codegen:refresh` to update the snapshot).

import type { ModelInfo, ProviderInfo } from "../core/catalog-types";

export const provider = {
  id: "kosmik",
  name: "Kosmik Compute",
  env: ["KOSMIK_API_KEY"],
  doc: "https://api.koscompute.com/docs/",
  api: "https://api.koscompute.com/v1",
} as const satisfies ProviderInfo;

export const models = {
  "qwen/qwen3.8-27b": {
    id: "qwen/qwen3.8-27b",
    name: "Qwen3.8 27B",
    family: "qwen",
    attachment: true,
    reasoning: true,
    toolCall: true,
    structuredOutput: true,
    temperature: true,
    openWeights: true,
    releaseDate: "2026-08-14",
    lastUpdated: "2026-08-14",
    modalities: { input: ["text", "image"], output: ["text"] },
    limit: { context: 262144, output: 32768 },
    cost: { input: 0.35, output: 2.2, cacheRead: 0.09 },
  },
} as const satisfies Record<string, ModelInfo>;

export type KosmikModelId = keyof typeof models;
export type KosmikTextModelId = "qwen/qwen3.8-27b";
export type KosmikImageModelId = never;
export type KosmikAudioModelId = never;
export type KosmikVideoModelId = never;
