// Generated by scripts/codegen.ts — DO NOT EDIT.
// Source: https://models.dev/api.json (committed snapshot: data/models-dev.json)
// Regenerate with `bun run codegen` (or `bun run codegen:refresh` to update the snapshot).

import type { ModelInfo, ProviderInfo } from "../core/catalog-types";

export const provider = {
  id: "lilac",
  name: "Lilac",
  env: ["LILAC_API_KEY"],
  doc: "https://docs.getlilac.com/inference/models",
  api: "https://api.getlilac.com/v1",
} as const satisfies ProviderInfo;

export const models = {
  "google/gemma-4-31b-it": {
    id: "google/gemma-4-31b-it",
    name: "Gemma 4 31B IT",
    family: "gemma",
    attachment: true,
    reasoning: true,
    toolCall: true,
    structuredOutput: true,
    temperature: true,
    openWeights: true,
    knowledge: "2025-01",
    releaseDate: "2026-04-02",
    lastUpdated: "2026-04-02",
    modalities: { input: ["text", "image", "video"], output: ["text"] },
    limit: { context: 262100, output: 262100 },
    cost: { input: 0.11, output: 0.35 },
  },
  "minimaxai/minimax-m3": {
    id: "minimaxai/minimax-m3",
    name: "MiniMax M3",
    family: "minimax-m3",
    attachment: true,
    reasoning: true,
    toolCall: true,
    structuredOutput: true,
    temperature: true,
    openWeights: true,
    releaseDate: "2026-06-01",
    lastUpdated: "2026-06-01",
    modalities: { input: ["text", "image", "video"], output: ["text"] },
    limit: { context: 1048576, output: 1048576 },
    cost: { input: 0.28, output: 1.1, cacheRead: 0.05 },
  },
  "moonshotai/kimi-k2.6": {
    id: "moonshotai/kimi-k2.6",
    name: "Kimi K2.6",
    family: "kimi-k2",
    attachment: true,
    reasoning: true,
    toolCall: true,
    structuredOutput: true,
    temperature: true,
    openWeights: true,
    knowledge: "2025-01",
    releaseDate: "2026-04-21",
    lastUpdated: "2026-04-21",
    modalities: { input: ["text", "image"], output: ["text"] },
    limit: { context: 262144, output: 262144 },
    cost: { input: 0.7, output: 3.5, cacheRead: 0.2 },
  },
  "zai-org/glm-5.2": {
    id: "zai-org/glm-5.2",
    name: "GLM 5.2",
    family: "glm",
    attachment: false,
    reasoning: true,
    toolCall: true,
    structuredOutput: true,
    temperature: true,
    openWeights: true,
    releaseDate: "2026-06-13",
    lastUpdated: "2026-06-13",
    modalities: { input: ["text"], output: ["text"] },
    limit: { context: 524288, output: 524288 },
    cost: { input: 0.9, output: 3, cacheRead: 0.27 },
  },
} as const satisfies Record<string, ModelInfo>;

export type LilacModelId = keyof typeof models;
export type LilacTextModelId = "google/gemma-4-31b-it" | "minimaxai/minimax-m3" | "moonshotai/kimi-k2.6" | "zai-org/glm-5.2";
export type LilacImageModelId = never;
export type LilacAudioModelId = never;
export type LilacVideoModelId = never;
