// Generated by scripts/codegen.ts — DO NOT EDIT.
// Source: https://models.dev/api.json (committed snapshot: data/models-dev.json)
// Regenerate with `bun run codegen` (or `bun run codegen:refresh` to update the snapshot).

import type { ModelInfo, ProviderInfo } from "../core/catalog-types";

export const provider = {
  id: "llmtr",
  name: "LLMTR",
  env: ["LLMTR_API_KEY"],
  doc: "https://llmtr.com/docs",
  api: "https://llmtr.com/v1",
} as const satisfies ProviderInfo;

export const models = {
  "gemma-4": {
    id: "gemma-4",
    name: "Gemma 4",
    attachment: false,
    reasoning: false,
    toolCall: false,
    temperature: true,
    openWeights: true,
    releaseDate: "2026-04-22",
    lastUpdated: "2026-04-22",
    modalities: { input: ["text"], output: ["text"] },
    limit: { context: 32768, output: 8192 },
    cost: { input: 5, output: 10 },
  },
  "magibu-11b-v8": {
    id: "magibu-11b-v8",
    name: "Magibu 11B v8",
    attachment: false,
    reasoning: false,
    toolCall: false,
    temperature: true,
    openWeights: false,
    releaseDate: "2026-06-05",
    lastUpdated: "2026-06-05",
    modalities: { input: ["text"], output: ["text"] },
    limit: { context: 8192, output: 4096 },
    cost: { input: 0, output: 0 },
  },
  "medgemma-4b": {
    id: "medgemma-4b",
    name: "MedGemma 4B",
    attachment: true,
    reasoning: false,
    toolCall: false,
    temperature: true,
    openWeights: true,
    releaseDate: "2026-04-26",
    lastUpdated: "2026-04-26",
    modalities: { input: ["text", "image"], output: ["text"] },
    limit: { context: 8192, output: 4096 },
    cost: { input: 3, output: 5 },
  },
  "qwen3-6-35b": {
    id: "qwen3-6-35b",
    name: "Qwen3.6 35B-A3B",
    family: "qwen",
    attachment: true,
    reasoning: true,
    toolCall: true,
    structuredOutput: true,
    temperature: true,
    openWeights: true,
    releaseDate: "2026-04-17",
    lastUpdated: "2026-04-17",
    modalities: { input: ["text", "image", "video", "audio"], output: ["text"] },
    limit: { context: 16384, output: 65536 },
    cost: { input: 5, output: 10 },
  },
  "sincap": {
    id: "sincap",
    name: "Sincap",
    attachment: false,
    reasoning: false,
    toolCall: false,
    temperature: true,
    openWeights: false,
    releaseDate: "2026-05-05",
    lastUpdated: "2026-05-05",
    modalities: { input: ["text"], output: ["text"] },
    limit: { context: 128000, output: 8192 },
    cost: { input: 0, output: 0 },
  },
  "trendyol-7b": {
    id: "trendyol-7b",
    name: "Trendyol 7B",
    family: "qwen",
    attachment: false,
    reasoning: false,
    toolCall: false,
    temperature: true,
    openWeights: true,
    releaseDate: "2026-06-06",
    lastUpdated: "2026-06-06",
    modalities: { input: ["text"], output: ["text"] },
    limit: { context: 32768, output: 8192 },
    cost: { input: 0, output: 0 },
  },
} as const satisfies Record<string, ModelInfo>;

export type LlmtrModelId = keyof typeof models;
export type LlmtrTextModelId = "gemma-4" | "magibu-11b-v8" | "medgemma-4b" | "qwen3-6-35b" | "sincap" | "trendyol-7b";
export type LlmtrImageModelId = never;
export type LlmtrAudioModelId = never;
export type LlmtrVideoModelId = never;
