// Generated by scripts/codegen.ts — DO NOT EDIT.
// Source: https://models.dev/api.json (committed snapshot: data/models-dev.json)
// Regenerate with `bun run codegen` (or `bun run codegen:refresh` to update the snapshot).

import type { ModelInfo, ProviderInfo } from "../core/catalog-types";

export const provider = {
  id: "lmstudio",
  name: "LMStudio",
  env: ["LMSTUDIO_API_KEY"],
  doc: "https://lmstudio.ai/models",
  api: "http://127.0.0.1:1234/v1",
} as const satisfies ProviderInfo;

export const models = {
  "openai/gpt-oss-20b": {
    id: "openai/gpt-oss-20b",
    name: "GPT OSS 20B",
    family: "gpt-oss",
    attachment: false,
    reasoning: true,
    toolCall: true,
    temperature: true,
    openWeights: true,
    releaseDate: "2025-08-05",
    lastUpdated: "2025-08-05",
    modalities: { input: ["text"], output: ["text"] },
    limit: { context: 131072, output: 32768 },
    cost: { input: 0, output: 0 },
  },
  "qwen/qwen3-30b-a3b-2507": {
    id: "qwen/qwen3-30b-a3b-2507",
    name: "Qwen3 30B A3B 2507",
    family: "qwen",
    attachment: false,
    reasoning: false,
    toolCall: true,
    temperature: true,
    openWeights: true,
    knowledge: "2025-04",
    releaseDate: "2025-07-30",
    lastUpdated: "2025-07-30",
    modalities: { input: ["text"], output: ["text"] },
    limit: { context: 262144, output: 16384 },
    cost: { input: 0, output: 0 },
  },
  "qwen/qwen3-coder-30b": {
    id: "qwen/qwen3-coder-30b",
    name: "Qwen3 Coder 30B",
    family: "qwen",
    attachment: false,
    reasoning: false,
    toolCall: true,
    temperature: true,
    openWeights: true,
    knowledge: "2025-04",
    releaseDate: "2025-07-23",
    lastUpdated: "2025-07-23",
    modalities: { input: ["text"], output: ["text"] },
    limit: { context: 262144, output: 65536 },
    cost: { input: 0, output: 0 },
  },
} as const satisfies Record<string, ModelInfo>;

export type LmstudioModelId = keyof typeof models;
export type LmstudioTextModelId = "openai/gpt-oss-20b" | "qwen/qwen3-30b-a3b-2507" | "qwen/qwen3-coder-30b";
export type LmstudioImageModelId = never;
export type LmstudioAudioModelId = never;
export type LmstudioVideoModelId = never;
