// Generated by scripts/codegen.ts — DO NOT EDIT.
// Source: https://models.dev/api.json (committed snapshot: data/models-dev.json)
// Regenerate with `bun run codegen` (or `bun run codegen:refresh` to update the snapshot).

import type { ModelInfo, ProviderInfo } from "../core/catalog-types";

export const provider = {
  id: "lucidquery",
  name: "LucidQuery",
  env: ["LUCIDQUERY_API_KEY"],
  doc: "https://lucidquery.com/docs",
  api: "https://api.lucidquery.com/v1",
} as const satisfies ProviderInfo;

export const models = {
  "lucidnova-rf1-100b": {
    id: "lucidnova-rf1-100b",
    name: "LucidNova RF1 100B",
    family: "nova",
    attachment: true,
    reasoning: true,
    toolCall: true,
    temperature: false,
    openWeights: false,
    knowledge: "2025-09-16",
    releaseDate: "2024-12-28",
    lastUpdated: "2025-09-10",
    modalities: { input: ["text"], output: ["text"] },
    limit: { context: 120000, output: 8000 },
    cost: { input: 2, output: 5 },
  },
  "lucidquery-agi-01-frontier": {
    id: "lucidquery-agi-01-frontier",
    name: "AGI-01 Frontier",
    family: "agi",
    attachment: true,
    reasoning: true,
    toolCall: true,
    temperature: true,
    openWeights: false,
    knowledge: "2026-06-05",
    releaseDate: "2026-06-16",
    lastUpdated: "2026-06-16",
    modalities: { input: ["text", "image"], output: ["text"] },
    limit: { context: 300000, output: 120000 },
    cost: { input: 4.5, output: 22 },
  },
  "lucidquery-agi-01-swift": {
    id: "lucidquery-agi-01-swift",
    name: "AGI-01 Swift",
    family: "agi",
    attachment: true,
    reasoning: true,
    toolCall: true,
    temperature: true,
    openWeights: false,
    knowledge: "2026-06-05",
    releaseDate: "2026-06-16",
    lastUpdated: "2026-06-16",
    modalities: { input: ["text", "image"], output: ["text"] },
    limit: { context: 300000, output: 120000 },
    cost: { input: 2.5, output: 15 },
  },
  "lucidquery-nexus-coder": {
    id: "lucidquery-nexus-coder",
    name: "LucidQuery Nexus Coder",
    family: "lucid",
    attachment: true,
    reasoning: true,
    toolCall: true,
    temperature: false,
    openWeights: false,
    knowledge: "2025-08-01",
    releaseDate: "2025-09-01",
    lastUpdated: "2025-09-01",
    modalities: { input: ["text"], output: ["text"] },
    limit: { context: 250000, output: 60000 },
    cost: { input: 2, output: 5 },
  },
} as const satisfies Record<string, ModelInfo>;

export type LucidqueryModelId = keyof typeof models;
export type LucidqueryTextModelId = "lucidnova-rf1-100b" | "lucidquery-agi-01-frontier" | "lucidquery-agi-01-swift" | "lucidquery-nexus-coder";
export type LucidqueryImageModelId = never;
export type LucidqueryAudioModelId = never;
export type LucidqueryVideoModelId = never;
