// Generated by scripts/codegen.ts — DO NOT EDIT.
// Source: https://models.dev/api.json (committed snapshot: data/models-dev.json)
// Regenerate with `bun run codegen` (or `bun run codegen:refresh` to update the snapshot).

import type { ModelInfo, ProviderInfo } from "../core/catalog-types";

export const provider = {
  id: "lynkr",
  name: "Lynkr",
  env: ["LYNKR_API_KEY"],
  doc: "https://github.com/Fast-Editor/Lynkr",
  api: "http://127.0.0.1:8081/v1",
} as const satisfies ProviderInfo;

export const models = {
  "lynkr-auto": {
    id: "lynkr-auto",
    name: "Lynkr Auto (complexity routing)",
    family: "auto",
    attachment: false,
    reasoning: false,
    toolCall: true,
    temperature: true,
    openWeights: false,
    releaseDate: "2025-12-03",
    lastUpdated: "2026-07-11",
    modalities: { input: ["text"], output: ["text"] },
    limit: { context: 128000, output: 8192 },
    cost: { input: 0, output: 0 },
  },
} as const satisfies Record<string, ModelInfo>;

export type LynkrModelId = keyof typeof models;
export type LynkrTextModelId = "lynkr-auto";
export type LynkrImageModelId = never;
export type LynkrAudioModelId = never;
export type LynkrVideoModelId = never;
