// Generated by scripts/codegen.ts — DO NOT EDIT.
// Source: https://models.dev/api.json (committed snapshot: data/models-dev.json)
// Regenerate with `bun run codegen` (or `bun run codegen:refresh` to update the snapshot).

import type { ModelInfo, ProviderInfo } from "../core/catalog-types";

export const provider = {
  id: "mixlayer",
  name: "Mixlayer",
  env: ["MIXLAYER_API_KEY"],
  doc: "https://docs.mixlayer.com",
  api: "https://models.mixlayer.ai/v1",
} as const satisfies ProviderInfo;

export const models = {
  "qwen/qwen3.5-122b-a10b": {
    id: "qwen/qwen3.5-122b-a10b",
    name: "Qwen3.5 122B A10B",
    family: "qwen",
    attachment: false,
    reasoning: true,
    toolCall: true,
    temperature: true,
    openWeights: true,
    releaseDate: "2026-03-18",
    lastUpdated: "2026-03-18",
    modalities: { input: ["text"], output: ["text"] },
    limit: { context: 262144, output: 262144 },
    cost: { input: 0.4, output: 3.2 },
  },
  "qwen/qwen3.5-27b": {
    id: "qwen/qwen3.5-27b",
    name: "Qwen3.5 27B",
    family: "qwen",
    attachment: false,
    reasoning: true,
    toolCall: true,
    temperature: true,
    openWeights: true,
    releaseDate: "2026-03-18",
    lastUpdated: "2026-03-18",
    modalities: { input: ["text"], output: ["text"] },
    limit: { context: 262144, output: 262144 },
    cost: { input: 0.3, output: 2.4 },
  },
  "qwen/qwen3.5-35b-a3b": {
    id: "qwen/qwen3.5-35b-a3b",
    name: "Qwen3.5 35B A3B",
    family: "qwen",
    attachment: false,
    reasoning: true,
    toolCall: true,
    temperature: true,
    openWeights: true,
    releaseDate: "2026-03-18",
    lastUpdated: "2026-03-18",
    modalities: { input: ["text"], output: ["text"] },
    limit: { context: 262144, output: 262144 },
    cost: { input: 0.25, output: 1.3 },
  },
  "qwen/qwen3.5-397b-a17b": {
    id: "qwen/qwen3.5-397b-a17b",
    name: "Qwen3.5 397B A17B",
    family: "qwen",
    attachment: false,
    reasoning: true,
    toolCall: true,
    temperature: true,
    openWeights: true,
    releaseDate: "2026-03-18",
    lastUpdated: "2026-03-18",
    modalities: { input: ["text"], output: ["text"] },
    limit: { context: 262144, output: 262144 },
    cost: { input: 0.6, output: 3.6 },
  },
  "qwen/qwen3.5-9b": {
    id: "qwen/qwen3.5-9b",
    name: "Qwen3.5 9B",
    family: "qwen",
    attachment: false,
    reasoning: true,
    toolCall: true,
    temperature: true,
    openWeights: true,
    releaseDate: "2026-03-18",
    lastUpdated: "2026-03-18",
    modalities: { input: ["text"], output: ["text"] },
    limit: { context: 262144, output: 262144 },
    cost: { input: 0.1, output: 0.4 },
  },
} as const satisfies Record<string, ModelInfo>;

export type MixlayerModelId = keyof typeof models;
export type MixlayerTextModelId = "qwen/qwen3.5-122b-a10b" | "qwen/qwen3.5-27b" | "qwen/qwen3.5-35b-a3b" | "qwen/qwen3.5-397b-a17b" | "qwen/qwen3.5-9b";
export type MixlayerImageModelId = never;
export type MixlayerAudioModelId = never;
export type MixlayerVideoModelId = never;
