// Generated by scripts/codegen.ts — DO NOT EDIT.
// Source: https://models.dev/api.json (committed snapshot: data/models-dev.json)
// Regenerate with `bun run codegen` (or `bun run codegen:refresh` to update the snapshot).

import type { ModelInfo, ProviderInfo } from "../core/catalog-types";

export const provider = {
  id: "moonshotai",
  name: "Moonshot AI",
  env: ["MOONSHOT_API_KEY"],
  doc: "https://platform.moonshot.ai/docs/api/chat",
  api: "https://api.moonshot.ai/v1",
} as const satisfies ProviderInfo;

export const models = {
  "kimi-k2.6": {
    id: "kimi-k2.6",
    name: "Kimi K2.6",
    family: "kimi-k2",
    attachment: true,
    reasoning: true,
    toolCall: true,
    structuredOutput: true,
    temperature: true,
    openWeights: true,
    knowledge: "2025-01",
    releaseDate: "2026-04-21",
    lastUpdated: "2026-04-21",
    modalities: { input: ["text", "image", "video"], output: ["text"] },
    limit: { context: 262144, output: 262144 },
    cost: { input: 0.95, output: 4, cacheRead: 0.16 },
  },
  "kimi-k2.7-code": {
    id: "kimi-k2.7-code",
    name: "Kimi K2.7 Code",
    family: "kimi-k2",
    attachment: true,
    reasoning: true,
    toolCall: true,
    structuredOutput: true,
    temperature: false,
    openWeights: true,
    knowledge: "2025-01",
    releaseDate: "2026-06-12",
    lastUpdated: "2026-06-12",
    modalities: { input: ["text", "image", "video"], output: ["text"] },
    limit: { context: 262144, output: 262144 },
    cost: { input: 0.95, output: 4, cacheRead: 0.19 },
  },
  "kimi-k2.7-code-highspeed": {
    id: "kimi-k2.7-code-highspeed",
    name: "Kimi K2.7 Code HighSpeed",
    family: "kimi-k2",
    attachment: true,
    reasoning: true,
    toolCall: true,
    structuredOutput: true,
    temperature: false,
    openWeights: true,
    knowledge: "2025-01",
    releaseDate: "2026-06-12",
    lastUpdated: "2026-06-12",
    modalities: { input: ["text", "image", "video"], output: ["text"] },
    limit: { context: 262144, output: 262144 },
    cost: { input: 1.9, output: 8, cacheRead: 0.38 },
  },
  "kimi-k3": {
    id: "kimi-k3",
    name: "Kimi K3",
    family: "kimi-k3",
    attachment: true,
    reasoning: true,
    toolCall: true,
    structuredOutput: true,
    temperature: false,
    openWeights: true,
    releaseDate: "2026-07-16",
    lastUpdated: "2026-07-16",
    modalities: { input: ["text", "image", "video"], output: ["text"] },
    limit: { context: 1048576, output: 131072 },
    cost: { input: 3, output: 15, cacheRead: 0.3 },
  },
} as const satisfies Record<string, ModelInfo>;

export type MoonshotaiModelId = keyof typeof models;
export type MoonshotaiTextModelId = "kimi-k2.6" | "kimi-k2.7-code" | "kimi-k2.7-code-highspeed" | "kimi-k3";
export type MoonshotaiImageModelId = never;
export type MoonshotaiAudioModelId = never;
export type MoonshotaiVideoModelId = never;
