// Generated by scripts/codegen.ts — DO NOT EDIT.
// Source: https://models.dev/api.json (committed snapshot: data/models-dev.json)
// Regenerate with `bun run codegen` (or `bun run codegen:refresh` to update the snapshot).

import type { ModelInfo, ProviderInfo } from "../core/catalog-types";

export const provider = {
  id: "neosmith",
  name: "NeoSmith",
  env: ["NEOSMITH_API_KEY"],
  doc: "https://neosmith.ai/docs",
  api: "https://router.neosmith.ai/v1",
} as const satisfies ProviderInfo;

export const models = {
  "neosmith.intelligent-basic": {
    id: "neosmith.intelligent-basic",
    name: "NeoSmith Basic",
    attachment: true,
    reasoning: true,
    toolCall: true,
    structuredOutput: false,
    temperature: true,
    openWeights: false,
    releaseDate: "2026-04-26",
    lastUpdated: "2026-08-03",
    modalities: { input: ["text", "image"], output: ["text"] },
    limit: { context: 1000000, output: 128000 },
    cost: { input: 1.17, output: 4.37, cacheRead: 0.22, cacheWrite: 0 },
  },
  "neosmith.intelligent-maestro": {
    id: "neosmith.intelligent-maestro",
    name: "NeoSmith Maestro",
    attachment: true,
    reasoning: true,
    toolCall: true,
    structuredOutput: false,
    temperature: true,
    openWeights: false,
    releaseDate: "2026-08-03",
    lastUpdated: "2026-08-08",
    modalities: { input: ["text", "image"], output: ["text"] },
    limit: { context: 1000000, output: 128000 },
    cost: { input: 2.4, output: 12, cacheRead: 0.35, cacheWrite: 0 },
  },
  "neosmith.intelligent-pro": {
    id: "neosmith.intelligent-pro",
    name: "NeoSmith Pro",
    attachment: true,
    reasoning: true,
    toolCall: true,
    structuredOutput: false,
    temperature: true,
    openWeights: false,
    releaseDate: "2026-04-26",
    lastUpdated: "2026-07-18",
    modalities: { input: ["text", "image"], output: ["text"] },
    limit: { context: 1000000, output: 128000 },
    cost: { input: 1.81, output: 8.39, cacheRead: 0.3, cacheWrite: 0 },
  },
  "neosmith.neolite": {
    id: "neosmith.neolite",
    name: "NeoSmith NeoLite",
    attachment: true,
    reasoning: true,
    toolCall: true,
    structuredOutput: false,
    temperature: true,
    openWeights: false,
    releaseDate: "2026-06-20",
    lastUpdated: "2026-08-03",
    modalities: { input: ["text", "image"], output: ["text"] },
    limit: { context: 512000, output: 64000 },
    cost: { input: 0.6, output: 2.4, cacheRead: 0.08, cacheWrite: 0 },
  },
} as const satisfies Record<string, ModelInfo>;

export type NeosmithModelId = keyof typeof models;
export type NeosmithTextModelId = "neosmith.intelligent-basic" | "neosmith.intelligent-maestro" | "neosmith.intelligent-pro" | "neosmith.neolite";
export type NeosmithImageModelId = never;
export type NeosmithAudioModelId = never;
export type NeosmithVideoModelId = never;
