// Generated by scripts/codegen.ts — DO NOT EDIT.
// Source: https://models.dev/api.json (committed snapshot: data/models-dev.json)
// Regenerate with `bun run codegen` (or `bun run codegen:refresh` to update the snapshot).

import type { ModelInfo, ProviderInfo } from "../core/catalog-types";

export const provider = {
  id: "nova",
  name: "Nova",
  env: ["NOVA_API_KEY"],
  doc: "https://nova.amazon.com/dev/documentation",
  api: "https://api.nova.amazon.com/v1",
} as const satisfies ProviderInfo;

export const models = {
  "nova-2-lite-v1": {
    id: "nova-2-lite-v1",
    name: "Nova 2 Lite",
    family: "nova-lite",
    attachment: true,
    reasoning: true,
    toolCall: true,
    temperature: true,
    openWeights: false,
    releaseDate: "2025-12-01",
    lastUpdated: "2025-12-01",
    modalities: { input: ["text", "image", "video", "pdf"], output: ["text"] },
    limit: { context: 1000000, output: 64000 },
    cost: { input: 0, output: 0, reasoning: 0 },
  },
  "nova-2-pro-v1": {
    id: "nova-2-pro-v1",
    name: "Nova 2 Pro",
    family: "nova-pro",
    attachment: true,
    reasoning: true,
    toolCall: true,
    temperature: true,
    openWeights: false,
    releaseDate: "2025-12-03",
    lastUpdated: "2026-01-03",
    modalities: { input: ["text", "image", "video", "pdf"], output: ["text"] },
    limit: { context: 1000000, output: 64000 },
    cost: { input: 0, output: 0, reasoning: 0 },
  },
} as const satisfies Record<string, ModelInfo>;

export type NovaModelId = keyof typeof models;
export type NovaTextModelId = "nova-2-lite-v1" | "nova-2-pro-v1";
export type NovaImageModelId = never;
export type NovaAudioModelId = never;
export type NovaVideoModelId = never;
