// Generated by scripts/codegen.ts — DO NOT EDIT.
// Source: https://models.dev/api.json (committed snapshot: data/models-dev.json)
// Regenerate with `bun run codegen` (or `bun run codegen:refresh` to update the snapshot).

import type { ModelInfo, ProviderInfo } from "../core/catalog-types";

export const provider = {
  id: "pendra",
  name: "Pendra",
  env: ["PENDRA_API_KEY"],
  doc: "https://pendra.ai/docs/integrations/opencode",
  api: "https://api.pendra.ai/api/v1",
} as const satisfies ProviderInfo;

export const models = {
  "deepseek-v4-flash": {
    id: "deepseek-v4-flash",
    name: "DeepSeek V4 Flash",
    family: "deepseek-flash",
    attachment: false,
    reasoning: true,
    toolCall: true,
    structuredOutput: true,
    temperature: true,
    openWeights: true,
    knowledge: "2025-05",
    releaseDate: "2026-04-24",
    lastUpdated: "2026-04-24",
    modalities: { input: ["text"], output: ["text"] },
    limit: { context: 1000000, output: 384000 },
    cost: { input: 0, output: 0 },
  },
  "glm-4.7-flash": {
    id: "glm-4.7-flash",
    name: "GLM-4.7-Flash",
    family: "glm-flash",
    attachment: false,
    reasoning: true,
    toolCall: true,
    temperature: true,
    openWeights: true,
    knowledge: "2025-04",
    releaseDate: "2026-01-19",
    lastUpdated: "2026-01-19",
    modalities: { input: ["text"], output: ["text"] },
    limit: { context: 200000, output: 131072 },
    cost: { input: 0, output: 0 },
  },
  "gpt-oss:120b": {
    id: "gpt-oss:120b",
    name: "GPT OSS 120B",
    family: "gpt-oss",
    attachment: false,
    reasoning: true,
    toolCall: true,
    structuredOutput: true,
    temperature: true,
    openWeights: true,
    releaseDate: "2025-08-05",
    lastUpdated: "2025-08-05",
    modalities: { input: ["text"], output: ["text"] },
    limit: { context: 131072, output: 32768 },
    cost: { input: 0, output: 0 },
  },
  "llama3.3:70b": {
    id: "llama3.3:70b",
    name: "Llama-3.3-70B-Instruct",
    family: "llama",
    attachment: false,
    reasoning: false,
    toolCall: true,
    temperature: true,
    openWeights: true,
    knowledge: "2023-12",
    releaseDate: "2024-12-06",
    lastUpdated: "2024-12-06",
    modalities: { input: ["text"], output: ["text"] },
    limit: { context: 128000, output: 4096 },
    cost: { input: 0, output: 0 },
  },
  "qwen3-coder:30b": {
    id: "qwen3-coder:30b",
    name: "Qwen3-Coder 30B-A3B Instruct",
    family: "qwen",
    attachment: false,
    reasoning: false,
    toolCall: true,
    temperature: true,
    openWeights: true,
    knowledge: "2025-04",
    releaseDate: "2025-04",
    lastUpdated: "2025-04",
    modalities: { input: ["text"], output: ["text"] },
    limit: { context: 262144, output: 65536 },
    cost: { input: 0, output: 0 },
  },
  "qwen3.6:27b": {
    id: "qwen3.6:27b",
    name: "Qwen3.6 27B",
    family: "qwen",
    attachment: true,
    reasoning: true,
    toolCall: true,
    structuredOutput: true,
    temperature: true,
    openWeights: true,
    releaseDate: "2026-04-22",
    lastUpdated: "2026-04-22",
    modalities: { input: ["text", "image"], output: ["text"] },
    limit: { context: 262144, output: 65536 },
    cost: { input: 0, output: 0 },
  },
} as const satisfies Record<string, ModelInfo>;

export type PendraModelId = keyof typeof models;
export type PendraTextModelId = "deepseek-v4-flash" | "glm-4.7-flash" | "gpt-oss:120b" | "llama3.3:70b" | "qwen3-coder:30b" | "qwen3.6:27b";
export type PendraImageModelId = never;
export type PendraAudioModelId = never;
export type PendraVideoModelId = never;
