// Generated by scripts/codegen.ts — DO NOT EDIT.
// Source: https://models.dev/api.json (committed snapshot: data/models-dev.json)
// Regenerate with `bun run codegen` (or `bun run codegen:refresh` to update the snapshot).

import type { ModelInfo, ProviderInfo } from "../core/catalog-types";

export const provider = {
  id: "perplexity",
  name: "Perplexity",
  env: ["PERPLEXITY_API_KEY"],
  doc: "https://docs.perplexity.ai",
} as const satisfies ProviderInfo;

export const models = {
  "sonar": {
    id: "sonar",
    name: "Sonar",
    family: "sonar",
    attachment: false,
    reasoning: false,
    toolCall: false,
    temperature: true,
    openWeights: false,
    knowledge: "2025-09-01",
    releaseDate: "2024-01-01",
    lastUpdated: "2025-09-01",
    modalities: { input: ["text"], output: ["text"] },
    limit: { context: 128000, output: 4096 },
    cost: { input: 1, output: 1 },
  },
  "sonar-deep-research": {
    id: "sonar-deep-research",
    name: "Perplexity Sonar Deep Research",
    attachment: false,
    reasoning: true,
    toolCall: false,
    temperature: false,
    openWeights: false,
    knowledge: "2025-01",
    releaseDate: "2025-02-01",
    lastUpdated: "2025-09-01",
    modalities: { input: ["text"], output: ["text"] },
    limit: { context: 128000, output: 32768 },
    cost: { input: 2, output: 8, reasoning: 3 },
  },
  "sonar-pro": {
    id: "sonar-pro",
    name: "Sonar Pro",
    family: "sonar-pro",
    attachment: true,
    reasoning: false,
    toolCall: false,
    temperature: true,
    openWeights: false,
    knowledge: "2025-09-01",
    releaseDate: "2024-01-01",
    lastUpdated: "2025-09-01",
    modalities: { input: ["text", "image"], output: ["text"] },
    limit: { context: 200000, output: 8192 },
    cost: { input: 3, output: 15 },
  },
  "sonar-reasoning-pro": {
    id: "sonar-reasoning-pro",
    name: "Sonar Reasoning Pro",
    family: "sonar-reasoning",
    attachment: true,
    reasoning: true,
    toolCall: false,
    temperature: true,
    openWeights: false,
    knowledge: "2025-09-01",
    releaseDate: "2024-01-01",
    lastUpdated: "2025-09-01",
    modalities: { input: ["text", "image"], output: ["text"] },
    limit: { context: 128000, output: 4096 },
    cost: { input: 2, output: 8 },
  },
} as const satisfies Record<string, ModelInfo>;

export type PerplexityModelId = keyof typeof models;
export type PerplexityTextModelId = "sonar" | "sonar-deep-research" | "sonar-pro" | "sonar-reasoning-pro";
export type PerplexityImageModelId = never;
export type PerplexityAudioModelId = never;
export type PerplexityVideoModelId = never;
