// Generated by scripts/codegen.ts — DO NOT EDIT.
// Source: https://models.dev/api.json (committed snapshot: data/models-dev.json)
// Regenerate with `bun run codegen` (or `bun run codegen:refresh` to update the snapshot).

import type { ModelInfo, ProviderInfo } from "../core/catalog-types";

export const provider = {
  id: "sakana",
  name: "Sakana AI",
  env: ["SAKANA_API_KEY"],
  doc: "https://console.sakana.ai/models",
  api: "https://api.sakana.ai/v1",
} as const satisfies ProviderInfo;

export const models = {
  "fugu": {
    id: "fugu",
    name: "Fugu",
    family: "fugu",
    attachment: true,
    reasoning: true,
    toolCall: true,
    structuredOutput: true,
    temperature: false,
    openWeights: false,
    releaseDate: "2026-06-15",
    lastUpdated: "2026-06-15",
    modalities: { input: ["text", "image"], output: ["text"] },
    limit: { context: 1000000, output: 1000000 },
  },
  "fugu-ultra": {
    id: "fugu-ultra",
    name: "Fugu Ultra",
    family: "fugu",
    attachment: true,
    reasoning: true,
    toolCall: true,
    structuredOutput: true,
    temperature: false,
    openWeights: false,
    releaseDate: "2026-06-15",
    lastUpdated: "2026-06-15",
    modalities: { input: ["text", "image"], output: ["text"] },
    limit: { context: 1000000, output: 1000000 },
    cost: { input: 5, output: 30, cacheRead: 0.5 },
  },
  "fugu-ultra-20260615": {
    id: "fugu-ultra-20260615",
    name: "Fugu Ultra",
    family: "fugu",
    attachment: true,
    reasoning: true,
    toolCall: true,
    structuredOutput: true,
    temperature: false,
    openWeights: false,
    releaseDate: "2026-06-15",
    lastUpdated: "2026-06-15",
    modalities: { input: ["text", "image"], output: ["text"] },
    limit: { context: 1000000, output: 1000000 },
    cost: { input: 5, output: 30, cacheRead: 0.5 },
  },
  "sakana-namazu": {
    id: "sakana-namazu",
    name: "Sakana Namazu",
    family: "sakana-namazu",
    attachment: true,
    reasoning: true,
    toolCall: true,
    structuredOutput: true,
    temperature: true,
    openWeights: false,
    releaseDate: "2026-08-03",
    lastUpdated: "2026-08-03",
    modalities: { input: ["text", "image", "pdf"], output: ["text"] },
    limit: { context: 262144, output: 65536 },
    cost: { input: 0.95, output: 4, cacheRead: 0.15 },
  },
} as const satisfies Record<string, ModelInfo>;

export type SakanaModelId = keyof typeof models;
export type SakanaTextModelId = "fugu" | "fugu-ultra" | "fugu-ultra-20260615" | "sakana-namazu";
export type SakanaImageModelId = never;
export type SakanaAudioModelId = never;
export type SakanaVideoModelId = never;
