// Generated by scripts/codegen.ts — DO NOT EDIT.
// Source: https://models.dev/api.json (committed snapshot: data/models-dev.json)
// Regenerate with `bun run codegen` (or `bun run codegen:refresh` to update the snapshot).

import type { ModelInfo, ProviderInfo } from "../core/catalog-types";

export const provider = {
  id: "scx",
  name: "SCX.ai",
  env: ["SCX_API_KEY"],
  doc: "https://platform.scx.ai/docs",
  api: "https://api.scx.ai/v1",
} as const satisfies ProviderInfo;

export const models = {
  "MiniMax-M2.7": {
    id: "MiniMax-M2.7",
    name: "MiniMax-M2.7",
    family: "minimax",
    attachment: false,
    reasoning: true,
    toolCall: true,
    structuredOutput: true,
    temperature: true,
    openWeights: true,
    releaseDate: "2026-03-18",
    lastUpdated: "2026-03-18",
    modalities: { input: ["text"], output: ["text"] },
    limit: { context: 192000, output: 64000 },
    cost: { input: 0.48, output: 1.79, cacheRead: 0.05 },
  },
  "gpt-oss-120b": {
    id: "gpt-oss-120b",
    name: "GPT OSS 120B",
    family: "gpt-oss",
    attachment: false,
    reasoning: true,
    toolCall: true,
    structuredOutput: true,
    temperature: true,
    openWeights: true,
    releaseDate: "2025-08-05",
    lastUpdated: "2025-08-05",
    modalities: { input: ["text"], output: ["text"] },
    limit: { context: 131072, output: 131072 },
    cost: { input: 0.17, output: 0.55 },
  },
} as const satisfies Record<string, ModelInfo>;

export type ScxModelId = keyof typeof models;
export type ScxTextModelId = "MiniMax-M2.7" | "gpt-oss-120b";
export type ScxImageModelId = never;
export type ScxAudioModelId = never;
export type ScxVideoModelId = never;
