// Generated by scripts/codegen.ts — DO NOT EDIT.
// Source: https://models.dev/api.json (committed snapshot: data/models-dev.json)
// Regenerate with `bun run codegen` (or `bun run codegen:refresh` to update the snapshot).

import type { ModelInfo, ProviderInfo } from "../core/catalog-types";

export const provider = {
  id: "stepfun-ai-step-plan",
  name: "StepFun Step Plan (Global)",
  env: ["STEPFUN_API_KEY"],
  doc: "https://platform.stepfun.ai/docs/en/step-plan/integrations/reasoning-api",
  api: "https://api.stepfun.ai/step_plan/v1",
} as const satisfies ProviderInfo;

export const models = {
  "step-3.5-flash": {
    id: "step-3.5-flash",
    name: "Step 3.5 Flash",
    attachment: false,
    reasoning: true,
    toolCall: true,
    temperature: true,
    openWeights: true,
    knowledge: "2025-01",
    releaseDate: "2026-01-29",
    lastUpdated: "2026-02-13",
    modalities: { input: ["text"], output: ["text"] },
    limit: { context: 256000, output: 256000, input: 256000 },
  },
  "step-3.5-flash-2603": {
    id: "step-3.5-flash-2603",
    name: "Step 3.5 Flash 2603",
    attachment: false,
    reasoning: true,
    toolCall: true,
    temperature: true,
    openWeights: true,
    knowledge: "2025-01",
    releaseDate: "2026-04-02",
    lastUpdated: "2026-04-02",
    modalities: { input: ["text"], output: ["text"] },
    limit: { context: 256000, output: 256000, input: 256000 },
  },
  "step-3.7-flash": {
    id: "step-3.7-flash",
    name: "Step 3.7 Flash",
    attachment: true,
    reasoning: true,
    toolCall: true,
    temperature: true,
    openWeights: true,
    knowledge: "2026-03-01",
    releaseDate: "2026-05-29",
    lastUpdated: "2026-05-29",
    modalities: { input: ["text", "image", "video"], output: ["text"] },
    limit: { context: 256000, output: 256000, input: 256000 },
  },
} as const satisfies Record<string, ModelInfo>;

export type StepfunAiStepPlanModelId = keyof typeof models;
export type StepfunAiStepPlanTextModelId = "step-3.5-flash" | "step-3.5-flash-2603" | "step-3.7-flash";
export type StepfunAiStepPlanImageModelId = never;
export type StepfunAiStepPlanAudioModelId = never;
export type StepfunAiStepPlanVideoModelId = never;
