// Generated by scripts/codegen.ts — DO NOT EDIT.
// Source: https://models.dev/api.json (committed snapshot: data/models-dev.json)
// Regenerate with `bun run codegen` (or `bun run codegen:refresh` to update the snapshot).

import type { ModelInfo, ProviderInfo } from "../core/catalog-types";

export const provider = {
  id: "tencent-tokenhub",
  name: "Tencent TokenHub",
  env: ["TENCENT_TOKENHUB_API_KEY"],
  doc: "https://cloud.tencent.com/document/product/1823/130050",
  api: "https://tokenhub.tencentmaas.com/v1",
} as const satisfies ProviderInfo;

export const models = {
  "hy3": {
    id: "hy3",
    name: "Hy3",
    family: "Hy",
    attachment: false,
    reasoning: true,
    toolCall: true,
    temperature: true,
    openWeights: true,
    releaseDate: "2026-07-06",
    lastUpdated: "2026-07-06",
    modalities: { input: ["text"], output: ["text"] },
    limit: { context: 256000, output: 128000, input: 192000 },
    cost: { input: 0, output: 0, cacheRead: 0, cacheWrite: 0 },
  },
  "hy3-preview": {
    id: "hy3-preview",
    name: "Hy3 preview",
    family: "Hy",
    attachment: false,
    reasoning: true,
    toolCall: true,
    temperature: true,
    openWeights: true,
    releaseDate: "2026-04-20",
    lastUpdated: "2026-04-20",
    modalities: { input: ["text"], output: ["text"] },
    limit: { context: 256000, output: 64000 },
    cost: { input: 0, output: 0, cacheRead: 0, cacheWrite: 0 },
  },
  "hy4-preview": {
    id: "hy4-preview",
    name: "Hy4 preview",
    family: "Hy",
    attachment: false,
    reasoning: true,
    toolCall: true,
    temperature: true,
    openWeights: true,
    releaseDate: "2026-08-28",
    lastUpdated: "2026-08-28",
    modalities: { input: ["text"], output: ["text"] },
    limit: { context: 1024000, output: 64000 },
    cost: { input: 0.834, output: 2.501, cacheRead: 0.042 },
  },
} as const satisfies Record<string, ModelInfo>;

export type TencentTokenhubModelId = keyof typeof models;
export type TencentTokenhubTextModelId = "hy3" | "hy3-preview" | "hy4-preview";
export type TencentTokenhubImageModelId = never;
export type TencentTokenhubAudioModelId = never;
export type TencentTokenhubVideoModelId = never;
