// Generated by scripts/codegen.ts — DO NOT EDIT.
// Source: https://models.dev/api.json (committed snapshot: data/models-dev.json)
// Regenerate with `bun run codegen` (or `bun run codegen:refresh` to update the snapshot).

import type { ModelInfo, ProviderInfo } from "../core/catalog-types";

export const provider = {
  id: "tencent-token-plan",
  name: "Tencent Token Plan",
  env: ["TENCENT_TOKEN_PLAN_API_KEY"],
  doc: "https://cloud.tencent.com/document/product/1823/130060",
  api: "https://api.lkeap.cloud.tencent.com/plan/v3",
} as const satisfies ProviderInfo;

export const models = {
  "hy3": {
    id: "hy3",
    name: "Hy3",
    family: "Hy",
    attachment: false,
    reasoning: true,
    toolCall: true,
    temperature: true,
    openWeights: true,
    releaseDate: "2026-07-06",
    lastUpdated: "2026-07-06",
    modalities: { input: ["text"], output: ["text"] },
    limit: { context: 256000, output: 64000 },
    cost: { input: 0, output: 0, cacheRead: 0, cacheWrite: 0 },
  },
} as const satisfies Record<string, ModelInfo>;

export type TencentTokenPlanModelId = keyof typeof models;
export type TencentTokenPlanTextModelId = "hy3";
export type TencentTokenPlanImageModelId = never;
export type TencentTokenPlanAudioModelId = never;
export type TencentTokenPlanVideoModelId = never;
