// Generated by scripts/codegen.ts — DO NOT EDIT.
// Source: https://models.dev/api.json (committed snapshot: data/models-dev.json)
// Regenerate with `bun run codegen` (or `bun run codegen:refresh` to update the snapshot).

import type { ModelInfo, ProviderInfo } from "../core/catalog-types";
import * as _302aiGen from "./302ai.gen";
import * as abacusGen from "./abacus.gen";
import * as abliterationAiGen from "./abliteration-ai.gen";
import * as aboveGen from "./above.gen";
import * as agentrouterGen from "./agentrouter.gen";
import * as agnesGen from "./agnes.gen";
import * as aiRouterGen from "./ai-router.gen";
import * as aiandGen from "./aiand.gen";
import * as aihubmixGen from "./aihubmix.gen";
import * as aixyGen from "./aixy.gen";
import * as akiIoGen from "./aki-io.gen";
import * as alibabaGen from "./alibaba.gen";
import * as alibabaCnGen from "./alibaba-cn.gen";
import * as alibabaCodingPlanGen from "./alibaba-coding-plan.gen";
import * as alibabaCodingPlanCnGen from "./alibaba-coding-plan-cn.gen";
import * as alibabaTokenPlanGen from "./alibaba-token-plan.gen";
import * as alibabaTokenPlanCnGen from "./alibaba-token-plan-cn.gen";
import * as amazonBedrockGen from "./amazon-bedrock.gen";
import * as ambientGen from "./ambient.gen";
import * as amdGen from "./amd.gen";
import * as anthropicGen from "./anthropic.gen";
import * as anyapiGen from "./anyapi.gen";
import * as arceeGen from "./arcee.gen";
import * as atomicChatGen from "./atomic-chat.gen";
import * as aurikoGen from "./auriko.gen";
import * as azureGen from "./azure.gen";
import * as azureCognitiveServicesGen from "./azure-cognitive-services.gen";
import * as bailingGen from "./bailing.gen";
import * as basetenGen from "./baseten.gen";
import * as bergetGen from "./berget.gen";
import * as blueclawGen from "./blueclaw.gen";
import * as bothubGen from "./bothub.gen";
import * as cerebrasGen from "./cerebras.gen";
import * as chutesGen from "./chutes.gen";
import * as clarifaiGen from "./clarifai.gen";
import * as claudinioGen from "./claudinio.gen";
import * as clinePassGen from "./cline-pass.gen";
import * as cloudferroSherlockGen from "./cloudferro-sherlock.gen";
import * as cloudflareAiGatewayGen from "./cloudflare-ai-gateway.gen";
import * as cloudflareWorkersAiGen from "./cloudflare-workers-ai.gen";
import * as cohereGen from "./cohere.gen";
import * as coralbricksGen from "./coralbricks.gen";
import * as cortecsGen from "./cortecs.gen";
import * as crofGen from "./crof.gen";
import * as crossmodelGen from "./crossmodel.gen";
import * as crusoeGen from "./crusoe.gen";
import * as daoxeGen from "./daoxe.gen";
import * as databricksGen from "./databricks.gen";
import * as deepinfraGen from "./deepinfra.gen";
import * as deepseekGen from "./deepseek.gen";
import * as digitaloceanGen from "./digitalocean.gen";
import * as dinferenceGen from "./dinference.gen";
import * as drunGen from "./drun.gen";
import * as ebcloudGen from "./ebcloud.gen";
import * as echoGen from "./echo.gen";
import * as edenaiGen from "./edenai.gen";
import * as empiriolabsGen from "./empiriolabs.gen";
import * as evrocGen from "./evroc.gen";
import * as fastrouterGen from "./fastrouter.gen";
import * as fireworksAiGen from "./fireworks-ai.gen";
import * as freemodelGen from "./freemodel.gen";
import * as friendliGen from "./friendli.gen";
import * as frogbotGen from "./frogbot.gen";
import * as githubCopilotGen from "./github-copilot.gen";
import * as gitlabGen from "./gitlab.gen";
import * as gmicloudGen from "./gmicloud.gen";
import * as googleGen from "./google.gen";
import * as googleVertexGen from "./google-vertex.gen";
import * as googleVertexAnthropicGen from "./google-vertex-anthropic.gen";
import * as greenptGen from "./greenpt.gen";
import * as groqGen from "./groq.gen";
import * as heliconeGen from "./helicone.gen";
import * as hetznerGen from "./hetzner.gen";
import * as hpcAiGen from "./hpc-ai.gen";
import * as huggingfaceGen from "./huggingface.gen";
import * as hyperGen from "./hyper.gen";
import * as iflowcnGen from "./iflowcn.gen";
import * as impossiblGen from "./impossibl.gen";
import * as inceptionGen from "./inception.gen";
import * as inceptronGen from "./inceptron.gen";
import * as inferenceGen from "./inference.gen";
import * as inferxGen from "./inferx.gen";
import * as infomaniakGen from "./infomaniak.gen";
import * as ioNetGen from "./io-net.gen";
import * as iteracomputeGen from "./iteracompute.gen";
import * as jalapenoGen from "./jalapeno.gen";
import * as jiekouGen from "./jiekou.gen";
import * as kenariGen from "./kenari.gen";
import * as kiloGen from "./kilo.gen";
import * as kimiForCodingGen from "./kimi-for-coding.gen";
import * as klokintegrationGen from "./klokintegration.gen";
import * as kosmikGen from "./kosmik.gen";
import * as kuaeCloudCodingPlanGen from "./kuae-cloud-coding-plan.gen";
import * as lilacGen from "./lilac.gen";
import * as llamaGen from "./llama.gen";
import * as llmgatewayGen from "./llmgateway.gen";
import * as llmgatewayProvidersGen from "./llmgateway-providers.gen";
import * as llmtechGen from "./llmtech.gen";
import * as llmtrGen from "./llmtr.gen";
import * as lmstudioGen from "./lmstudio.gen";
import * as longcatGen from "./longcat.gen";
import * as lucidqueryGen from "./lucidquery.gen";
import * as lynkrGen from "./lynkr.gen";
import * as meganovaGen from "./meganova.gen";
import * as mergeGatewayGen from "./merge-gateway.gen";
import * as metaGen from "./meta.gen";
import * as minimaxGen from "./minimax.gen";
import * as minimaxCnGen from "./minimax-cn.gen";
import * as minimaxCnCodingPlanGen from "./minimax-cn-coding-plan.gen";
import * as minimaxCodingPlanGen from "./minimax-coding-plan.gen";
import * as mistralGen from "./mistral.gen";
import * as mixlayerGen from "./mixlayer.gen";
import * as moarkGen from "./moark.gen";
import * as modalGen from "./modal.gen";
import * as modelOracleAiGen from "./model-oracle-ai.gen";
import * as modelisGen from "./modelis.gen";
import * as modelscopeGen from "./modelscope.gen";
import * as moonshotaiGen from "./moonshotai.gen";
import * as moonshotaiCnGen from "./moonshotai-cn.gen";
import * as morphGen from "./morph.gen";
import * as nanoGptGen from "./nano-gpt.gen";
import * as nearaiGen from "./nearai.gen";
import * as nebiusGen from "./nebius.gen";
import * as neonGen from "./neon.gen";
import * as neosmithGen from "./neosmith.gen";
import * as neuralwattGen from "./neuralwatt.gen";
import * as novaGen from "./nova.gen";
import * as novitaAiGen from "./novita-ai.gen";
import * as nvidiaGen from "./nvidia.gen";
import * as ofoxGen from "./ofox.gen";
import * as ollamaCloudGen from "./ollama-cloud.gen";
import * as openaiGen from "./openai.gen";
import * as opencodeGen from "./opencode.gen";
import * as opencodeGoGen from "./opencode-go.gen";
import * as openreasonGen from "./openreason.gen";
import * as openrouterGen from "./openrouter.gen";
import * as opperGen from "./opper.gen";
import * as orcarouterGen from "./orcarouter.gen";
import * as ovhcloudGen from "./ovhcloud.gen";
import * as pendraGen from "./pendra.gen";
import * as perplexityGen from "./perplexity.gen";
import * as perplexityAgentGen from "./perplexity-agent.gen";
import * as pioneerGen from "./pioneer.gen";
import * as poeGen from "./poe.gen";
import * as poolsideGen from "./poolside.gen";
import * as privatemodeAiGen from "./privatemode-ai.gen";
import * as qihangAiGen from "./qihang-ai.gen";
import * as qiniuAiGen from "./qiniu-ai.gen";
import * as qvacGen from "./qvac.gen";
import * as regoloAiGen from "./regolo-ai.gen";
import * as requestyGen from "./requesty.gen";
import * as routingRunGen from "./routing-run.gen";
import * as runinfraGen from "./runinfra.gen";
import * as sakanaGen from "./sakana.gen";
import * as saladCloudGen from "./salad-cloud.gen";
import * as sapAiCoreGen from "./sap-ai-core.gen";
import * as sarvamGen from "./sarvam.gen";
import * as scalewayGen from "./scaleway.gen";
import * as scnetTokenPlanGen from "./scnet-token-plan.gen";
import * as scxAiGen from "./scx-ai.gen";
import * as sensenovaGen from "./sensenova.gen";
import * as siliconflowGen from "./siliconflow.gen";
import * as siliconflowCnGen from "./siliconflow-cn.gen";
import * as snowflakeCortexGen from "./snowflake-cortex.gen";
import * as stackitGen from "./stackit.gen";
import * as standardcomputeGen from "./standardcompute.gen";
import * as stepfunGen from "./stepfun.gen";
import * as stepfunAiGen from "./stepfun-ai.gen";
import * as stepfunAiStepPlanGen from "./stepfun-ai-step-plan.gen";
import * as stepfunStepPlanGen from "./stepfun-step-plan.gen";
import * as subconsciousGen from "./subconscious.gen";
import * as submodelGen from "./submodel.gen";
import * as syntheticGen from "./synthetic.gen";
import * as tencentCodingPlanGen from "./tencent-coding-plan.gen";
import * as tencentTokenPlanGen from "./tencent-token-plan.gen";
import * as tencentTokenhubGen from "./tencent-tokenhub.gen";
import * as tensorxGen from "./tensorx.gen";
import * as theGridAiGen from "./the-grid-ai.gen";
import * as thinkingmachinesGen from "./thinkingmachines.gen";
import * as tinfoilGen from "./tinfoil.gen";
import * as togetheraiGen from "./togetherai.gen";
import * as tokengoGen from "./tokengo.gen";
import * as tokenrouterGen from "./tokenrouter.gen";
import * as trustedrouterGen from "./trustedrouter.gen";
import * as umansAiGen from "./umans-ai.gen";
import * as umansAiCodingPlanGen from "./umans-ai-coding-plan.gen";
import * as unorouterGen from "./unorouter.gen";
import * as upstageGen from "./upstage.gen";
import * as v0Gen from "./v0.gen";
import * as vancineGen from "./vancine.gen";
import * as veniceGen from "./venice.gen";
import * as vercelGen from "./vercel.gen";
import * as vivgridGen from "./vivgrid.gen";
import * as volcengineGen from "./volcengine.gen";
import * as volcengineCodingPlanGen from "./volcengine-coding-plan.gen";
import * as vultrGen from "./vultr.gen";
import * as waferAiGen from "./wafer.ai.gen";
import * as wandbGen from "./wandb.gen";
import * as watsonxGen from "./watsonx.gen";
import * as xaiGen from "./xai.gen";
import * as xiaomiGen from "./xiaomi.gen";
import * as xiaomiTokenPlanAmsGen from "./xiaomi-token-plan-ams.gen";
import * as xiaomiTokenPlanCnGen from "./xiaomi-token-plan-cn.gen";
import * as xiaomiTokenPlanSgpGen from "./xiaomi-token-plan-sgp.gen";
import * as xpersonaGen from "./xpersona.gen";
import * as zaiGen from "./zai.gen";
import * as zaiCodingPlanGen from "./zai-coding-plan.gen";
import * as zeldocGen from "./zeldoc.gen";
import * as zenifraGen from "./zenifra.gen";
import * as zenmuxGen from "./zenmux.gen";
import * as zhipuaiGen from "./zhipuai.gen";
import * as zhipuaiCodingPlanGen from "./zhipuai-coding-plan.gen";

export interface ProviderCatalog {
  provider: ProviderInfo;
  models: Record<string, ModelInfo>;
}

export type ProviderId =
  | "302ai"
  | "abacus"
  | "abliteration-ai"
  | "above"
  | "agentrouter"
  | "agnes"
  | "ai-router"
  | "aiand"
  | "aihubmix"
  | "aixy"
  | "aki-io"
  | "alibaba"
  | "alibaba-cn"
  | "alibaba-coding-plan"
  | "alibaba-coding-plan-cn"
  | "alibaba-token-plan"
  | "alibaba-token-plan-cn"
  | "amazon-bedrock"
  | "ambient"
  | "amd"
  | "anthropic"
  | "anyapi"
  | "arcee"
  | "atomic-chat"
  | "auriko"
  | "azure"
  | "azure-cognitive-services"
  | "bailing"
  | "baseten"
  | "berget"
  | "blueclaw"
  | "bothub"
  | "cerebras"
  | "chutes"
  | "clarifai"
  | "claudinio"
  | "cline-pass"
  | "cloudferro-sherlock"
  | "cloudflare-ai-gateway"
  | "cloudflare-workers-ai"
  | "cohere"
  | "coralbricks"
  | "cortecs"
  | "crof"
  | "crossmodel"
  | "crusoe"
  | "daoxe"
  | "databricks"
  | "deepinfra"
  | "deepseek"
  | "digitalocean"
  | "dinference"
  | "drun"
  | "ebcloud"
  | "echo"
  | "edenai"
  | "empiriolabs"
  | "evroc"
  | "fastrouter"
  | "fireworks-ai"
  | "freemodel"
  | "friendli"
  | "frogbot"
  | "github-copilot"
  | "gitlab"
  | "gmicloud"
  | "google"
  | "google-vertex"
  | "google-vertex-anthropic"
  | "greenpt"
  | "groq"
  | "helicone"
  | "hetzner"
  | "hpc-ai"
  | "huggingface"
  | "hyper"
  | "iflowcn"
  | "impossibl"
  | "inception"
  | "inceptron"
  | "inference"
  | "inferx"
  | "infomaniak"
  | "io-net"
  | "iteracompute"
  | "jalapeno"
  | "jiekou"
  | "kenari"
  | "kilo"
  | "kimi-for-coding"
  | "klokintegration"
  | "kosmik"
  | "kuae-cloud-coding-plan"
  | "lilac"
  | "llama"
  | "llmgateway"
  | "llmgateway-providers"
  | "llmtech"
  | "llmtr"
  | "lmstudio"
  | "longcat"
  | "lucidquery"
  | "lynkr"
  | "meganova"
  | "merge-gateway"
  | "meta"
  | "minimax"
  | "minimax-cn"
  | "minimax-cn-coding-plan"
  | "minimax-coding-plan"
  | "mistral"
  | "mixlayer"
  | "moark"
  | "modal"
  | "model-oracle-ai"
  | "modelis"
  | "modelscope"
  | "moonshotai"
  | "moonshotai-cn"
  | "morph"
  | "nano-gpt"
  | "nearai"
  | "nebius"
  | "neon"
  | "neosmith"
  | "neuralwatt"
  | "nova"
  | "novita-ai"
  | "nvidia"
  | "ofox"
  | "ollama-cloud"
  | "openai"
  | "opencode"
  | "opencode-go"
  | "openreason"
  | "openrouter"
  | "opper"
  | "orcarouter"
  | "ovhcloud"
  | "pendra"
  | "perplexity"
  | "perplexity-agent"
  | "pioneer"
  | "poe"
  | "poolside"
  | "privatemode-ai"
  | "qihang-ai"
  | "qiniu-ai"
  | "qvac"
  | "regolo-ai"
  | "requesty"
  | "routing-run"
  | "runinfra"
  | "sakana"
  | "salad-cloud"
  | "sap-ai-core"
  | "sarvam"
  | "scaleway"
  | "scnet-token-plan"
  | "scx-ai"
  | "sensenova"
  | "siliconflow"
  | "siliconflow-cn"
  | "snowflake-cortex"
  | "stackit"
  | "standardcompute"
  | "stepfun"
  | "stepfun-ai"
  | "stepfun-ai-step-plan"
  | "stepfun-step-plan"
  | "subconscious"
  | "submodel"
  | "synthetic"
  | "tencent-coding-plan"
  | "tencent-token-plan"
  | "tencent-tokenhub"
  | "tensorx"
  | "the-grid-ai"
  | "thinkingmachines"
  | "tinfoil"
  | "togetherai"
  | "tokengo"
  | "tokenrouter"
  | "trustedrouter"
  | "umans-ai"
  | "umans-ai-coding-plan"
  | "unorouter"
  | "upstage"
  | "v0"
  | "vancine"
  | "venice"
  | "vercel"
  | "vivgrid"
  | "volcengine"
  | "volcengine-coding-plan"
  | "vultr"
  | "wafer.ai"
  | "wandb"
  | "watsonx"
  | "xai"
  | "xiaomi"
  | "xiaomi-token-plan-ams"
  | "xiaomi-token-plan-cn"
  | "xiaomi-token-plan-sgp"
  | "xpersona"
  | "zai"
  | "zai-coding-plan"
  | "zeldoc"
  | "zenifra"
  | "zenmux"
  | "zhipuai"
  | "zhipuai-coding-plan";

/**
 * The full registry with every literal the `.gen` files already computed.
 *
 * `satisfies`, not an annotation: the annotation checks the rows exactly the
 * same way and then throws away what it checked, so `keyof` collapses to
 * `string`, every limit widens to `number`, and `getModel("anthropic", "…")`
 * completes nothing. This is the same edit `GEMINI_IMAGE_MODEL_RULES` and the
 * CLI registries carry, at catalog scale.
 *
 * The price is real and is why this lives on its own subpath: the bundled
 * declaration for this entry is ~3.6 MB against ~4 KiB for `unmodel/catalog`.
 * See the doc on `catalog` in `./index`.
 */
export const catalogTyped = {
  "302ai": _302aiGen,
  "abacus": abacusGen,
  "abliteration-ai": abliterationAiGen,
  "above": aboveGen,
  "agentrouter": agentrouterGen,
  "agnes": agnesGen,
  "ai-router": aiRouterGen,
  "aiand": aiandGen,
  "aihubmix": aihubmixGen,
  "aixy": aixyGen,
  "aki-io": akiIoGen,
  "alibaba": alibabaGen,
  "alibaba-cn": alibabaCnGen,
  "alibaba-coding-plan": alibabaCodingPlanGen,
  "alibaba-coding-plan-cn": alibabaCodingPlanCnGen,
  "alibaba-token-plan": alibabaTokenPlanGen,
  "alibaba-token-plan-cn": alibabaTokenPlanCnGen,
  "amazon-bedrock": amazonBedrockGen,
  "ambient": ambientGen,
  "amd": amdGen,
  "anthropic": anthropicGen,
  "anyapi": anyapiGen,
  "arcee": arceeGen,
  "atomic-chat": atomicChatGen,
  "auriko": aurikoGen,
  "azure": azureGen,
  "azure-cognitive-services": azureCognitiveServicesGen,
  "bailing": bailingGen,
  "baseten": basetenGen,
  "berget": bergetGen,
  "blueclaw": blueclawGen,
  "bothub": bothubGen,
  "cerebras": cerebrasGen,
  "chutes": chutesGen,
  "clarifai": clarifaiGen,
  "claudinio": claudinioGen,
  "cline-pass": clinePassGen,
  "cloudferro-sherlock": cloudferroSherlockGen,
  "cloudflare-ai-gateway": cloudflareAiGatewayGen,
  "cloudflare-workers-ai": cloudflareWorkersAiGen,
  "cohere": cohereGen,
  "coralbricks": coralbricksGen,
  "cortecs": cortecsGen,
  "crof": crofGen,
  "crossmodel": crossmodelGen,
  "crusoe": crusoeGen,
  "daoxe": daoxeGen,
  "databricks": databricksGen,
  "deepinfra": deepinfraGen,
  "deepseek": deepseekGen,
  "digitalocean": digitaloceanGen,
  "dinference": dinferenceGen,
  "drun": drunGen,
  "ebcloud": ebcloudGen,
  "echo": echoGen,
  "edenai": edenaiGen,
  "empiriolabs": empiriolabsGen,
  "evroc": evrocGen,
  "fastrouter": fastrouterGen,
  "fireworks-ai": fireworksAiGen,
  "freemodel": freemodelGen,
  "friendli": friendliGen,
  "frogbot": frogbotGen,
  "github-copilot": githubCopilotGen,
  "gitlab": gitlabGen,
  "gmicloud": gmicloudGen,
  "google": googleGen,
  "google-vertex": googleVertexGen,
  "google-vertex-anthropic": googleVertexAnthropicGen,
  "greenpt": greenptGen,
  "groq": groqGen,
  "helicone": heliconeGen,
  "hetzner": hetznerGen,
  "hpc-ai": hpcAiGen,
  "huggingface": huggingfaceGen,
  "hyper": hyperGen,
  "iflowcn": iflowcnGen,
  "impossibl": impossiblGen,
  "inception": inceptionGen,
  "inceptron": inceptronGen,
  "inference": inferenceGen,
  "inferx": inferxGen,
  "infomaniak": infomaniakGen,
  "io-net": ioNetGen,
  "iteracompute": iteracomputeGen,
  "jalapeno": jalapenoGen,
  "jiekou": jiekouGen,
  "kenari": kenariGen,
  "kilo": kiloGen,
  "kimi-for-coding": kimiForCodingGen,
  "klokintegration": klokintegrationGen,
  "kosmik": kosmikGen,
  "kuae-cloud-coding-plan": kuaeCloudCodingPlanGen,
  "lilac": lilacGen,
  "llama": llamaGen,
  "llmgateway": llmgatewayGen,
  "llmgateway-providers": llmgatewayProvidersGen,
  "llmtech": llmtechGen,
  "llmtr": llmtrGen,
  "lmstudio": lmstudioGen,
  "longcat": longcatGen,
  "lucidquery": lucidqueryGen,
  "lynkr": lynkrGen,
  "meganova": meganovaGen,
  "merge-gateway": mergeGatewayGen,
  "meta": metaGen,
  "minimax": minimaxGen,
  "minimax-cn": minimaxCnGen,
  "minimax-cn-coding-plan": minimaxCnCodingPlanGen,
  "minimax-coding-plan": minimaxCodingPlanGen,
  "mistral": mistralGen,
  "mixlayer": mixlayerGen,
  "moark": moarkGen,
  "modal": modalGen,
  "model-oracle-ai": modelOracleAiGen,
  "modelis": modelisGen,
  "modelscope": modelscopeGen,
  "moonshotai": moonshotaiGen,
  "moonshotai-cn": moonshotaiCnGen,
  "morph": morphGen,
  "nano-gpt": nanoGptGen,
  "nearai": nearaiGen,
  "nebius": nebiusGen,
  "neon": neonGen,
  "neosmith": neosmithGen,
  "neuralwatt": neuralwattGen,
  "nova": novaGen,
  "novita-ai": novitaAiGen,
  "nvidia": nvidiaGen,
  "ofox": ofoxGen,
  "ollama-cloud": ollamaCloudGen,
  "openai": openaiGen,
  "opencode": opencodeGen,
  "opencode-go": opencodeGoGen,
  "openreason": openreasonGen,
  "openrouter": openrouterGen,
  "opper": opperGen,
  "orcarouter": orcarouterGen,
  "ovhcloud": ovhcloudGen,
  "pendra": pendraGen,
  "perplexity": perplexityGen,
  "perplexity-agent": perplexityAgentGen,
  "pioneer": pioneerGen,
  "poe": poeGen,
  "poolside": poolsideGen,
  "privatemode-ai": privatemodeAiGen,
  "qihang-ai": qihangAiGen,
  "qiniu-ai": qiniuAiGen,
  "qvac": qvacGen,
  "regolo-ai": regoloAiGen,
  "requesty": requestyGen,
  "routing-run": routingRunGen,
  "runinfra": runinfraGen,
  "sakana": sakanaGen,
  "salad-cloud": saladCloudGen,
  "sap-ai-core": sapAiCoreGen,
  "sarvam": sarvamGen,
  "scaleway": scalewayGen,
  "scnet-token-plan": scnetTokenPlanGen,
  "scx-ai": scxAiGen,
  "sensenova": sensenovaGen,
  "siliconflow": siliconflowGen,
  "siliconflow-cn": siliconflowCnGen,
  "snowflake-cortex": snowflakeCortexGen,
  "stackit": stackitGen,
  "standardcompute": standardcomputeGen,
  "stepfun": stepfunGen,
  "stepfun-ai": stepfunAiGen,
  "stepfun-ai-step-plan": stepfunAiStepPlanGen,
  "stepfun-step-plan": stepfunStepPlanGen,
  "subconscious": subconsciousGen,
  "submodel": submodelGen,
  "synthetic": syntheticGen,
  "tencent-coding-plan": tencentCodingPlanGen,
  "tencent-token-plan": tencentTokenPlanGen,
  "tencent-tokenhub": tencentTokenhubGen,
  "tensorx": tensorxGen,
  "the-grid-ai": theGridAiGen,
  "thinkingmachines": thinkingmachinesGen,
  "tinfoil": tinfoilGen,
  "togetherai": togetheraiGen,
  "tokengo": tokengoGen,
  "tokenrouter": tokenrouterGen,
  "trustedrouter": trustedrouterGen,
  "umans-ai": umansAiGen,
  "umans-ai-coding-plan": umansAiCodingPlanGen,
  "unorouter": unorouterGen,
  "upstage": upstageGen,
  "v0": v0Gen,
  "vancine": vancineGen,
  "venice": veniceGen,
  "vercel": vercelGen,
  "vivgrid": vivgridGen,
  "volcengine": volcengineGen,
  "volcengine-coding-plan": volcengineCodingPlanGen,
  "vultr": vultrGen,
  "wafer.ai": waferAiGen,
  "wandb": wandbGen,
  "watsonx": watsonxGen,
  "xai": xaiGen,
  "xiaomi": xiaomiGen,
  "xiaomi-token-plan-ams": xiaomiTokenPlanAmsGen,
  "xiaomi-token-plan-cn": xiaomiTokenPlanCnGen,
  "xiaomi-token-plan-sgp": xiaomiTokenPlanSgpGen,
  "xpersona": xpersonaGen,
  "zai": zaiGen,
  "zai-coding-plan": zaiCodingPlanGen,
  "zeldoc": zeldocGen,
  "zenifra": zenifraGen,
  "zenmux": zenmuxGen,
  "zhipuai": zhipuaiGen,
  "zhipuai-coding-plan": zhipuaiCodingPlanGen,
} satisfies Record<ProviderId, ProviderCatalog>;

/** The typed registry's own type — `Catalog["anthropic"]["models"]` and so on. */
export type Catalog = typeof catalogTyped;

/** Every model id one provider serves, as a union. */
export type ModelIdFor<P extends ProviderId> = Extract<keyof Catalog[P]["models"], string>;

/**
 * One provider's catalog slice, with its literals.
 *
 * Two overloads, and the loose one is not a formality: a provider id known
 * only at run time falls to it and keeps `| undefined`, which is the honest
 * answer. A KNOWN literal cannot miss, so it does not.
 */
export function getProviderTyped<P extends ProviderId>(providerId: P): Catalog[P];
export function getProviderTyped(
  providerId: ProviderId | (string & {}),
): ProviderCatalog | undefined;
export function getProviderTyped(providerId: string): ProviderCatalog | undefined {
  // Object.hasOwn: ids like "constructor" must not resolve to inherited
  // Object.prototype members.
  return Object.hasOwn(catalogTyped, providerId)
    ? (catalogTyped as Record<string, ProviderCatalog>)[providerId]
    : undefined;
}

/**
 * One model's row, with its literals — `.limit.context` is `1000000`, not
 * `number`, and needs no `?.`.
 *
 * A known provider with an UNKNOWN model id falls to the loose overload and
 * keeps `| undefined`, which is again the honest answer.
 */
export function getModelTyped<P extends ProviderId, M extends ModelIdFor<P>>(
  providerId: P,
  modelId: M,
): Catalog[P]["models"][M];
export function getModelTyped(
  providerId: ProviderId | (string & {}),
  modelId: string,
): ModelInfo | undefined;
export function getModelTyped(providerId: string, modelId: string): ModelInfo | undefined {
  const models = getProviderTyped(providerId)?.models;
  return models !== undefined && Object.hasOwn(models, modelId) ? models[modelId] : undefined;
}
