// Generated by scripts/codegen.ts — DO NOT EDIT.
// Source: https://models.dev/api.json (committed snapshot: data/models-dev.json)
// Regenerate with `bun run codegen` (or `bun run codegen:refresh` to update the snapshot).

import type { ModelInfo, ProviderInfo } from "../core/catalog-types";

export const provider = {
  id: "upstage",
  name: "Upstage",
  env: ["UPSTAGE_API_KEY"],
  doc: "https://developers.upstage.ai/docs/apis/chat",
  api: "https://api.upstage.ai/v1/solar",
} as const satisfies ProviderInfo;

export const models = {
  "solar-mini": {
    id: "solar-mini",
    name: "solar-mini",
    family: "solar-mini",
    attachment: false,
    reasoning: false,
    toolCall: true,
    temperature: true,
    openWeights: false,
    knowledge: "2024-09",
    releaseDate: "2024-06-12",
    lastUpdated: "2025-04-22",
    modalities: { input: ["text"], output: ["text"] },
    limit: { context: 32768, output: 4096 },
    cost: { input: 0.15, output: 0.15 },
  },
  "solar-pro2": {
    id: "solar-pro2",
    name: "solar-pro2",
    family: "solar-pro",
    attachment: false,
    reasoning: true,
    toolCall: true,
    temperature: true,
    openWeights: false,
    knowledge: "2025-03",
    releaseDate: "2025-05-20",
    lastUpdated: "2025-05-20",
    modalities: { input: ["text"], output: ["text"] },
    limit: { context: 65536, output: 8192 },
    cost: { input: 0.25, output: 0.25 },
  },
  "solar-pro3": {
    id: "solar-pro3",
    name: "solar-pro3",
    family: "solar-pro",
    attachment: false,
    reasoning: true,
    toolCall: true,
    temperature: true,
    openWeights: false,
    knowledge: "2025-03",
    releaseDate: "2026-01",
    lastUpdated: "2026-01",
    modalities: { input: ["text"], output: ["text"] },
    limit: { context: 131072, output: 8192 },
    cost: { input: 0.25, output: 0.25 },
  },
  "solar-pro4": {
    id: "solar-pro4",
    name: "Solar Pro 4",
    family: "solar-pro",
    attachment: false,
    reasoning: true,
    toolCall: true,
    structuredOutput: true,
    temperature: true,
    openWeights: false,
    knowledge: "2026-02",
    releaseDate: "2026-08-06",
    lastUpdated: "2026-08-06",
    modalities: { input: ["text"], output: ["text"] },
    limit: { context: 524288, output: 131072 },
    cost: { input: 0.3, output: 1.2, cacheRead: 0.06 },
  },
} as const satisfies Record<string, ModelInfo>;

export type UpstageModelId = keyof typeof models;
export type UpstageTextModelId = "solar-mini" | "solar-pro2" | "solar-pro3" | "solar-pro4";
export type UpstageImageModelId = never;
export type UpstageAudioModelId = never;
export type UpstageVideoModelId = never;
