// Generated by scripts/codegen.ts — DO NOT EDIT.
// Source: https://models.dev/api.json (committed snapshot: data/models-dev.json)
// Regenerate with `bun run codegen` (or `bun run codegen:refresh` to update the snapshot).

import type { ModelInfo, ProviderInfo } from "../core/catalog-types";

export const provider = {
  id: "v0",
  name: "v0",
  env: ["V0_API_KEY"],
  doc: "https://sdk.vercel.ai/providers/ai-sdk-providers/vercel",
} as const satisfies ProviderInfo;

export const models = {
  "v0-1.0-md": {
    id: "v0-1.0-md",
    name: "v0-1.0-md",
    family: "v0",
    attachment: true,
    reasoning: true,
    toolCall: true,
    temperature: true,
    openWeights: false,
    releaseDate: "2025-05-22",
    lastUpdated: "2025-05-22",
    modalities: { input: ["text", "image"], output: ["text"] },
    limit: { context: 128000, output: 32000 },
    cost: { input: 3, output: 15 },
  },
  "v0-1.5-lg": {
    id: "v0-1.5-lg",
    name: "v0-1.5-lg",
    family: "v0",
    attachment: true,
    reasoning: true,
    toolCall: true,
    temperature: true,
    openWeights: false,
    releaseDate: "2025-06-09",
    lastUpdated: "2025-06-09",
    modalities: { input: ["text", "image"], output: ["text"] },
    limit: { context: 512000, output: 32000 },
    cost: { input: 15, output: 75 },
  },
  "v0-1.5-md": {
    id: "v0-1.5-md",
    name: "v0-1.5-md",
    family: "v0",
    attachment: true,
    reasoning: true,
    toolCall: true,
    temperature: true,
    openWeights: false,
    releaseDate: "2025-06-09",
    lastUpdated: "2025-06-09",
    modalities: { input: ["text", "image"], output: ["text"] },
    limit: { context: 128000, output: 32000 },
    cost: { input: 3, output: 15 },
  },
} as const satisfies Record<string, ModelInfo>;

export type V0ModelId = keyof typeof models;
export type V0TextModelId = "v0-1.0-md" | "v0-1.5-lg" | "v0-1.5-md";
export type V0ImageModelId = never;
export type V0AudioModelId = never;
export type V0VideoModelId = never;
