// Generated by scripts/codegen.ts — DO NOT EDIT.
// Source: https://models.dev/api.json (committed snapshot: data/models-dev.json)
// Regenerate with `bun run codegen` (or `bun run codegen:refresh` to update the snapshot).

import type { ModelInfo, ProviderInfo } from "../core/catalog-types";

export const provider = {
  id: "watsonx",
  name: "watsonx.ai",
  env: ["WATSONX_AI_APIKEY", "WATSONX_AI_PROJECT_ID"],
  doc: "https://www.ibm.com/docs/en/watsonx/saas?topic=solutions-supported-foundation-models",
} as const satisfies ProviderInfo;

export const models = {
  "ibm/granite-4-h-small": {
    id: "ibm/granite-4-h-small",
    name: "Granite-4.0-H-Small",
    family: "granite",
    attachment: false,
    reasoning: false,
    toolCall: true,
    structuredOutput: true,
    temperature: true,
    openWeights: true,
    releaseDate: "2025-10-02",
    lastUpdated: "2025-10-02",
    modalities: { input: ["text"], output: ["text"] },
    limit: { context: 131072, output: 131072 },
    cost: { input: 0.0636, output: 0.265 },
  },
  "meta-llama/llama-3-3-70b-instruct": {
    id: "meta-llama/llama-3-3-70b-instruct",
    name: "Llama-3.3-70B-Instruct",
    family: "llama",
    attachment: true,
    reasoning: false,
    toolCall: true,
    temperature: true,
    openWeights: true,
    knowledge: "2023-12",
    releaseDate: "2024-12-06",
    lastUpdated: "2024-12-06",
    modalities: { input: ["text"], output: ["text"] },
    limit: { context: 131072, output: 4096 },
    cost: { input: 0.7526, output: 0.7526 },
  },
  "meta-llama/llama-4-maverick-17b-128e-instruct-fp8": {
    id: "meta-llama/llama-4-maverick-17b-128e-instruct-fp8",
    name: "Llama 4 Maverick 17B 128E Instruct FP8",
    family: "llama",
    attachment: true,
    reasoning: false,
    toolCall: true,
    temperature: true,
    openWeights: true,
    knowledge: "2024-08",
    releaseDate: "2025-04-05",
    lastUpdated: "2025-04-05",
    modalities: { input: ["text", "image"], output: ["text"] },
    limit: { context: 131072, output: 8192 },
    cost: { input: 0.371, output: 1.484 },
  },
  "mistralai/mistral-small-3-1-24b-instruct-2503": {
    id: "mistralai/mistral-small-3-1-24b-instruct-2503",
    name: "Mistral Small 3.1 24B",
    family: "mistral-small",
    attachment: true,
    reasoning: false,
    toolCall: true,
    structuredOutput: true,
    temperature: true,
    openWeights: true,
    knowledge: "2024-06",
    releaseDate: "2025-03-17",
    lastUpdated: "2025-03-17",
    modalities: { input: ["text", "image"], output: ["text"] },
    limit: { context: 131072, output: 16384 },
    cost: { input: 0.106, output: 0.318 },
  },
  "openai/gpt-oss-120b": {
    id: "openai/gpt-oss-120b",
    name: "GPT OSS 120B",
    family: "gpt-oss",
    attachment: false,
    reasoning: true,
    toolCall: true,
    structuredOutput: true,
    temperature: true,
    openWeights: true,
    releaseDate: "2025-08-05",
    lastUpdated: "2025-08-05",
    modalities: { input: ["text"], output: ["text"] },
    limit: { context: 131072, output: 32768 },
    cost: { input: 0.159, output: 0.636 },
  },
} as const satisfies Record<string, ModelInfo>;

export type WatsonxModelId = keyof typeof models;
export type WatsonxTextModelId = "ibm/granite-4-h-small" | "meta-llama/llama-3-3-70b-instruct" | "meta-llama/llama-4-maverick-17b-128e-instruct-fp8" | "mistralai/mistral-small-3-1-24b-instruct-2503" | "openai/gpt-oss-120b";
export type WatsonxImageModelId = never;
export type WatsonxAudioModelId = never;
export type WatsonxVideoModelId = never;
