// Generated by scripts/codegen.ts — DO NOT EDIT.
// Source: https://models.dev/api.json (committed snapshot: data/models-dev.json)
// Regenerate with `bun run codegen` (or `bun run codegen:refresh` to update the snapshot).

import type { ModelInfo, ProviderInfo } from "../core/catalog-types";

export const provider = {
  id: "zhipuai-coding-plan",
  name: "Zhipu AI Coding Plan",
  env: ["ZHIPU_API_KEY"],
  doc: "https://docs.bigmodel.cn/cn/coding-plan/overview",
  api: "https://open.bigmodel.cn/api/coding/paas/v4",
} as const satisfies ProviderInfo;

export const models = {
  "glm-4.6v": {
    id: "glm-4.6v",
    name: "GLM-4.6V",
    family: "glm",
    attachment: true,
    reasoning: true,
    toolCall: true,
    temperature: true,
    openWeights: true,
    knowledge: "2025-04",
    releaseDate: "2025-12-08",
    lastUpdated: "2025-12-08",
    modalities: { input: ["text", "image", "video"], output: ["text"] },
    limit: { context: 128000, output: 32768 },
    cost: { input: 0.3, output: 0.9 },
  },
  "glm-5.3": {
    id: "glm-5.3",
    name: "GLM-5.3",
    family: "glm",
    attachment: false,
    reasoning: true,
    toolCall: true,
    structuredOutput: true,
    temperature: true,
    openWeights: true,
    releaseDate: "2026-08-14",
    lastUpdated: "2026-08-14",
    modalities: { input: ["text"], output: ["text"] },
    limit: { context: 1000000, output: 131072 },
    cost: { input: 0, output: 0, cacheRead: 0, cacheWrite: 0 },
  },
  "glm-5.3-flash": {
    id: "glm-5.3-flash",
    name: "GLM-5.3-Flash",
    family: "glm-flash",
    attachment: true,
    reasoning: true,
    toolCall: true,
    structuredOutput: true,
    temperature: true,
    openWeights: true,
    releaseDate: "2026-08-26",
    lastUpdated: "2026-08-26",
    modalities: { input: ["text", "image", "video", "pdf"], output: ["text"] },
    limit: { context: 1000000, output: 131072 },
    cost: { input: 0, output: 0, cacheRead: 0, cacheWrite: 0 },
  },
  "glm-5.3-highspeed": {
    id: "glm-5.3-highspeed",
    name: "GLM-5.3 Highspeed",
    family: "glm",
    attachment: false,
    reasoning: true,
    toolCall: true,
    structuredOutput: true,
    temperature: true,
    openWeights: true,
    releaseDate: "2026-08-14",
    lastUpdated: "2026-08-14",
    modalities: { input: ["text"], output: ["text"] },
    limit: { context: 1000000, output: 131072 },
    cost: { input: 0, output: 0, cacheRead: 0, cacheWrite: 0 },
  },
} as const satisfies Record<string, ModelInfo>;

export type ZhipuaiCodingPlanModelId = keyof typeof models;
export type ZhipuaiCodingPlanTextModelId = "glm-4.6v" | "glm-5.3" | "glm-5.3-flash" | "glm-5.3-highspeed";
export type ZhipuaiCodingPlanImageModelId = never;
export type ZhipuaiCodingPlanAudioModelId = never;
export type ZhipuaiCodingPlanVideoModelId = never;
