/**
 * `fal.image` — text-to-image across fal's queue.
 *
 * `POST https://queue.fal.run/{endpoint}`, flat JSON body,
 * `Authorization: Key <FAL_KEY>`.
 *
 * ## The route is a parameter, and it is not called `model`
 *
 * At fal the endpoint id IS the URL path, at arbitrary depth
 * (`fal-ai/bytedance/seedream/v4.5/text-to-image`), and there is no model
 * field in the body. Every other provider here would spell that selector
 * `model` — but `model` is a REAL wire field on several fal endpoints
 * (`fal-ai/sync-lipsync/v2` sends `model: "lipsync-2"`), so it cannot also be
 * the router without one silently eating the other. The selector is therefore
 * `endpoint`: a pseudo-param, stripped in `finalize`, interpolated into
 * `.request.url`, and hard-errored at codegen time if any curated endpoint
 * ever declares a property by that name.
 *
 * Unified callers are unaffected — `"fal/fal-ai/flux/dev"` splits on the FIRST
 * slash, so they still write `model:`.
 *
 * ## One schema, 28 endpoints, per-endpoint narrowing
 *
 * The zod schema is ONE `z.looseObject` for the whole category — 28 eagerly
 * constructed per-endpoint schemas to use one is not a trade worth making —
 * and it deliberately carries no bounds. What each endpoint requires, ranges
 * and enumerates lives in the generated `FAL_IMAGE_SHAPES` rows, which the
 * shared check battery in `./checks.ts` reads at run time to compose a message
 * naming that endpoint and citing its own documentation. `num_inference_steps`
 * tops out at 50 on `fal-ai/flux/dev` and at 12 on `fal-ai/flux/schnell`; a
 * schema that accepted the union would accept a request schnell refuses.
 *
 * At the TYPE level the same narrowing comes from {@link FalImageArm}, which
 * indexes the generated by-id body map. A union of 28 arms was measured
 * against it (30-arm scratch build, `tsc --extendedDiagnostics`): the union
 * cost 8,908 instantiations to the map's 3,127, and could not express two
 * things the map can — `ExactKeys` against a whole union reads `keyof` as the
 * key INTERSECTION, so per-arm `Extract` is mandatory and is where the cost
 * goes, and a dynamically-typed endpoint id is not assignable to a union of
 * literal arms at all. The map won on both counts.
 *
 * ## `looseObject`, and why an unknown key is a warning
 *
 * fal ships new parameters between snapshot refreshes. A caller who read the
 * release notes before we did should not be blocked by a roster that is a week
 * behind, so an undeclared key is an `unknown_param` warning and the request
 * goes out as written. (Krea, whose schema is `additionalProperties: false`,
 * is the one place in this repo where that is an error instead — there the API
 * itself answers a typo with a 400.)
 *
 * ## Cost
 *
 * Mostly `undefined`, and deliberately. Of the 28 endpoints, only the flat
 * per-image ones can be priced from a request body; per-megapixel needs
 * dimensions the caller usually leaves as a preset, and tiered / conditional
 * rates need a field the request often does not set. See `./pricing.ts` — and
 * `falPriceNote` for the sentence explaining any particular `undefined`.
 *
 * ```ts
 * const params = fal.image({
 *   endpoint: "fal-ai/flux/dev",
 *   prompt: "a cinematic glass cabin beside a frozen lake at sunrise",
 *   image_size: "landscape_4_3",
 * });
 * const res = await fetch(params.request.url, {
 *   method: params.request.method,
 *   headers: { ...params.request.headers, authorization: `Key ${process.env.FAL_KEY}` },
 *   body: JSON.stringify(params),
 * });
 * const { response_url } = await res.json(); // then GET that; never construct it
 * ```
 */

import { createValidator, type PipelineContext } from "../../core/pipeline";
import { toValidated, JSON_HEADERS, type ExactKeys, type Validated } from "../../core/request";
import type { ValidateOptions } from "../../core/options";
import type { ValidateResult } from "../../core/result";
import type { ModelInfo } from "../../core/catalog-types";
import type { EndpointConstraints } from "../../core/constraint-types";
import { runFalChecks } from "./checks";
import { falCostUSD } from "./pricing";
import { falQueueUrl } from "./urls";
import { FAL_DOC_URLS, FAL_IMAGE_ENDPOINTS, type FalImageEndpointId } from "./gen/endpoints.gen";
import { FAL_IMAGE_SHAPES } from "./gen/image-narrow.gen";
import { falImageInputSchema } from "./gen/image-schema.gen";
import { imageModels } from "./gen/models-image.gen";
import type { FalImageBodyById } from "./gen/image-wire.gen";

export { FAL_IMAGE_ENDPOINTS, type FalImageEndpointId } from "./gen/endpoints.gen";
export type { FalImageBodyById, FalImageResultById } from "./gen/image-wire.gen";

/**
 * One endpoint's request params: its published body, plus the route selector.
 *
 * An id the roster does not know still compiles — it widens to a loose body
 * rather than failing — because fal adds endpoints weekly and a curated list
 * is a snapshot. The kernel warns `unknown_model` and the checks stand down;
 * see `./checks.ts`.
 */
export type FalImageArm<Id extends string> = { endpoint: Id } &
  (Id extends FalImageEndpointId ? FalImageBodyById[Id] : Record<string, unknown>);

/** The widest thing `fal.image` accepts — every curated endpoint's body, keyed. */
export type FalImageParams = FalImageArm<FalImageEndpointId | (string & {})>;

/**
 * `.toSdk("fal")` — the shape `@fal-ai/client` takes.
 *
 * fal's own documented call is
 * `fal.subscribe("fal-ai/flux/schnell", { input: { … } })` — the body nested
 * under `input`, with the endpoint id as a separate first argument. So the
 * formatter returns `{ input: body }` and the id stays where it already is,
 * on `.request.url` and on the non-enumerable `modelId`.
 *
 * Verified against fal's own client documentation on 2026-08-24:
 * https://fal.ai/docs/model-apis/client
 */
type FalSdkTargets<B> = { fal: () => { input: B } };

function checkAll(params: FalImageParams, _info: ModelInfo | undefined, ctx: PipelineContext): void {
  runFalChecks(
    params.endpoint,
    FAL_IMAGE_SHAPES,
    FAL_DOC_URLS,
    params as Readonly<Record<string, unknown>>,
    ctx,
  );
}

function estimate(params: FalImageParams) {
  const { endpoint, ...body } = params as Record<string, unknown> & { endpoint: string };
  const costUSD = falCostUSD(endpoint, body);
  return costUSD === undefined ? {} : { costUSD };
}

function finalize(params: FalImageParams): unknown {
  // `endpoint` is the route, never a body field: it comes off here and goes
  // into the URL. A fal endpoint that ever declares a real `endpoint` property
  // fails codegen rather than colliding silently.
  const { endpoint, ...body } = params as Record<string, unknown> & { endpoint: string };
  return toValidated(
    body,
    { url: falQueueUrl(endpoint), method: "POST", headers: JSON_HEADERS },
    { sdk: { fal: () => ({ input: body }) } },
  );
}

const validator = createValidator<FalImageParams, unknown>({
  endpoint: "fal.image",
  schema: falImageInputSchema,
  modelId: (params) => params.endpoint,
  catalog: imageModels,
  checks: [checkAll],
  estimate,
  finalize,
  promptPath: ["prompt"],
});

/**
 * Validates a `fal.image` submit body.
 *
 * The returned object's enumerable properties are the exact fetch JSON body —
 * `endpoint` is a route selector, stripped from the body and interpolated into
 * `.request.url`. The POST returns the queue ENVELOPE (`{ request_id,
 * response_url, … }`), not image bytes: follow the `response_url` it hands
 * back rather than constructing one, and note that `status: "COMPLETED"` does
 * not mean the request succeeded — fal's queue declares no failure state and a
 * failure rides the result document's `error` field. See `./urls.ts`.
 *
 * Auth is yours to add: `Authorization: Key <FAL_KEY>`. fal's own OpenAPI
 * security scheme omits the `Key ` prefix, so unmodel states the header rather
 * than deriving it, and never touches your key.
 */
export const image = validator as unknown as {
  <Id extends FalImageEndpointId | (string & {}), T extends FalImageArm<Id>>(
    params: T & { endpoint: Id } & ExactKeys<T, FalImageArm<Id>>,
    options?: ValidateOptions<T>,
  ): Validated<Omit<T, "endpoint">, FalSdkTargets<Omit<T, "endpoint">>>;
  safe<Id extends FalImageEndpointId | (string & {}), T extends FalImageArm<Id>>(
    params: T & { endpoint: Id } & ExactKeys<T, FalImageArm<Id>>,
    options?: ValidateOptions<T>,
  ): ValidateResult<Validated<Omit<T, "endpoint">, FalSdkTargets<Omit<T, "endpoint">>>>;
  constraintsFor(modelId: string): EndpointConstraints[];
};
