/**
 * `fal.video` — video generation across fal's queue, at one address.
 *
 * `POST https://queue.fal.run/{endpoint}`, flat JSON body,
 * `Authorization: Key <FAL_KEY>`.
 *
 * ## Why there is no `fal.videoFromImage`
 *
 * Every other video provider here forks: `runway.video` and
 * `runway.videoFromImage` are two different POST paths with two different
 * bodies, and the qualified id exists to name the second WIRE ROUTE. At fal
 * there is no second route to name. `fal-ai/veo3.1` and
 * `fal-ai/veo3.1/image-to-video` are the same route — one URL shape, one body
 * shape, one validator — with a different path segment, and the path is a
 * PARAMETER here (`endpoint`) rather than a fork in the code. Adding
 * `fal.videoFromImage` would mean deciding which of the thirty-five curated
 * endpoints belong to it, and the answer would be a list rather than a rule:
 * `minimax/h3/image-to-video` takes its `image_url` OPTIONALLY, so it is a
 * text-to-video route and an image-to-video route depending on the request.
 *
 * So text-to-video, image-to-video, first-and-last-frame interpolation,
 * reference-to-video and clip editing all live at `fal.video`, and which of
 * them a given endpoint serves is a fact on its generated row (`roles`,
 * `videoWire`) that `./unified-video.ts` reads. The address-vs-wire law is
 * satisfied — the address is the category's own verb, bare — and the
 * `src/cli-registry.test.ts` video list carries this argument in prose so a
 * future reader does not "fix" the asymmetry.
 *
 * ## One schema, thirty-five endpoints, per-endpoint narrowing
 *
 * As at `fal.image`: ONE `z.looseObject` for the category, with every bound,
 * requirement and vocabulary living on the generated `FAL_VIDEO_SHAPES` rows
 * that `./checks.ts` reads at run time. It matters more here than anywhere
 * else in this provider, because `duration` is genuinely four different types
 * across these thirty-five endpoints — the string enum `"5"` at kling, the
 * suffixed string `"8s"` at veo3.1, the integer enum `5` at wan, and a free
 * integer 1..15 at pixverse — and a union schema that accepted all four would
 * accept `"8s"` at kling, which fal refuses.
 *
 * At the TYPE level the narrowing comes from {@link FalVideoArm}, indexing the
 * generated by-id body map. See `./image.ts` for the measurement that chose a
 * map over a union of arms.
 *
 * ## Cost
 *
 * Almost entirely `undefined`, and this is the category where that is most
 * defensible. Twenty-six of the thirty-five rows are `conditional`: the rate turns
 * on `resolution`, on `generate_audio`, or — at seedance and gemini-omni — on
 * a TOKEN count computed from the frames actually rendered, which no request
 * body carries. Two endpoints (`fal-ai/minimax/hailuo-02/pro/image-to-video`,
 * `fal-ai/kling-video/o3/pro/video-to-video/edit`) publish one flat per-second
 * rate and reach `ModelCost.perVideoSecond`; everything else answers
 * `undefined` with a sentence from `falPriceNote` explaining which field would
 * have settled it.
 *
 * ```ts
 * const params = fal.video({
 *   endpoint: "fal-ai/veo3.1/image-to-video",
 *   prompt: "the camera pushes slowly through the doorway",
 *   image_url: "https://example.com/frame.png",
 *   duration: "8s",
 *   resolution: "1080p",
 * });
 * const res = await fetch(params.request.url, {
 *   method: params.request.method,
 *   headers: { ...params.request.headers, authorization: `Key ${process.env.FAL_KEY}` },
 *   body: JSON.stringify(params),
 * });
 * const { response_url } = await res.json(); // then GET that; never construct it
 * ```
 */

import { createValidator, type PipelineContext } from "../../core/pipeline";
import { toValidated, JSON_HEADERS, type ExactKeys, type Validated } from "../../core/request";
import type { ValidateOptions } from "../../core/options";
import type { ValidateResult } from "../../core/result";
import type { ModelInfo } from "../../core/catalog-types";
import type { EndpointConstraints } from "../../core/constraint-types";
import { runFalChecks } from "./checks";
import { falCostUSD } from "./pricing";
import { falQueueUrl } from "./urls";
import { FAL_DOC_URLS, FAL_VIDEO_ENDPOINTS, type FalVideoEndpointId } from "./gen/endpoints.gen";
import { FAL_VIDEO_SHAPES } from "./gen/video-narrow.gen";
import { falVideoInputSchema } from "./gen/video-schema.gen";
import { videoModels } from "./gen/models-video.gen";
import type { FalVideoBodyById } from "./gen/video-wire.gen";

export { FAL_VIDEO_ENDPOINTS, type FalVideoEndpointId } from "./gen/endpoints.gen";
export type { FalVideoBodyById, FalVideoResultById } from "./gen/video-wire.gen";

/**
 * One endpoint's request params: its published body, plus the route selector.
 *
 * An id the roster does not know still compiles — it widens to a loose body
 * rather than failing — because fal adds endpoints weekly and a curated list
 * is a snapshot. The kernel warns `unknown_model` and the checks stand down.
 */
export type FalVideoArm<Id extends string> = { endpoint: Id } &
  (Id extends FalVideoEndpointId ? FalVideoBodyById[Id] : Record<string, unknown>);

/** The widest thing `fal.video` accepts — every curated endpoint's body, keyed. */
export type FalVideoParams = FalVideoArm<FalVideoEndpointId | (string & {})>;

/** `.toSdk("fal")` — the `{ input: body }` shape `@fal-ai/client` takes. */
type FalSdkTargets<B> = { fal: () => { input: B } };

function checkAll(params: FalVideoParams, _info: ModelInfo | undefined, ctx: PipelineContext): void {
  runFalChecks(
    params.endpoint,
    FAL_VIDEO_SHAPES,
    FAL_DOC_URLS,
    params as Readonly<Record<string, unknown>>,
    ctx,
  );
}

function estimate(params: FalVideoParams) {
  const { endpoint, ...body } = params as Record<string, unknown> & { endpoint: string };
  const costUSD = falCostUSD(endpoint, body);
  return costUSD === undefined ? {} : { costUSD };
}

function finalize(params: FalVideoParams): unknown {
  // `endpoint` is the route, never a body field. See ./image.ts.
  const { endpoint, ...body } = params as Record<string, unknown> & { endpoint: string };
  return toValidated(
    body,
    { url: falQueueUrl(endpoint), method: "POST", headers: JSON_HEADERS },
    { sdk: { fal: () => ({ input: body }) } },
  );
}

const validator = createValidator<FalVideoParams, unknown>({
  endpoint: "fal.video",
  schema: falVideoInputSchema,
  modelId: (params) => params.endpoint,
  catalog: videoModels,
  checks: [checkAll],
  estimate,
  finalize,
  promptPath: ["prompt"],
});

/**
 * Validates a `fal.video` submit body.
 *
 * The returned object's enumerable properties are the exact fetch JSON body —
 * `endpoint` is a route selector, stripped from the body and interpolated into
 * `.request.url`. The POST returns the queue ENVELOPE, not a clip: follow the
 * `response_url` it hands back rather than constructing one, and note that
 * `status: "COMPLETED"` does not mean the request succeeded — fal's queue
 * declares no failure state and a failure rides the result document's `error`
 * field. Video jobs are the longest-running things in this provider, so this is
 * the category where that matters most. See `./urls.ts`.
 *
 * Auth is yours to add: `Authorization: Key <FAL_KEY>`.
 */
export const video = validator as unknown as {
  <Id extends FalVideoEndpointId | (string & {}), T extends FalVideoArm<Id>>(
    params: T & { endpoint: Id } & ExactKeys<T, FalVideoArm<Id>>,
    options?: ValidateOptions<T>,
  ): Validated<Omit<T, "endpoint">, FalSdkTargets<Omit<T, "endpoint">>>;
  safe<Id extends FalVideoEndpointId | (string & {}), T extends FalVideoArm<Id>>(
    params: T & { endpoint: Id } & ExactKeys<T, FalVideoArm<Id>>,
    options?: ValidateOptions<T>,
  ): ValidateResult<Validated<Omit<T, "endpoint">, FalSdkTargets<Omit<T, "endpoint">>>>;
  constraintsFor(modelId: string): EndpointConstraints[];
};
