/**
 * Generates the typed model catalog from a committed models.dev snapshot,
 * plus the per-provider cross-provider availability tables that back
 * `.toApi(target)`.
 *
 *   bun run codegen             regenerate src/catalog/**\/*.gen.ts from data/models-dev.json
 *   bun run codegen:refresh     fetch https://models.dev/api.json first, then regenerate
 *
 * Output is a pure function of its two committed inputs (the snapshot and
 * data/availability-overrides.json): no timestamps, stable ordering.
 * CI verifies drift with `bun run codegen && git diff --exit-code`.
 */
import { z } from "zod";
import { buildAvailability, renderAvailabilityFile } from "./availability";

const SNAPSHOT_URL = "https://models.dev/api.json";
const SNAPSHOT_PATH = new URL("../data/models-dev.json", import.meta.url).pathname;
const OVERRIDES_PATH = new URL("../data/availability-overrides.json", import.meta.url).pathname;
const CATALOG_DIR = new URL("../src/catalog/", import.meta.url).pathname;
const AVAILABILITY_SUBDIR = "availability/";

// ---------------------------------------------------------------------------
// Raw models.dev shapes. Loose everywhere: unknown upstream additions must
// never break the pipeline — they simply aren't emitted until mapped here.
// ---------------------------------------------------------------------------

const modalityEnum = z.enum(["text", "image", "audio", "video", "pdf"]);

const rawCostSchema = z
  .looseObject({
    input: z.number().optional(),
    output: z.number().optional(),
    cache_read: z.number().optional(),
    cache_write: z.number().optional(),
    reasoning: z.number().optional(),
    input_audio: z.number().optional(),
    output_audio: z.number().optional(),
  })
  .optional();

const rawModelSchema = z.looseObject({
  id: z.string(),
  name: z.string(),
  family: z.string().optional(),
  attachment: z.boolean(),
  reasoning: z.boolean(),
  tool_call: z.boolean(),
  structured_output: z.boolean().optional(),
  temperature: z.boolean().optional(),
  open_weights: z.boolean(),
  release_date: z.string().optional(),
  last_updated: z.string().optional(),
  knowledge: z.string().optional(),
  status: z.enum(["alpha", "beta", "deprecated"]).optional(),
  modalities: z.object({
    input: z.array(modalityEnum),
    output: z.array(modalityEnum),
  }),
  limit: z.looseObject({
    context: z.number(),
    output: z.number().optional(),
    input: z.number().optional(),
  }),
  cost: rawCostSchema,
});

const rawProviderSchema = z.looseObject({
  id: z.string(),
  name: z.string(),
  env: z.array(z.string()).default([]),
  doc: z.string().optional(),
  api: z.string().optional(),
  models: z.record(z.string(), rawModelSchema),
});

const rawSnapshotSchema = z.record(z.string(), rawProviderSchema);

type RawModel = z.output<typeof rawModelSchema>;
type RawProvider = z.output<typeof rawProviderSchema>;

// ---------------------------------------------------------------------------
// Emission — deterministic TypeScript rendering.
// ---------------------------------------------------------------------------

const GEN_HEADER = `// Generated by scripts/codegen.ts — DO NOT EDIT.
// Source: ${SNAPSHOT_URL} (committed snapshot: data/models-dev.json)
// Regenerate with \`bun run codegen\` (or \`bun run codegen:refresh\` to update the snapshot).
`;

const AVAILABILITY_HEADER = `// Generated by scripts/codegen.ts — DO NOT EDIT.
// Derived from data/models-dev.json (${SNAPSHOT_URL}) by the conjunction
// heuristic in scripts/availability.ts, filtered by data/availability-overrides.json.
// Regenerate with \`bun run codegen\` (or \`bun run codegen:refresh\` to update the snapshot).
`;

function quote(value: string): string {
  return JSON.stringify(value);
}

function num(value: number): string {
  return JSON.stringify(value);
}

/** "amazon-bedrock" → "AmazonBedrock"; "openai" → "Openai"; "302ai" → "_302ai". */
function pascalCase(id: string): string {
  const pascal = id
    .split(/[^a-zA-Z0-9]+/)
    .filter(Boolean)
    .map((part) => (part[0]?.toUpperCase() ?? "") + part.slice(1))
    .join("");
  return /^[0-9]/.test(pascal) ? `_${pascal}` : pascal;
}

/** "amazon-bedrock" → "amazonBedrock". */
function camelCase(id: string): string {
  const pascal = pascalCase(id);
  return (pascal[0]?.toLowerCase() ?? "") + pascal.slice(1);
}

function renderStringArray(values: readonly string[]): string {
  return `[${values.map(quote).join(", ")}]`;
}

function renderCost(cost: NonNullable<RawModel["cost"]>): string | undefined {
  const fields: string[] = [];
  const push = (key: string, value: number | undefined) => {
    if (value !== undefined) fields.push(`${key}: ${num(value)}`);
  };
  push("input", cost.input);
  push("output", cost.output);
  push("cacheRead", cost.cache_read);
  push("cacheWrite", cost.cache_write);
  push("reasoning", cost.reasoning);
  push("inputAudio", cost.input_audio);
  push("outputAudio", cost.output_audio);
  if (fields.length === 0) return undefined;
  return `{ ${fields.join(", ")} }`;
}

function renderModel(model: RawModel, indent: string): string {
  const lines: string[] = [];
  const push = (key: string, rendered: string | undefined) => {
    if (rendered !== undefined) lines.push(`${indent}  ${key}: ${rendered},`);
  };
  push("id", quote(model.id));
  push("name", quote(model.name));
  push("family", model.family === undefined ? undefined : quote(model.family));
  push("attachment", String(model.attachment));
  push("reasoning", String(model.reasoning));
  push("toolCall", String(model.tool_call));
  push(
    "structuredOutput",
    model.structured_output === undefined ? undefined : String(model.structured_output),
  );
  push("temperature", model.temperature === undefined ? undefined : String(model.temperature));
  push("openWeights", String(model.open_weights));
  push("knowledge", model.knowledge === undefined ? undefined : quote(model.knowledge));
  push("releaseDate", model.release_date === undefined ? undefined : quote(model.release_date));
  push("lastUpdated", model.last_updated === undefined ? undefined : quote(model.last_updated));
  push("status", model.status === undefined ? undefined : quote(model.status));
  push(
    "modalities",
    `{ input: ${renderStringArray(model.modalities.input)}, output: ${renderStringArray(model.modalities.output)} }`,
  );
  const limitFields = [`context: ${num(model.limit.context)}`];
  if (model.limit.output !== undefined) limitFields.push(`output: ${num(model.limit.output)}`);
  if (model.limit.input !== undefined) limitFields.push(`input: ${num(model.limit.input)}`);
  push("limit", `{ ${limitFields.join(", ")} }`);
  push("cost", model.cost === undefined ? undefined : renderCost(model.cost));
  return `${indent}${quote(model.id)}: {\n${lines.join("\n")}\n${indent}},`;
}

function renderModalityUnion(models: RawModel[], modality: "text" | "image" | "audio" | "video"): string {
  const ids = models.filter((m) => m.modalities.output.includes(modality)).map((m) => quote(m.id));
  if (ids.length === 0) return "never";
  return ids.join(" | ");
}

function renderProviderFile(provider: RawProvider): string {
  const models = Object.values(provider.models).sort((a, b) => (a.id < b.id ? -1 : a.id > b.id ? 1 : 0));
  const pascal = pascalCase(provider.id);

  const providerFields: string[] = [
    `  id: ${quote(provider.id)},`,
    `  name: ${quote(provider.name)},`,
    `  env: ${renderStringArray(provider.env)},`,
  ];
  if (provider.doc !== undefined) providerFields.push(`  doc: ${quote(provider.doc)},`);
  if (provider.api !== undefined) providerFields.push(`  api: ${quote(provider.api)},`);

  return `${GEN_HEADER}
import type { ModelInfo, ProviderInfo } from "../core/catalog-types";

export const provider = {
${providerFields.join("\n")}
} as const satisfies ProviderInfo;

export const models = {
${models.map((m) => renderModel(m, "  ")).join("\n")}
} as const satisfies Record<string, ModelInfo>;

export type ${pascal}ModelId = keyof typeof models;
export type ${pascal}TextModelId = ${renderModalityUnion(models, "text")};
export type ${pascal}ImageModelId = ${renderModalityUnion(models, "image")};
export type ${pascal}AudioModelId = ${renderModalityUnion(models, "audio")};
export type ${pascal}VideoModelId = ${renderModalityUnion(models, "video")};
`;
}

function renderIndexFile(providers: RawProvider[]): string {
  const entries = providers.map((p) => ({ id: p.id, importName: `${camelCase(p.id)}Gen` }));

  const collisions = new Map<string, string>();
  for (const entry of entries) {
    const existing = collisions.get(entry.importName);
    if (existing !== undefined) {
      throw new Error(`Import name collision between providers "${existing}" and "${entry.id}"`);
    }
    collisions.set(entry.importName, entry.id);
  }

  return `${GEN_HEADER}
import type { ModelInfo, ProviderInfo } from "../core/catalog-types";
${entries.map((e) => `import * as ${e.importName} from "./${e.id}.gen";`).join("\n")}

export interface ProviderCatalog {
  provider: ProviderInfo;
  models: Record<string, ModelInfo>;
}

export type ProviderId =
${providers.map((p) => `  | ${quote(p.id)}`).join("\n")};

/**
 * The full registry, deliberately widened to ModelInfo (no literal types).
 * Provider subpaths with validators (e.g. \`unmodel/openai\`) re-export their
 * own catalog slice with literal types when you need precise inference.
 */
export const catalog: Record<ProviderId, ProviderCatalog> = {
${entries.map((e) => `  ${quote(collisions.get(e.importName)!)}: ${e.importName},`).join("\n")}
};

export function getProvider(providerId: ProviderId | (string & {})): ProviderCatalog | undefined {
  // Object.hasOwn: ids like "constructor" must not resolve to inherited
  // Object.prototype members.
  return Object.hasOwn(catalog, providerId)
    ? (catalog as Record<string, ProviderCatalog>)[providerId]
    : undefined;
}

export function getModel(
  providerId: ProviderId | (string & {}),
  modelId: string,
): ModelInfo | undefined {
  const models = getProvider(providerId)?.models;
  return models !== undefined && Object.hasOwn(models, modelId) ? models[modelId] : undefined;
}
`;
}

/**
 * Pure generation: snapshot JSON → map of catalog-relative path → content.
 *
 * Keys are relative to `src/catalog/`, so availability tables land under
 * `availability/<id>.gen.ts` and `main()`'s single write loop covers them.
 * `overrides` is the parsed `data/availability-overrides.json`; omit it and
 * no availability tables are emitted (catalog-only fixtures).
 */
export function generate(snapshot: unknown, overrides?: unknown): Map<string, string> {
  const parsed = rawSnapshotSchema.safeParse(snapshot);
  if (!parsed.success) {
    const details = parsed.error.issues
      .slice(0, 20)
      .map((issue) => `  ${issue.path.join(".")}: ${issue.message}`)
      .join("\n");
    throw new Error(`models.dev snapshot failed validation:\n${details}`);
  }

  const providers = Object.values(parsed.data).sort((a, b) => (a.id < b.id ? -1 : a.id > b.id ? 1 : 0));
  const files = new Map<string, string>();
  for (const provider of providers) {
    files.set(`${provider.id}.gen.ts`, renderProviderFile(provider));
  }
  files.set("index.ts", renderIndexFile(providers));

  if (overrides !== undefined) {
    const availability = buildAvailability(snapshot, overrides);
    for (const [providerId, map] of availability.providers) {
      files.set(
        `${AVAILABILITY_SUBDIR}${providerId}.gen.ts`,
        renderAvailabilityFile(providerId, map, AVAILABILITY_HEADER),
      );
    }
  }
  return files;
}

/** Recursively sorts object keys so the committed snapshot diffs cleanly. */
export function sortKeysDeep(value: unknown): unknown {
  if (Array.isArray(value)) return value.map(sortKeysDeep);
  if (typeof value === "object" && value !== null) {
    const sorted: Record<string, unknown> = {};
    for (const key of Object.keys(value).sort()) {
      sorted[key] = sortKeysDeep((value as Record<string, unknown>)[key]);
    }
    return sorted;
  }
  return value;
}

async function main(): Promise<void> {
  const refresh = process.argv.includes("--refresh");

  if (refresh) {
    console.log(`Fetching ${SNAPSHOT_URL} ...`);
    const response = await fetch(SNAPSHOT_URL);
    if (!response.ok) throw new Error(`Fetch failed: ${response.status} ${response.statusText}`);
    const raw: unknown = await response.json();
    await Bun.write(SNAPSHOT_PATH, `${JSON.stringify(sortKeysDeep(raw), null, 2)}\n`);
    console.log(`Wrote ${SNAPSHOT_PATH}`);
  }

  const snapshotFile = Bun.file(SNAPSHOT_PATH);
  if (!(await snapshotFile.exists())) {
    throw new Error(`Snapshot not found at ${SNAPSHOT_PATH}. Run \`bun run codegen:refresh\` once.`);
  }
  const overridesFile = Bun.file(OVERRIDES_PATH);
  if (!(await overridesFile.exists())) {
    throw new Error(`Availability overrides not found at ${OVERRIDES_PATH}.`);
  }
  const files = generate(await snapshotFile.json(), await overridesFile.json());

  // Remove stale .gen.ts files for providers that left the snapshot — in the
  // catalog root and in the availability subdirectory, whose membership also
  // shrinks when a model stops being served in more than one place.
  const { readdir, rm, mkdir } = await import("node:fs/promises");
  await mkdir(CATALOG_DIR, { recursive: true });
  await mkdir(`${CATALOG_DIR}${AVAILABILITY_SUBDIR}`, { recursive: true });
  for (const dir of ["", AVAILABILITY_SUBDIR]) {
    for (const existing of await readdir(`${CATALOG_DIR}${dir}`)) {
      const name = `${dir}${existing}`;
      if (existing.endsWith(".gen.ts") && !files.has(name)) {
        await rm(`${CATALOG_DIR}${name}`);
        console.log(`Removed stale ${name}`);
      }
    }
  }

  for (const [name, content] of files) {
    await Bun.write(`${CATALOG_DIR}${name}`, content);
  }
  console.log(`Generated ${files.size} files into src/catalog/`);
}

if (import.meta.main) {
  await main();
}
