/**
 * Generates the typed model catalog from a committed models.dev snapshot,
 * plus the per-provider cross-provider availability tables that back
 * `.toApi(target)`.
 *
 *   bun run codegen             regenerate src/catalog/**\/*.gen.ts from data/models-dev.json
 *   bun run codegen:refresh     fetch https://models.dev/api.json first, then regenerate
 *
 * Output is a pure function of its two committed inputs (the snapshot and
 * data/availability-overrides.json): no timestamps, stable ordering.
 * CI verifies drift with `bun run codegen && git diff --exit-code`.
 */
import { z } from "zod";
import { buildAvailability, overridesSchema, renderAvailabilityFile } from "./availability";

const SNAPSHOT_URL = "https://models.dev/api.json";
const SNAPSHOT_PATH = new URL("../data/models-dev.json", import.meta.url).pathname;
const OVERRIDES_PATH = new URL("../data/availability-overrides.json", import.meta.url).pathname;
const CATALOG_DIR = new URL("../src/catalog/", import.meta.url).pathname;
const AVAILABILITY_SUBDIR = "availability/";

// ---------------------------------------------------------------------------
// Raw models.dev shapes. Loose everywhere: unknown upstream additions must
// never break the pipeline — they simply aren't emitted until mapped here.
// ---------------------------------------------------------------------------

const modalityEnum = z.enum(["text", "image", "audio", "video", "pdf"]);

const rawCostSchema = z
  .looseObject({
    input: z.number().optional(),
    output: z.number().optional(),
    cache_read: z.number().optional(),
    cache_write: z.number().optional(),
    reasoning: z.number().optional(),
    input_audio: z.number().optional(),
    output_audio: z.number().optional(),
  })
  .optional();

const rawModelSchema = z.looseObject({
  id: z.string(),
  name: z.string(),
  family: z.string().optional(),
  attachment: z.boolean(),
  reasoning: z.boolean(),
  tool_call: z.boolean(),
  structured_output: z.boolean().optional(),
  temperature: z.boolean().optional(),
  open_weights: z.boolean(),
  release_date: z.string().optional(),
  last_updated: z.string().optional(),
  knowledge: z.string().optional(),
  status: z.enum(["alpha", "beta", "deprecated"]).optional(),
  modalities: z.object({
    input: z.array(modalityEnum),
    output: z.array(modalityEnum),
  }),
  limit: z.looseObject({
    context: z.number(),
    output: z.number().optional(),
    input: z.number().optional(),
  }),
  cost: rawCostSchema,
});

const rawProviderSchema = z.looseObject({
  id: z.string(),
  name: z.string(),
  env: z.array(z.string()).default([]),
  doc: z.string().optional(),
  api: z.string().optional(),
  models: z.record(z.string(), rawModelSchema),
});

const rawSnapshotSchema = z.record(z.string(), rawProviderSchema);

type RawModel = z.output<typeof rawModelSchema>;
type RawProvider = z.output<typeof rawProviderSchema>;

// ---------------------------------------------------------------------------
// Emission — deterministic TypeScript rendering.
// ---------------------------------------------------------------------------

const GEN_HEADER = `// Generated by scripts/codegen.ts — DO NOT EDIT.
// Source: ${SNAPSHOT_URL} (committed snapshot: data/models-dev.json)
// Regenerate with \`bun run codegen\` (or \`bun run codegen:refresh\` to update the snapshot).
`;

const AVAILABILITY_HEADER = `// Generated by scripts/codegen.ts — DO NOT EDIT.
// Derived from data/models-dev.json (${SNAPSHOT_URL}) by the conjunction
// heuristic in scripts/availability.ts, filtered by data/availability-overrides.json.
// Regenerate with \`bun run codegen\` (or \`bun run codegen:refresh\` to update the snapshot).
`;

const CHAT_HEADER = `// Generated by scripts/codegen.ts — DO NOT EDIT.
// Source: ${SNAPSHOT_URL} (committed snapshot: data/models-dev.json), scoped by
// the \`providers\` list in data/availability-overrides.json.
// Regenerate with \`bun run codegen\` (or \`bun run codegen:refresh\` to update the snapshot).
`;

/**
 * Targets whose URL embeds per-instance configuration (a region, a project, a
 * resource endpoint, an account id) and therefore cannot be reached from a
 * bare `"provider/model"` ref. `src/core/translate/endpoints.ts` is the
 * authority — these are exactly the entries there that carry `config` — but
 * codegen must not import from `src/`, so the list is repeated here and the
 * agreement is asserted in `test/chat/refs.test.ts`.
 */
const CHAT_FACTORY_PROVIDERS: ReadonlySet<string> = new Set([
  "amazon-bedrock",
  "azure",
  "cloudflare-workers-ai",
  "google-vertex",
]);

function quote(value: string): string {
  return JSON.stringify(value);
}

function num(value: number): string {
  return JSON.stringify(value);
}

/** "amazon-bedrock" → "AmazonBedrock"; "openai" → "Openai"; "302ai" → "_302ai". */
function pascalCase(id: string): string {
  const pascal = id
    .split(/[^a-zA-Z0-9]+/)
    .filter(Boolean)
    .map((part) => (part[0]?.toUpperCase() ?? "") + part.slice(1))
    .join("");
  return /^[0-9]/.test(pascal) ? `_${pascal}` : pascal;
}

/** "amazon-bedrock" → "amazonBedrock". */
function camelCase(id: string): string {
  const pascal = pascalCase(id);
  return (pascal[0]?.toLowerCase() ?? "") + pascal.slice(1);
}

function renderStringArray(values: readonly string[]): string {
  return `[${values.map(quote).join(", ")}]`;
}

function renderCost(cost: NonNullable<RawModel["cost"]>): string | undefined {
  const fields: string[] = [];
  const push = (key: string, value: number | undefined) => {
    if (value !== undefined) fields.push(`${key}: ${num(value)}`);
  };
  push("input", cost.input);
  push("output", cost.output);
  push("cacheRead", cost.cache_read);
  push("cacheWrite", cost.cache_write);
  push("reasoning", cost.reasoning);
  push("inputAudio", cost.input_audio);
  push("outputAudio", cost.output_audio);
  if (fields.length === 0) return undefined;
  return `{ ${fields.join(", ")} }`;
}

/** `{ context: 200000, output: 64000 }` — one spelling, shared by both emitters. */
function renderLimit(limit: RawModel["limit"]): string {
  const fields = [`context: ${num(limit.context)}`];
  if (limit.output !== undefined) fields.push(`output: ${num(limit.output)}`);
  if (limit.input !== undefined) fields.push(`input: ${num(limit.input)}`);
  return `{ ${fields.join(", ")} }`;
}

/** `{ input: ["text"], output: ["text"] }` — one spelling, shared by both emitters. */
function renderModalities(modalities: RawModel["modalities"]): string {
  return `{ input: ${renderStringArray(modalities.input)}, output: ${renderStringArray(modalities.output)} }`;
}

function renderModel(model: RawModel, indent: string): string {
  const lines: string[] = [];
  const push = (key: string, rendered: string | undefined) => {
    if (rendered !== undefined) lines.push(`${indent}  ${key}: ${rendered},`);
  };
  push("id", quote(model.id));
  push("name", quote(model.name));
  push("family", model.family === undefined ? undefined : quote(model.family));
  push("attachment", String(model.attachment));
  push("reasoning", String(model.reasoning));
  push("toolCall", String(model.tool_call));
  push(
    "structuredOutput",
    model.structured_output === undefined ? undefined : String(model.structured_output),
  );
  push("temperature", model.temperature === undefined ? undefined : String(model.temperature));
  push("openWeights", String(model.open_weights));
  push("knowledge", model.knowledge === undefined ? undefined : quote(model.knowledge));
  push("releaseDate", model.release_date === undefined ? undefined : quote(model.release_date));
  push("lastUpdated", model.last_updated === undefined ? undefined : quote(model.last_updated));
  push("status", model.status === undefined ? undefined : quote(model.status));
  push("modalities", renderModalities(model.modalities));
  push("limit", renderLimit(model.limit));
  push("cost", model.cost === undefined ? undefined : renderCost(model.cost));
  return `${indent}${quote(model.id)}: {\n${lines.join("\n")}\n${indent}},`;
}

function renderModalityUnion(models: RawModel[], modality: "text" | "image" | "audio" | "video"): string {
  const ids = models.filter((m) => m.modalities.output.includes(modality)).map((m) => quote(m.id));
  if (ids.length === 0) return "never";
  return ids.join(" | ");
}

function renderProviderFile(provider: RawProvider): string {
  const models = Object.values(provider.models).sort((a, b) => (a.id < b.id ? -1 : a.id > b.id ? 1 : 0));
  const pascal = pascalCase(provider.id);

  const providerFields: string[] = [
    `  id: ${quote(provider.id)},`,
    `  name: ${quote(provider.name)},`,
    `  env: ${renderStringArray(provider.env)},`,
  ];
  if (provider.doc !== undefined) providerFields.push(`  doc: ${quote(provider.doc)},`);
  if (provider.api !== undefined) providerFields.push(`  api: ${quote(provider.api)},`);

  return `${GEN_HEADER}
import type { ModelInfo, ProviderInfo } from "../core/catalog-types";

export const provider = {
${providerFields.join("\n")}
} as const satisfies ProviderInfo;

export const models = {
${models.map((m) => renderModel(m, "  ")).join("\n")}
} as const satisfies Record<string, ModelInfo>;

export type ${pascal}ModelId = keyof typeof models;
export type ${pascal}TextModelId = ${renderModalityUnion(models, "text")};
export type ${pascal}ImageModelId = ${renderModalityUnion(models, "image")};
export type ${pascal}AudioModelId = ${renderModalityUnion(models, "audio")};
export type ${pascal}VideoModelId = ${renderModalityUnion(models, "video")};
`;
}

function renderIndexFile(providers: RawProvider[]): string {
  const entries = providers.map((p) => ({ id: p.id, importName: `${camelCase(p.id)}Gen` }));

  const collisions = new Map<string, string>();
  for (const entry of entries) {
    const existing = collisions.get(entry.importName);
    if (existing !== undefined) {
      throw new Error(`Import name collision between providers "${existing}" and "${entry.id}"`);
    }
    collisions.set(entry.importName, entry.id);
  }

  return `${GEN_HEADER}
import type { ModelInfo, ProviderInfo } from "../core/catalog-types";
${entries.map((e) => `import * as ${e.importName} from "./${e.id}.gen";`).join("\n")}

export interface ProviderCatalog {
  provider: ProviderInfo;
  models: Record<string, ModelInfo>;
}

export type ProviderId =
${providers.map((p) => `  | ${quote(p.id)}`).join("\n")};

/**
 * The full registry, deliberately widened to ModelInfo (no literal types).
 * Provider subpaths with validators (e.g. \`unmodel/openai\`) re-export their
 * own catalog slice with literal types when you need precise inference.
 */
export const catalog: Record<ProviderId, ProviderCatalog> = {
${entries.map((e) => `  ${quote(collisions.get(e.importName)!)}: ${e.importName},`).join("\n")}
};

export function getProvider(providerId: ProviderId | (string & {})): ProviderCatalog | undefined {
  // Object.hasOwn: ids like "constructor" must not resolve to inherited
  // Object.prototype members.
  return Object.hasOwn(catalog, providerId)
    ? (catalog as Record<string, ProviderCatalog>)[providerId]
    : undefined;
}

export function getModel(
  providerId: ProviderId | (string & {}),
  modelId: string,
): ModelInfo | undefined {
  const models = getProvider(providerId)?.models;
  return models !== undefined && Object.hasOwn(models, modelId) ? models[modelId] : undefined;
}
`;
}

// ---------------------------------------------------------------------------
// The unified `unmodel/chat` tables.
//
// `unmodel/chat` is the one entry point that speaks about *every* provider at
// once (`chat({ model: "anthropic/claude-opus-5" })`), so unlike the
// per-provider catalogs it cannot be sliced per subpath. That forces two
// files rather than one, split along the only axis that matters for bundle
// weight — types are erased, values are not:
//
//   • `chat-refs.gen.ts`    TYPE-ONLY. Zero runtime bytes; ~50 KB of `.d.ts`.
//   • `chat-profiles.gen.ts` runtime. The slim capability/limit/cost subset a
//     request check actually reads, and nothing else.
//
// Keeping `name`, `family`, `openWeights`, `releaseDate`, `lastUpdated` and
// `knowledge` out of the profile table is worth ~90 KB of shipped source for
// data no validation path consults.
// ---------------------------------------------------------------------------

/** A text-output model — the rows `unmodel/chat` can address. */
function isTextModel(model: RawModel): boolean {
  return model.modalities.output.includes("text");
}

/** Providers reachable as `"provider/model"`, sorted, with their text models. */
function chatScope(
  providers: readonly RawProvider[],
  overrides: z.output<typeof overridesSchema>,
): Array<{ id: string; models: RawModel[] }> {
  const byId = new Map(providers.map((provider) => [provider.id, provider]));
  const targetOnly = new Set(overrides.targetOnly);
  const scope: Array<{ id: string; models: RawModel[] }> = [];
  for (const id of [...overrides.providers].sort()) {
    if (targetOnly.has(id) || CHAT_FACTORY_PROVIDERS.has(id)) continue;
    const provider = byId.get(id);
    if (provider === undefined) {
      throw new Error(`chat scope names provider "${id}", which is not in the snapshot.`);
    }
    const models = Object.values(provider.models)
      .filter(isTextModel)
      .sort((a, b) => (a.id < b.id ? -1 : a.id > b.id ? 1 : 0));
    if (models.length === 0) continue;
    scope.push({ id, models });
  }
  return scope;
}

/**
 * The model-ref union, written out as **fully expanded string literals**
 * (`"openai/gpt-5" | "openai/gpt-5-mini" | …`) rather than the tempting
 * `` `openai/${OpenaiTextModelId}` `` template arms.
 *
 * Both spell the same type. They do not cost the same: a spike over this
 * snapshot measured 5.7k types / 0 instantiations for the expanded union
 * against 26.5k for the template form, because every template arm has to be
 * re-instantiated at each comparison site while a plain literal union is
 * interned once. ~52 KB of `.d.ts` for a 4.6× cheaper check on the type most
 * editors will resolve on every keystroke is the right trade.
 */
function renderChatRefsFile(scope: ReturnType<typeof chatScope>): string {
  const refs: string[] = [];
  for (const { id, models } of scope) {
    for (const model of models) refs.push(`${id}/${model.id}`);
  }
  return `${CHAT_HEADER}
/**
 * The ${scope.length} providers \`unmodel/chat\` can send to: every provider with a chat
 * validator, minus the factory-configured targets (amazon-bedrock, azure,
 * cloudflare-workers-ai, google-vertex), whose URL needs config a bare
 * \`"provider/model"\` ref cannot carry, and minus cohere, whose wire format is
 * a fifth dialect with no codec.
 */
export type ChatProviderId =
${scope.map((entry) => `  | ${quote(entry.id)}`).join("\n")};

/**
 * Every \`"provider/model"\` pair \`chat()\` accepts — ${refs.length} of them.
 *
 * Model ids may themselves contain slashes (openrouter serves
 * \`"anthropic/claude-opus-5"\`, so the ref is
 * \`"openrouter/anthropic/claude-opus-5"\`), which is why \`parseModelRef\` splits
 * on the FIRST slash and never the last.
 */
export type ChatModelRef =
${refs.map((ref) => `  | ${quote(ref)}`).join("\n")};
`;
}

/** `{ input: ["text","image"], output: ["text"] }` → `M_TEXT_IMAGE__TEXT`. */
function modalitySignatureName(modalities: RawModel["modalities"]): string {
  const part = (values: readonly string[]): string =>
    values.map((value) => value.toUpperCase()).join("_");
  return `M_${part(modalities.input)}__${part(modalities.output)}`;
}

/** One profile row: the slim subset, in `ModelInfo` field order. */
function renderProfile(model: RawModel, modalitiesRef: string): string {
  const fields: string[] = [
    `attachment: ${String(model.attachment)}`,
    `reasoning: ${String(model.reasoning)}`,
    `toolCall: ${String(model.tool_call)}`,
  ];
  if (model.structured_output !== undefined) {
    fields.push(`structuredOutput: ${String(model.structured_output)}`);
  }
  if (model.temperature !== undefined) fields.push(`temperature: ${String(model.temperature)}`);
  if (model.status !== undefined) fields.push(`status: ${quote(model.status)}`);
  fields.push(`modalities: ${modalitiesRef}`);
  fields.push(`limit: ${renderLimit(model.limit)}`);
  const cost = model.cost === undefined ? undefined : renderCost(model.cost);
  if (cost !== undefined) fields.push(`cost: ${cost}`);
  return `${quote(model.id)}: { ${fields.join(", ")} },`;
}

/**
 * The runtime profile table.
 *
 * Two shape decisions:
 *
 * - **Modality signatures are hoisted** into named consts. Only 44 distinct
 *   `{input, output}` pairs exist across 1.3k models and one of them accounts
 *   for half the rows, so inlining them costs ~50 KB of source and 1,295
 *   redundant objects at runtime for no information. The names are derived
 *   from the signature (`M_TEXT_IMAGE__TEXT`), not from an index, so adding a
 *   new signature does not renumber — and therefore does not churn — every
 *   row below it.
 * - **Fields are emitted even when \`false\`**, unlike the size-conscious
 *   omission elsewhere, so a row here is *literally* the corresponding row in
 *   \`<provider>.gen.ts\` narrowed by \`Pick\`. That is what lets the drift test
 *   in \`scripts/codegen.test.ts\` be an exact deep-equality rather than an
 *   equality-modulo-defaults, and an exact test is the only kind that catches
 *   a codegen bug that flips a default.
 */
function renderChatProfilesFile(scope: ReturnType<typeof chatScope>): string {
  const signatures = new Map<string, string>();
  for (const { models } of scope) {
    for (const model of models) {
      signatures.set(modalitySignatureName(model.modalities), renderModalities(model.modalities));
    }
  }
  const consts = [...signatures.entries()]
    .sort((a, b) => (a[0] < b[0] ? -1 : a[0] > b[0] ? 1 : 0))
    .map(([name, value]) => `const ${name} = ${value} as const;`)
    .join("\n");

  const rows = scope
    .map(
      ({ id, models }) =>
        `  ${quote(id)}: {\n${models
          .map((model) => `    ${renderProfile(model, modalitySignatureName(model.modalities))}`)
          .join("\n")}\n  },`,
    )
    .join("\n");

  return `${CHAT_HEADER}
import type { ModelInfo } from "../core/catalog-types";

/**
 * What \`unmodel/chat\` needs to know about a model to check a request against
 * it: what it accepts, what it can do, how big it is and what it costs. A
 * \`Pick\` of \`ModelInfo\` rather than a fresh interface, so a field rename in
 * the catalog contract fails \`tsc\` here instead of silently splitting the two
 * vocabularies.
 */
export type ChatModelProfile = Pick<
  ModelInfo,
  | "attachment"
  | "reasoning"
  | "toolCall"
  | "structuredOutput"
  | "temperature"
  | "status"
  | "modalities"
  | "limit"
  | "cost"
>;

/** Provider id → model id → profile. */
export type ChatCatalog = Readonly<Record<string, Readonly<Record<string, ChatModelProfile>>>>;

// Hoisted modality signatures — see the emitter's doc comment for why.
${consts}

/**
 * Every text model of every provider \`unmodel/chat\` can address, keyed
 * \`provider → model\`. Deliberately annotated \`ChatCatalog\` rather than
 * \`as const satisfies\`: the literal type of a 1.3k-row table is a real tsc
 * cost on every file that touches it, and nothing needs the literals — the
 * precise \`"provider/model"\` surface is \`ChatModelRef\`, which is type-only
 * and therefore free at runtime.
 */
export const chatProfiles: ChatCatalog = {
${rows}
};
`;
}

/**
 * Pure generation: snapshot JSON → map of catalog-relative path → content.
 *
 * Keys are relative to `src/catalog/`, so availability tables land under
 * `availability/<id>.gen.ts` and `main()`'s single write loop covers them.
 * `overrides` is the parsed `data/availability-overrides.json`; omit it and
 * no availability tables are emitted (catalog-only fixtures).
 */
export function generate(snapshot: unknown, overrides?: unknown): Map<string, string> {
  const parsed = rawSnapshotSchema.safeParse(snapshot);
  if (!parsed.success) {
    const details = parsed.error.issues
      .slice(0, 20)
      .map((issue) => `  ${issue.path.join(".")}: ${issue.message}`)
      .join("\n");
    throw new Error(`models.dev snapshot failed validation:\n${details}`);
  }

  const providers = Object.values(parsed.data).sort((a, b) => (a.id < b.id ? -1 : a.id > b.id ? 1 : 0));
  const files = new Map<string, string>();
  for (const provider of providers) {
    files.set(`${provider.id}.gen.ts`, renderProviderFile(provider));
  }
  files.set("index.ts", renderIndexFile(providers));

  if (overrides !== undefined) {
    const availability = buildAvailability(snapshot, overrides);
    for (const [providerId, map] of availability.providers) {
      files.set(
        `${AVAILABILITY_SUBDIR}${providerId}.gen.ts`,
        renderAvailabilityFile(providerId, map, AVAILABILITY_HEADER),
      );
    }

    // The unified `unmodel/chat` tables. Gated on `overrides` for the same
    // reason the availability tables are: the provider scope is that file's
    // `providers` list, not something the snapshot can supply. `main()`'s
    // stale-file sweep removes any `src/catalog/**/*.gen.ts` this map does not
    // name, so both files have to be produced here rather than written on the
    // side.
    const parsedOverrides = overridesSchema.safeParse(overrides);
    if (!parsedOverrides.success) {
      throw new Error("availability overrides failed validation (see buildAvailability)");
    }
    const scope = chatScope(providers, parsedOverrides.data);
    files.set("chat-refs.gen.ts", renderChatRefsFile(scope));
    files.set("chat-profiles.gen.ts", renderChatProfilesFile(scope));
  }
  return files;
}

/** Recursively sorts object keys so the committed snapshot diffs cleanly. */
export function sortKeysDeep(value: unknown): unknown {
  if (Array.isArray(value)) return value.map(sortKeysDeep);
  if (typeof value === "object" && value !== null) {
    const sorted: Record<string, unknown> = {};
    for (const key of Object.keys(value).sort()) {
      sorted[key] = sortKeysDeep((value as Record<string, unknown>)[key]);
    }
    return sorted;
  }
  return value;
}

async function main(): Promise<void> {
  const refresh = process.argv.includes("--refresh");

  if (refresh) {
    console.log(`Fetching ${SNAPSHOT_URL} ...`);
    const response = await fetch(SNAPSHOT_URL);
    if (!response.ok) throw new Error(`Fetch failed: ${response.status} ${response.statusText}`);
    const raw: unknown = await response.json();
    await Bun.write(SNAPSHOT_PATH, `${JSON.stringify(sortKeysDeep(raw), null, 2)}\n`);
    console.log(`Wrote ${SNAPSHOT_PATH}`);
  }

  const snapshotFile = Bun.file(SNAPSHOT_PATH);
  if (!(await snapshotFile.exists())) {
    throw new Error(`Snapshot not found at ${SNAPSHOT_PATH}. Run \`bun run codegen:refresh\` once.`);
  }
  const overridesFile = Bun.file(OVERRIDES_PATH);
  if (!(await overridesFile.exists())) {
    throw new Error(`Availability overrides not found at ${OVERRIDES_PATH}.`);
  }
  const files = generate(await snapshotFile.json(), await overridesFile.json());

  // Remove stale .gen.ts files for providers that left the snapshot — in the
  // catalog root and in the availability subdirectory, whose membership also
  // shrinks when a model stops being served in more than one place.
  const { readdir, rm, mkdir } = await import("node:fs/promises");
  await mkdir(CATALOG_DIR, { recursive: true });
  await mkdir(`${CATALOG_DIR}${AVAILABILITY_SUBDIR}`, { recursive: true });
  for (const dir of ["", AVAILABILITY_SUBDIR]) {
    for (const existing of await readdir(`${CATALOG_DIR}${dir}`)) {
      const name = `${dir}${existing}`;
      if (existing.endsWith(".gen.ts") && !files.has(name)) {
        await rm(`${CATALOG_DIR}${name}`);
        console.log(`Removed stale ${name}`);
      }
    }
  }

  for (const [name, content] of files) {
    await Bun.write(`${CATALOG_DIR}${name}`, content);
  }
  console.log(`Generated ${files.size} files into src/catalog/`);
}

if (import.meta.main) {
  await main();
}
